### ISSUE TITLE
toggle comment shortcut in query editor

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#10]
The query editor supported toggling comments.
The default shortcuts `cmd + /` for "toggle line comment" and `option + cmd + /` for "toggle block comment" should work fine for the muscle memory of most people.

`ctrl  + cmd + ↑` and `ctrl  + cmd + ↓` for "swap line up/down" would also be very helpful.

**Comment by jakob** [comment]
Here's a build of Postico with cmd-/ for toggle line comment and cmd-opt-/ for toggle block comment just like you suggested. It works pretty similar to sublime.
https://eggerapps-downloads.s3.amazonaws.com/postico-2015-06-29.zip

Would love to hear your comments.

**Comment by qwesda** [comment]
works like a charm, thanks!

**Comment by ottob** [comment]
:+1: thanks!

**Comment by danillos** [comment]
Please add it to the public version, this will help me a lot.

**Comment by jakob** [comment]
Feature is now public in 0.25

https://eggerapps.at/postico/changelist.html
