### ISSUE TITLE
Insert from query history - easier inserting into editor

### ISSUE THREAD

**Issue by kruser** [jakob/Postico#101]
Minor request here, in order to insert a query from my history I have to click a query on the left and then click the "Insert into Editor" button over on the right which feels very unnatural to do repeatedly. 

I naturally tried to just double-click if I picked one with my mouse or hit enter if I was navigating with my arrows. It would be nice if both triggered the insert.

![image](https://cloud.githubusercontent.com/assets/2208700/10765065/1b53f0b6-7c9f-11e5-91a7-9576b5be580c.png)

Very nice how "esc" closes it.

**Comment by jakob** [comment]
Fixed in version 1.0
https://eggerapps.at/postico/changelist.html

**Comment by kruser** [comment]
Thanks @jakob
