### ISSUE TITLE
<cmd + R> should not close open schemas in the sidebar

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#102]
Every time I create a table through the sql editor and reload the sidebar with <cmd + R> all the opened schemas are getting closed, which gets a bit annoying over time. It would be nice if

a) the open/close states of the schemas in the sidebar would remain stable across reloads
b) `CREATE`, `DROP` and maybe `ALTER` statements would automatically invalidate the corresponding schema and table information

**Comment by qwesda** [comment]
any chance this (at least the a) part) could make it into the next release?

**Comment by humancopy** [comment]
👍 

This is actually quite annoying when opening a table within a schema (sidebar closed), press cmd+r to reload the content, click the schema name in the toolbar (expect to go back to the schema) and all schemas are closed. I keep on opening tables from the main schema every time! 😅

**Comment by jakob** [comment]
I've now fixed part a) for the sidebar; schemas are now no longer collapsed when reloading.

Please download a recent build and test:
https://eggerapps.at/postico/builds/

Part b) (auto-refreshing after CREATE and ALTER statements) is something I'm probably not going to fix right now. The way it is currently, you at least know you have to refresh manually. If I try to detect changes, it's only going to work in some cases (eg. it might not work when doing changes in a procedure, or when using multiple windows/tabs, etc.). For now I think predictability of the UI is more important, but I might rethink this in the future.

I still need to store expanded schemas for the database view, but I think that is used less than the sidebar.

**Comment by humancopy** [comment]
Yes it's fixed in the sidebar but not in the main view. After reloading the schemas in the main view are closed again. I use the app without the sidebar.

So to reproduce:

1. Open a schema and go into a table
2. Reload the data
3. Click the schema name in the toolbar to go back
4. Schema is closed in main view - expected to be open

Thanks 😄

**Comment by jakob** [comment]
@humancopy Thanks for testing! Yes, the main view is what I meant with "database view"

**Comment by qwesda** [comment]
works as advertised for me, Thanks!

I can see how an incomplete implementation for b) might be more annoying than none at all and with the schemas retaining their state CMD+R is already a lotless painful.

**Comment by jakob** [comment]
@humancopy I've now also stored the expanded state of items in the main view -- please test a build from here: https://eggerapps.at/postico/builds/

This issue has proved to be quite a rabbit hole. As I was testing this feature, I realised that there is a lot more state that I should save, eg. the currently selected item, or the current scroll position. And it would be best if the state would be saved across restarts of the app as well -- not just when reloading.

**Comment by qwesda** [comment]
nice to hear about selected items/scroll position (#367)! 

I'm not sure about maintaining this state across restarts though ...  might be little payoff for a lot of hassle and edge cases.

**Comment by humancopy** [comment]
It's working good, just that can see the screen reload, it's not so smooth ... 😄

**Comment by jakob** [comment]
I'm closing this issue. I think it works good enough for now, and further refinements would need a lot of refactoring.
