### ISSUE TITLE
"copy INSERT statement" should have line-breaks between rows

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#104]
copying many rows with the "copy INSERT statement" leads potentially to one very long line. 
Sadly many text editors handle long lines very badly, especially if they try to apply syntax highlighting.
Splitting the statement over many lines removes this issue and also improves the readability of the copied statement.

**Comment by jakob** [comment]
Good catch!

I fixed this:
https://eggerapps-downloads.s3.amazonaws.com/postico-1230.zip

**Comment by qwesda** [comment]
works as expected and doesn't kill sublime text anymore (with syntax highlighting enabled)! Tested with 5k rows and 1.2MB total statement length. Anything bigger should probably not have been a copy statement operation anyway.

I would add two additional line breaks: one before and one after `VALUES`

**Comment by jakob** [comment]
I've added the two additional newlines you suggested. Good idea.
https://eggerapps-downloads.s3.amazonaws.com/postico-1240.zip

**Comment by qwesda** [comment]
works great ...
it's also nice to see the indices even they are not yet editable.
