### ISSUE TITLE
edge case for determining separate sql queries

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#109]
I stumbled over an edge case for determining where a query starts and where it ends:

```
CREATE OR REPLACE RULE "maintein_active_tables_on_delete" AS 
ON DELETE TO "frontends"."frontend_to_release_format"
DO ALSO (
    DELETE FROM "frontends"."frontend_to_release_format_active"
    WHERE (gdid_frontend, gdid_release_format) = (old.gdid_frontend, old.gdid_release_format);
    DELETE FROM "frontends"."frontend_to_release_format_inactive"
    WHERE (gdid_frontend, gdid_release_format) = (old.gdid_frontend, old.gdid_release_format);
);
```

**Comment by jakob** [comment]
Thanks for letting me know about this. I wasn't aware that PostgreSQL statements can contain semicolons; I thought I would be spared this horror from MySQL....

But it seems the fix should be straightforward. I checked the psql source to see what they do, and they just ignore semicolons inside parentheses. So I just need to count parenthesis.

**Comment by qwesda** [comment]
I was pretty surprised by this too. 

Nice to hear that the fix is not too complicated - I thought it might involve a lot of unpleasant code

**Comment by jakob** [comment]
I've implemented parenthesis counting in build 1253
https://eggerapps-downloads.s3.amazonaws.com/postico-1253.zip

The sample query you posted works is recognized correctly now

**Comment by qwesda** [comment]
works also on my end.
