### ISSUE TITLE
Add ability to sort tables by click on column

### ISSUE THREAD

**Issue by 1st** [jakob/Postico#111]
When I switch to view all tables as a list - I see few columns like `Name`, `Row count`, `Size`, etc.

When I press on column name - nothing happens. but I need to sort tables by column value, for example see all the table with most records in it.

Please add this type of sorting and it will be super good improvement! Thanks.
- Anton

**Comment by cboothe** [comment]
@jakob Would be great to sort on Size or Index Size columns for the All Tables view.

**Comment by jakob** [comment]
I'm closing this issue since we decided to remove this view in Postico 2 (see issue #143).
