### ISSUE TITLE
Add new database via Postico GUI interface

### ISSUE THREAD

**Issue by 1st** [jakob/Postico#112]
To create new database I need to run all commands in terminal... I like to press button `+` and fill name of the database and select (or add new) user to access it.

Is it possible to add this functionality in near future? How hard is it? Do you need to have access to a 1root` privileges to do this operation, or you can do it without any additional privileges?

**Comment by vincent-dm** [comment]
I'm having the same issue. This is such a basic operation and I've been looking like crazy until I found this thread which confirms that it actually isn't there!

**Comment by jakob** [comment]
Hi! I've added a "CREATE DATABASE" button to the grid view with the databases. Could you try the following prerelease build and let me know if that works for you?
https://eggerapps-downloads.s3.amazonaws.com/postico-1301.zip

**Comment by 1st** [comment]
Hi @jakob. I have opened the app. Imagine that I don't have any connections and any database yet. How to create first database without use of terminal app? I think that you can add button on the main screen too. Thanks.

**Comment by 1st** [comment]
@jakob Any updates?

**Comment by jakob** [comment]
@1st I don't think it makes sense to add a "create database" button to the favorites window. Which server should I add the database to? This only makes sense *after* connecting to a server.

I assume that you are looking for a way to create a database on your local machine. In that case, how to create a database depends on your specific PostgrSQL install. If you use Postgres.app, you won't need to create a db; Postgres.app creates it for you. If you need more dbs, you can create them after connecting.

Postico is a database client; its not an all-in-one solution like Access or Filemaker.

**Comment by vincent-dm** [comment]
I tried it and it works splendidly. Thanks Jakob!

**Comment by jakob** [comment]
This issue is resolved in Postico 1.0.4
Download here: https://eggerapps.at/postico/

**Comment by danmandle** [comment]
I had to find this issue to figure out how to add a database. It's also not possible to get back to that screen without disconnecting and reconnecting after selecting a database. Could you please add this to the context menu? 
![screen shot 2017-05-31 at 1 43 51 pm](https://cloud.githubusercontent.com/assets/1851630/26650645/4bb9bdfc-4607-11e7-8274-eacf38378a9a.png)

**Comment by jakob** [comment]
You can go back to the server view by clicking the server icon in the path bar, or by using the "Go Up" command (shortcut cmd-option-up arrow).

**Comment by swedge218** [comment]
Create database works for me too. Thanks Jakob.

**Comment by vickylance** [comment]
I dont find that option anymore anywhere
