### ISSUE TITLE
How to delete unexpectedly added connection?

### ISSUE THREAD

**Issue by 1st** [jakob/Postico#114]
I have pressed `New Favorite` and don't know how to delete this connection. Please help me to find the way. Maybe need to add button "Delete" for a connection.

<img width="645" alt="screen shot 2015-11-03 at 18 02 25" src="https://cloud.githubusercontent.com/assets/630224/10913085/17b0b47e-8255-11e5-8177-eb810719e7dc.png">

<img width="650" alt="screen shot 2015-11-03 at 17 59 56" src="https://cloud.githubusercontent.com/assets/630224/10913054/f2564892-8254-11e5-9d10-1c0b1ccab36f.png">

And think that connection without filled data should be ignored and not created. But I created an empty connection - I mean without entering any data in the fields.

BTW, is it misspelling in word `Favorite`? Do you mean `Favourite`?

**Comment by motns** [comment]
You can click `Edit` on an entry in the favorites list, then click the `Options` drop-down, and select `Delete` from there. But yes I agree, there probably should be a more discoverable UI element, like a button.

As for the spelling, actually both versions are correct: `Favorite` is the American and `Favourite` is the British version.

**Comment by jakob** [comment]
You can also right-click on favorites to delete.

**Comment by 1st** [comment]
@jakob At least please don't add the empty connection. But I feel that the button `Delete` is better than context menu. Thanks.
