### ISSUE TITLE
Option to set default schema in login information

### ISSUE THREAD

**Issue by eliduke** [jakob/Postico#117]
With multi tenancy our default schema is 'public'. It would be nice if we could set that default schema to something else. This way you could have different 'Favorite' connection preferences for different schemas.

![schema_wireframe](https://cloud.githubusercontent.com/assets/1372520/11011784/bbb5718e-84a0-11e5-9613-43d0c10ca1ff.png)

**Comment by wesbaker** [comment]
Any chance this is in the works?

**Comment by jakob** [comment]
I'm planning an overhaul of the favorites management window; adding support for additional parameters (like search path, time zone, etc) will be part of that.

However, this is a part of a bigger effort, so it'll probably still take some time (months) before there's anything we can release.

**Comment by wesbaker** [comment]
Thanks for the response @jakob! No worries about it taking time, just wanted to make sure it wasn't dead.

**Comment by jakob** [comment]
We've now added a way to change the search_path in Postico 2, which kind-of does what you are suggesting. It doesn't change the special handling of the "public" schema, but it does help when you want to configure the search path for executing queries.

See #702 for details!
