### ISSUE TITLE
Autocomplete / filter in tables view on key presses

### ISSUE THREAD

**Issue by madis** [jakob/Postico#119]
When looking at the list of tables, it would be very nice if

1. user presses key, the selection move to the table starting with that name (when multiple keys are pressed in sequence, the table name match could be made more precise)
2. [cmd]+[F] find dialog that when typed into automatically filters shown tables down

Having to visually scan through large number of tables is takes time and is bad user experience.

**Comment by jakob** [comment]
I added these features in 1.0.1
https://eggerapps.at/postico/changelist.html

**Comment by qimingweng** [comment]
This is a godsend.

**Comment by madis** [comment]
:joy:

**Comment by gormster** [comment]
LOVE. although… it would be nice if "just start typing" worked the same way as the Search box, instead of searching by first characters only. IMHO.

**Comment by jakob** [comment]
Well, the "just start typing" feature is a pretty standard OS X feature for list views, so I don't want to change hof it works. It's useful for jumping to a specific table when you don't want to filter them.

**Comment by gormster** [comment]
Fair call. It works differently in Launchpad, but I don't know how many power users actually use Launchpad...
