### ISSUE TITLE
Export CSV to clipboard or be able to include column names when copying

### ISSUE THREAD

**Issue by eoglethorpe** [jakob/Postico#125]
I do a lot of Excel work where I pull from SQL. The export feature is great for creating CSVs but if I'm simply going to be exporting to Excel right away, this is an additional step. Other alternative is just to copy and paste resultset, but this doesn't capture column names.

Would be great to have ability to copy the full output (including column names) to clipboard either through the export feature or when copying the resultset.

Thanks again, really digging Postico

**Comment by jakob** [comment]
I added a "Copy with Header" command in 1.0.1
https://eggerapps.at/postico/changelist.html
