### ISSUE TITLE
Option to disable magic mouse gestures forward/back.

### ISSUE THREAD

**Issue by sblmasta** [jakob/Postico#129]
I think is a good idea to add option to disable it in preferences of application, because sometimes gestures can be a problematic for smart view database rows/schema.
I will be very grateful to you for adding such an option in preferences.

Best regards!
Łukasz :)

**Comment by qwesda** [comment]
+1

I'm using a trackpad and for me they have a 50/50 chance of being invoked by accident. The few times I had used a magic mouse the ration was more like 80/20. So an option to disable it might be very useful. For the trackpad there might also be an option to use a tree finger swipe for that.

**Comment by jakob** [comment]
I added a preference to disable gestures in 1.0.1
https://eggerapps.at/postico/changelist.html
