### ISSUE TITLE
tiiiiny request: more intrusive update notification

### ISSUE THREAD

**Issue by wellsoliver** [jakob/Postico#135]
Went for a whole two weeks before I noticed the little tiny blurb in the bottom left of the start-up screen! Two weeks before I was able to enjoy the awesome new ability to set font sizes (which, by the way, thanks!)

Can you make this more prominent? Maybe some alert style prompting you to upgrade, etc...

**Comment by jakob** [comment]
Hmm. You actually discovered the update the day it was released (I released version 1.0.1 on Nov 23).

I'll think about this a bit. For now the best thing to stay up to date is to subscribe to interesting issues on Github.

(BTW: I just released 1.0.2 [which fixes two regressions in 1.0.1](https://eggerapps.at/postico/docs/?file=changelist.html))

**Comment by jakob** [comment]
I've now made update notifications more "intrusive" (Postico now uses Notification Center to show notifications)

You could try the latest build, but of course you won't see anything until the next version is released:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1324.zip

**Comment by jakob** [comment]
Postico 1.0.4 is now out! If you want to see what the new update notifications look like, download build 1324 (above) and start it.
