### ISSUE TITLE
Restore window size & position

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#14]
Postico should remember window size & position, and restore it when connecting the next time.

**Comment by motns** [comment]
:+1:

**Comment by jakob** [comment]
I partially addressed this in 0.25. Windows are now restored when the app restarts. However, when closing all windows, and reopening them, the size is not remembered yet.

**Comment by ecsos** [comment]
thank you

**Comment by adi-** [comment]
+1

**Comment by jakob** [comment]
Postico now autosaves the window size

You can download the latest build here:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1334.zip

**Comment by jakob** [comment]
This issue is resolved in Postico 1.0.4
Download here: https://eggerapps.at/postico/
