### ISSUE TITLE
Add support for PostGIS data types

### ISSUE THREAD

**Issue by lastquestion** [jakob/Postico#141]
It would be very nice to add support for PostGIS types. Is that something that is on the roadmap yet? The company I work for is using postico for editing various tables with PostGIS columns and having to drop to `psql` is not always possible for everyone.

**Comment by jakob** [comment]
What exactly do you mean with "support for PostGIS types"? Postico displays geometry and geography columns in EWKT format (see issues #92 and #140). What else would you like to see in Postico?

**Comment by lastquestion** [comment]
Ah, I should have done a better search of the existing closed issues. We'll try out the build you mentioned in #140. I think mostly if we can visualize and edit as text that will be sufficient.

**Comment by jakob** [comment]
I usually leave issues open until the fix is in a released version, but in that case the person reporting the issue closed it.

Please let me know if this build solves your issue. I also welcome any and all suggestions that make Postico more useful for PostGIS users!

**Comment by jakob** [comment]
Just released version 1.0.3
Download here: https://eggerapps.at/postico/
