### ISSUE TITLE
>, >=, <, <= operators for text fields as well

### ISSUE THREAD

**Issue by jakajancar** [jakob/Postico#147]
We have text columns representing months with `yyyy-mm`.
Sometimes we also want somebody to manually process different parts of the alphabet :)

**Comment by jakajancar** [comment]
@jakob Can this get some love? :)

**Comment by jakob** [comment]
Yes. I'm working on a new build that fixes the JSON sorting issue, let me see if I can add these operators as well.

**Comment by jakajancar** [comment]
Thanks!

**Comment by jakob** [comment]
New operators are in version 1.0.3
https://eggerapps.at/postico/
