### ISSUE TITLE
[Save Query...] button broken

### ISSUE THREAD

**Issue by corgus** [jakob/Postico#15]
Clicking 'Save Query...' button leads to the app attempting to create a folder with the specified query name, which prohibits query saving: 

![screen shot 2015-06-22 at 3 56 11 pm](https://cloud.githubusercontent.com/assets/3866184/8295234/87bd6b58-18f7-11e5-9a27-520a5fda4cf2.png)

**Comment by jakob** [comment]
This is odd. I use the [writeToURL:atomically:encoding:error:](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSString_Class/index.html#//apple_ref/occ/instm/NSString/writeToURL:atomically:encoding:error:) API to atomically save the file. This method first writes the file to a temporary location, and then moves the file to its final destination. In this case it sounds like the temporary folder could not be created.

OS X always chooses a temporary location on the same volume as the target location. Could it be that there's a permission error with the volume you are trying to save the file to? Are you trying to save to a network drive?

I'm not sure what I can do on my end. I don't want to disable atomic saving, as that can cause file corruption in case of an error.

Could you check if anything is logged in Console.app when the error occurs?

Also: what version of OS X are you on?

**Comment by corgus** [comment]
Strange, suddenly it works! Can't seem to duplicate the issue either...
My OS is Mavericks, and the destination directory was newly created outside the app in my home dir.
In any case, this issue's probably good to close.
