### ISSUE TITLE
Remember contents of query editor across restarts

### ISSUE THREAD

**Issue by dimfeld** [jakob/Postico#152]
Postico's query history does this partway, but I often have a bunch of related queries in a single editor window and have become accustomed to not saving them (a bad habit, I know) when using other editors which restore the contents on restart. I see the windows come back in the right place thanks to the work done so far on #14 but persistence of the editor contents would be great as well.

**Comment by jakob** [comment]
Postico now restores the contents of the query editor

Prerelease build:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1490.zip

**Comment by jakob** [comment]
Postico 1.0.9 (which includes this feature) can be downloaded from my website, and it should hit the app store soon.
