### ISSUE TITLE
window position changes when resized.

### ISSUE THREAD

**Issue by chazlarson** [jakob/Postico#154]
1. Position the Postico window in the upper-left of the screen.  
<img width="838" alt="01" src="https://cloud.githubusercontent.com/assets/3865541/12095013/a4c1411a-b2d1-11e5-9af6-178b63ada762.png">

2. Click on the lower-right corner to drag-resize.

3. Window will snap into the center of the screen as soon as you begin the resizing drag.
<img width="838" alt="03" src="https://cloud.githubusercontent.com/assets/3865541/12095012/a4b1d748-b2d1-11e5-8f15-abf6a744a41c.png">

**Comment by jakob** [comment]
This doesn't happen on my machine, and I can't think of anything that might be causing this behavior in my code.

Does this happen only in Postico or have you seen this in other apps? Does it happen only with this window or other windows (eg. favorites) as well?

Do you have any window managers or similar utilities installed?

Have you tried rebooting your Mac?

**Comment by chazlarson** [comment]
Haven’t seen it in other apps.  Happens with the Favorites window as well.

No window managers installed.

I’ll give the reboot a try, as well as logging into a different user account.

chazl

—
Chaz Larson    |   (c)   612-701-3658

Hey, I’m transitioning over to using chaz@chazlarson.com as my primary address.  If you’d be so kind as to change your address book, that’d be awesome sauce.


On January 4, 2016 at 11:38:11 AM, Jakob Egger (notifications@github.com) wrote:

This doesn't happen on my machine, and I can't think of anything that might be causing this behavior in my code.

Does this happen only in Postico or have you seen this in other apps? Does it happen only with this window or other windows (eg. favorites) as well?

Do you have any window managers or similar utilities installed?

Have you tried rebooting your Mac?

**Comment by jakob** [comment]
Since I haven't gotten any further reports of this issue, I'm hoping it's a one-time quirk, and I'm closing this issue. If you (or anyone else) run into this problem again, please reopen this issue.
