### ISSUE TITLE
Bug when connecting in SSL mode

### ISSUE THREAD

**Issue by liudangyi** [jakob/Postico#158]
Postico seems to interpose the the SSL certificate chain. I use the same certificates for both nginx and postgresql. But the certificate chain is different, and Postico's is not trusted.

![screen shot 2016-01-14 at 1 32 01 am](https://cloud.githubusercontent.com/assets/1825485/12302295/781b3e1e-ba5f-11e5-84a7-7aa8df7d8554.png)
![screen shot 2016-01-14 at 1 32 17 am](https://cloud.githubusercontent.com/assets/1825485/12302296/79efffea-ba5f-11e5-8862-976916325911.png)

**Comment by liudangyi** [comment]
Postico doesn't ask Keychain for System Root CAs. I'm afraid all certificates will have trouble being verified.

**Comment by jakob** [comment]
Postico uses the OS X Security API to verify certificates. "WoSign" is not a System Root CA. Therefore you need to include the StartCom cert for WoSign with your certificate. It could be that Safari has a copy of that certificate cached somewhere, and therefore doesn't need it, but Postico does.

Try appending the StartCom cert to your server cert. See section [17.9. Secure TCP/IP Connections with SSL](http://www.postgresql.org/docs/current/static/ssl-tcp.html) in the PostgreSQL manual:
> In some cases, the server certificate might be signed by an "intermediate" certificate authority, rather than one that is directly trusted by clients. To use such a certificate, append the certificate of the signing authority to the server.crt file, then its parent authority's certificate, and so on up to a certificate authority, "root" or "intermediate", that is trusted by clients, i.e. signed by a certificate in the clients' root.crt files.

Usually you should get a "bundle.crt" file or similar from your issuer, containing all the additional certs you need. Try appending that file to "server.crt", then restart your PostgreSQL server, and it should work.

**Comment by liudangyi** [comment]
Actually WoSign is not a root CA, it's an intermediate certificate authority. But Postico recognized it as the root CA. 

I've also tried Psequel with SSL enabled. It connected without any errors. 

The server is available to the Internet with host name "aws.leedy.me". You can try with different tools (with SSL forced).

**Comment by jakob** [comment]
This is not a bug in Postico. You need to configure your server to send all the certificates, not just the server certificate. Please read my comment again, and then read the documentation I linked too.

(Psequel probably just doesn't verify the cert.)

**Comment by liudangyi** [comment]
I have two servers. Server A's certificate is self-signed. Server B's is signed correctly.

### Server A with PSequel
<img width="621" alt="screen shot 2016-01-15 at 3 29 06 pm" src="https://cloud.githubusercontent.com/assets/1825485/12347897/64ada71a-bb9d-11e5-8236-f6d1de95fd55.png">

### Server B with PSequel
<img width="624" alt="screen shot 2016-01-15 at 3 29 35 pm" src="https://cloud.githubusercontent.com/assets/1825485/12347906/795464f6-bb9d-11e5-8966-ae5b4ccc6f45.png">

### Server A with Postico
<img width="762" alt="screen shot 2016-01-15 at 3 31 03 pm" src="https://cloud.githubusercontent.com/assets/1825485/12347932/be6c8b36-bb9d-11e5-9e30-892e94f3b103.png">

### Server B with Postico
![screen shot 2016-01-15 at 3 30 48 pm](https://cloud.githubusercontent.com/assets/1825485/12347935/c21a669a-bb9d-11e5-9abb-dcb840d0fb52.png)

### Using `psql`
```
$ psql -h aws.leedy.me -a "sslmode=verify-full"
Password:
$ psql -h do.leedy.me -a "sslmode=verify-full"
psql: SSL error: certificate verify failed
```

**Comment by jakob** [comment]
psql checks the certificate against root certificates stored in `~/.postgresql/root.crt`. Postico does not. It checks them against System Root certificates stored in the Keychain.

You have two ways of fixing this problem:

- Add the root cert from `~/.postgresql/root.crt` to your keychain
- Alternatively configure the server to include the WoSign certificate signed by StartCom

**Comment by liudangyi** [comment]
The problem still exists after I import `~/.postgresql/root.crt`. In fact, `root.crt` is StartCom CA which is already included in System Root certificates.

**Comment by jakob** [comment]
OK, sorry, you are right. Let me check what is happening.

**Comment by jakob** [comment]
I've now discovered the source of the bug and fixed it. The bug caused Postico to ignore additional certificates sent by the server, just like you said. This means that certificates from intermediate CAs like WoSign were rejected.

Thank you for telling me about this bug. I am really sorry for not believing you at first.

Here is a build of Postico that should correctly check the certificate:
https://eggerapps-downloads.s3.amazonaws.com/postico-1298.zip

**Comment by liudangyi** [comment]
It works! Thank you.
