### ISSUE TITLE
Incorrect field name in materialized view

### ISSUE THREAD

**Issue by kpashka** [jakob/Postico#159]
Created simple materialized view:

```sql
create materialized view users_view as
select
    u.name as user_name,
    to_char(u.created_at, 'YYYY-MM-DD HH24:MI:SS') as created_at
from users as u;
```

For second column, Postico renders `to_char` as field name, but it should render `created_at`.

**Comment by jakob** [comment]
It works for me on PostgreSQL 9.4. This could be an issue on the server side. What server are you connecting to?

Postico uses the following query to get the column names:
```SQL
SELECT 
attnum, attname, atttypid, attnotnull, format_type(atttypid,atttypmod),
pg_get_expr(adbin, attrelid, true) AS adsrc,
col_description(attrelid, attnum), typcategory
FROM pg_attribute
LEFT JOIN pg_type ON atttypid=pg_type.oid
LEFT JOIN pg_attrdef ON adrelid=attrelid AND adnum=attnum
WHERE attrelid = 'yourtablename'::regclass AND NOT attisdropped
ORDER BY attnum
```

Can you check what that returns for your table?

**Comment by kpashka** [comment]
@jakob Strange, can't reproduce it again, perhaps it was a typo. Will re-open if encounter this again
