### ISSUE TITLE
add find-and-replace in SQL Query view

### ISSUE THREAD

**Issue by jmcbroom** [jakob/Postico#165]
would be nice to have find-and-replace for the text in the query editor; both for the whole editor and a selection. thanks. Postico is great so far.

**Comment by teneruffian** [comment]
I was just thinking the same thing.  So that's a "please" from me, also.
And a thank you for the app.

**Comment by nksocast** [comment]
+1, please add this feature.

**Comment by swrobel** [comment]
Duplicate of #53

**Comment by jakob** [comment]
I've now added find & replace in the query editor

Download latest nightly build here:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1402.zip
