### ISSUE TITLE
Count of Selected Rows

### ISSUE THREAD

**Issue by bleonard33** [jakob/Postico#170]
It would be awesome to have a count at the bottom of the page (such as by the standard row count) when you highlight rows of how many you have selected for quick at-a-glance information about your selection.

**Comment by qwesda** [comment]
+1

**Comment by jakob** [comment]
I've added this feature. It will be in the next release. You can try out this prerelease:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1309.zip

**Comment by jakob** [comment]
This feature is now included in Postico 1.0.4
Download here: https://eggerapps.at/postico/
