### ISSUE TITLE
ordering and search for database list

### ISSUE THREAD

**Issue by stefanfoulis** [jakob/Postico#172]
It would be great to have ordering and search of the list of databases (possibly with an optional list view instead of the "icon" view).

My usecase is that we have postgres instances with thousands of databases, all with cryptic random names. It's pretty hard to find the right database right now.

**Comment by jakob** [comment]
I've added a search field recently -- it's not yet in the released version, but you can download this build to try it out: https://eggerapps-downloads.s3.amazonaws.com/postico-1304.zip

I assume you are connecting to a Heroku db? In that case I recommend unchecking the "Show All Databases" option for the favorite, to connect directly to your db, then you don't need to bother with that list of databases.

**Comment by stefanfoulis** [comment]
@jakob awesome, the search works like a charm in that pre-release version. thanks.

**Comment by jakob** [comment]
This feature is now included in Postico 1.0.4
Download here: https://eggerapps.at/postico/

**Comment by stefanfoulis** [comment]
Awesome, thanks Jakob. I already switched back to the 1.0.4 release.
