### ISSUE TITLE
Ctrl+H in sql editor to open Dash

### ISSUE THREAD

**Issue by trapias** [jakob/Postico#176]
It would be nice to have the possibility to hit "ctrl+h" in editor, maybe after having selected a term, and to let this keystroke launch Dash (https://kapeli.com/dash), just like Sublime does for example, to look at documentation.

Note: I say Dash because I use that, but have nothing to do with them - which program to launch might be a configuration parameter, I guess.

More: per default, e.g. if no word is selected in editor, since "ctrl+h" is common for "help" might open Postico own help/help page. Optimum, @jakob , for me would be to see Postico docs into Dash :smile:

**Comment by jakob** [comment]
You can use services to look up a term in Dash: Right Click on Word -> Services -> Look Up In Dash (Make sure you have "Look Up In Dash" enabled in System Preferences -> Keyboard -> Shortcuts -> Services -> Searching)

But I agree, maybe a shortcut would be useful. I'll contact the developer and see what I can do.

**Comment by trapias** [comment]
Sorry to bother @jakob, aren't **you** the developer? thought so :smile: 

Thanks!
al.

**Comment by jakob** [comment]
@trapias yes, I'm the developer of Postico :)

I meant, I'll contact the developer of Dash to see how I can best do the integration.

**Comment by trapias** [comment]
ops :flushed: not my best day, today.

Also consider putting Postico help into Dash, why not? You just can ask the developer (of Postico) to write some documentation in spare time :grimacing:

**Comment by jakob** [comment]
OK, Bogdan, the developer of Dash pointed me to [this page](https://kapeli.com/dash_plugins) that explains how to do integrations -- looks like it's pretty straightforward. I'll see what I can do.

I'm not sure about putting Postico docs into Dash -- does that make sense? I thought that Dash was only useful for keyword based API docs... do you use it for other stuff too?

**Comment by trapias** [comment]
Great! Not a major functionality, but I'd love to have it.

Anyway, I have like 30 dockets installed, I find Dash to be useful on tons of cases. You're right maybe that's not where one would search for Postico docs...

**Comment by jakob** [comment]
OK, I now added the shortcut Ctrl-H to lookup the current word in Dash. Obviously only useful if you have the psql docset installed.

You can try it here:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1308.zip

(This does override the "DeleteBackward" emacs key binding that Ctrl-H usually has in Cocoa text views. I hope that nobody uses that key binding -- but why should you, when you have a backspace key?)

**Comment by trapias** [comment]
@jakob GREAT! Working perfectly, thank you so much!!! :smile:

**Comment by qwesda** [comment]
Nice, I literally tried `Ctrl + H` yesterday to look something up in dash.

I doesn't work for multi word commands though, like `CREATE TABLE`.

**Comment by jakob** [comment]
You can select the words first, then press Ctrl-H to look it up... but I agree, it'd be nicer if Postico was smarter about the syntax. hmmm...

**Comment by qwesda** [comment]
Ah, I meant when I have `CREATE TABLE` selected it doesn't work, as in nothing happens.
Also the postgres docset in dash would expect it to be spelled `CREATETABLE` (without the space).

**Comment by jakob** [comment]
@qwesda oh, OK, I misunderstood. Thanks for letting me know about this. I fixed it, it should work now:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1310.zip

**Comment by qwesda** [comment]
works for me. 

Sadly the docset itself it pretty bad and is only useful for keywords but not for functions.

**Comment by trapias** [comment]
@jakob looks like it works pretty well, I believe you could close this issue and just include the feature in next release.

Thank you :smile:

**Comment by jakob** [comment]
@trapias OK! I'll close the issue after the release (I don't want to close issues before I released the change, because then I often end up with duplicate issues -- most people don't look at closed issues)

**Comment by trapias** [comment]
@jakob what about extending the "ctrl+h" feature to the "query status" textarea? In case you get errors, for example, it might help to quickly get help.

**Comment by jakob** [comment]
I've decided not to add this feature to the query status area. I think most error message wouldn't lead to useful results in Dash. Also, you can already use the "Services" menu to look up words in Dash (just right click on a word in the result area)

**Comment by trapias** [comment]
I agree, thanks for the update.

**Comment by tadao** [comment]
Hi there,
I unchecked "Look Up in Dash" in "Services".
But whenever I hit `Ctrl + H` in Postico, Postico opens Dash app.
Why?
