### ISSUE TITLE
Cannot go two FK away from starting table

### ISSUE THREAD

**Issue by cypreess** [jakob/Postico#177]
I got a database model where I got

Table1 -> fk -> Table2 -> fk -> Table 3

I filtered Table1. I selected one row and I click on table2.fk , pop-up shows a specific row, then I click "Open table2" button. It takes me to the view of table 2 with specific row selected. Now I click on table3.fk field, I see again popup, I click "Open table3" and nothing happens. Pop-up is still there, it do not open table3 view.

**Comment by jakob** [comment]
Thanks! Fixed:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1312.zip

**Comment by cypreess** [comment]
Thx - tested - it's working
