### ISSUE TITLE
Support for column based SELECT privileges

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#179]
I'm currently working on a database where access is restricted on the table, column and row level. Trying to view a table where only a subset of the columns are accessible to the current user results in a 'permission denied' error message. 

It should be possible for postico to figure out which columns can be selected for the current user and only select these columns from the backend. The following function returns `TRUE` if access is possible:

```SELECT has_column_privilege('"schema name"."table name"', 'column name', 'SELECT');```

Non-accessible columns should be displayed as if they are disabled.

**Comment by jakob** [comment]
Good idea. Here's a first implementation of this:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1320.zip

Comments?

**Comment by qwesda** [comment]
Works basically.

The disabling of the column is spotty thought. It only resets if you `cmd + R` while having another table open.

Maybe the different permission levels could be better represented by small icon on the right side of the column header:

- SELECT and UPDATE => no icon
- SELECT and NOT UPDATE => crossed pencil icon
- NOT SELECT and UPDATE => crossed eye icon & pencil icon
- NOT SELECT and NOT UPDATE => crossed eye icon & crossed pencil icon (maybe also grey out the whole column)

**Comment by jakob** [comment]
OK, I fixed the column header highlighting issue:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1321.zip

The icons are a good idea, but I have to think about that a bit (eg. how would I highlight missing INSERT privilege? should I?)

**Comment by jakob** [comment]
And here's another build that fixes filters for tables with forbidden columns...

https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1322.zip

**Comment by qwesda** [comment]
`cmd + R` works now. And it works good enough for me to work with. So thanks.

Do you mean a missing INSERT privilege for the whole table or specific columns? For the whole table disabling the `+ Row` button would be appropriate – and if only some columns can be inserted to only these should have enabled input fields for the new row.

**Comment by jakob** [comment]
I've just released 1.0.4
https://eggerapps.at/postico/
