### ISSUE TITLE
First time UX tweak for SQL terminal

### ISSUE THREAD

**Issue by ottob** [jakob/Postico#182]
The first time you start the application and go to the SQL terminal it looks like this:

![sql_ux](https://cloud.githubusercontent.com/assets/67104/12988269/32bfc206-d100-11e5-998e-ef2648a9a56c.png)

I have seen a couple of times that new users try to insert text where I have written in red. If the input field was larger, perhaps covering 50% of the available space I think this would be a bit less confusing.

**Comment by jakob** [comment]
Sorry for getting back to you so late, but could you check which version of Postico you are using? I thought I had fixed this problem some time ago...

**Comment by ottob** [comment]
That might well be the case, I will keep my eyes open the next time I install it to someone new.
