### ISSUE TITLE
Favorites not showing up recent build

### ISSUE THREAD

**Issue by ear** [jakob/Postico#185]
I just tried your latest build posted in #38 [here](https://github.com/jakob/Postico/issues/38#issuecomment-184687334) and this happens:

![postico-favorites-build-1292-1334](https://cloud.githubusercontent.com/assets/2104122/13078128/7ae2f902-d4bd-11e5-8512-574657292901.png)

On the left the older build (1292) on the right the newest one (1334).

Is this a problem with my setup or did you change something as for how the favorites are saved/restored recently?

The two that show up on the new build are the local, and they have `@localhostname` appended to them in the new build only. The rest of the favorites don't show at all. Strangely enough the third one is also local but does not show. The remaining three are remote.

**Comment by jakob** [comment]
Hm. I've made no changes to the favorites code between the two builds. Maybe there's a problem with storing the favorites?

Postico doesn't like it when two copies of the app are open simultaneously, it could be that this corrupts the favorites database.

Could you try quitting all copies of Postico, then reopen them one by one? Maybe try to export favorites before quitting, so you don't lose them?

**Comment by ear** [comment]
I tried. No change. Every version opens exactly what it opens anyway. It does not seem to be a concurrency problem.

**Comment by jakob** [comment]
Could you try running the following command in Terminal (while Postico is open) to see if both builds are reading the same favorite database:

`lsof | grep ConnectionFavorites.db`

**Comment by ear** [comment]
Oh wow they aren't! Crazy. `~/Library/Application Support/Postico/ConnectionFavorites.*` versus `~/Library/Containers/at.eggerapps.Postico/Data/Library/Application Support/Postico/ConnectionFavorites.*`.

Well I guess that explains it. Maybe it has something to do with sandboxing.

**Comment by jakob** [comment]
Yes, this probably means that sandboxing is disabled, which might be due to a problem with code signing.

What OS are you on?

Could you try running the following three commands to check the code signature and what gatekeeper thinks about it:

```bash
codesign -vvv ~/Downloads/Postico\ 1334.app
codesign -d -vv --entitlements :- ~/Downloads/Postico\ 1334.app
spctl --assess -vv ~/Downloads/Postico\ 1334.app
```

**Comment by ear** [comment]
I tried deleting the app and re-downloading it and now it shows the same favorites. I think I might have messed it up myself while playing with codesign in the `/Application` directory for my own purposes.

Thank you for the support btw, you rock :+1:
