### ISSUE TITLE
Improve the color menu

### ISSUE THREAD

**Issue by ream88** [jakob/Postico#187]
![screen shot 2016-02-22 at 14 19 20](https://cloud.githubusercontent.com/assets/14321/13219331/a3ca796a-d96f-11e5-88c2-3a88ed561a68.png)
Could this implemented like this?
![screen shot 2016-02-22 at 14 19 54](https://cloud.githubusercontent.com/assets/14321/13219354/c689f0ac-d96f-11e5-8585-f211b6636e78.png)

Maybe I'm finicky, but at least it would be a lot faster to use 😉

**Comment by jakob** [comment]
Yes it absolutely should be implemented this way -- but custom menu items are finicky, and it would probably cost me half a day, so I'll defer this to a later time.

**Comment by jakob** [comment]
Took a bit longer than half a day, but Postico 1.5 finally has a better color picker. Thanks to @chrispysoft I can close this issue now!

**Comment by ream88** [comment]
And support for dark mode!! 🙃 @jakob you rock!

**Comment by jakob** [comment]
Thanks :)

But credit where credit is due: @chrispysoft did most of the work on Dark Mode!

**Comment by ream88** [comment]
@chrispysoft you rock as well! 😊
