### ISSUE TITLE
Dismiss "Filter tables" on Enter

### ISSUE THREAD

**Issue by ulope** [jakob/Postico#189]
Currently pressing `Enter` while in "Filter Tables" mode does nothing.

I would suggest that it should simply dismiss the filter mode (and close the tables sidebar if it wasn't open before entering filter mode)

**Comment by jakob** [comment]
Thanks for your suggestion, but I don't think this is such a great idea. I often press enter instinctively after typing a search term, and it would be a bit annoying if that would dismiss the filter mode.

(You can dismiss the filter mode by pressing escape, and you can close the sidebar again by pressing Cmd-0)

**Comment by ulope** [comment]
Heh, that instinctive enter-after-searching is exactly why I suggested it :)
As it is now pressing enter produces that "key does nothing" sound which I find quire distracting.

**Comment by jakob** [comment]
Neither return or Enter in the search field (in the sidebar) make any sound on my Mac -- what OS are you on? Are you possibly pressing Cmd-Return?

**Comment by ulope** [comment]
Ah sorry I wasn't clear. The sound only happens when first selecting a table with cursor up/down and then pressing enter

**Comment by jakob** [comment]
Ok, I understand now. The most sensible thing here would probably be to put the focus on the table view after pressing enter.

Closing the sidebar if it was hidden before would involve adding a bunch of state that I'd like to avoid if possible.

Or, I could make return trigger "rename", like the Finder does.

Hm. Not sure about this.

**Comment by ulope** [comment]
> Ok, I understand now. The most sensible thing here would probably be to put the focus on the table view after pressing enter.

That would help a bit, for sure :)

> Closing the sidebar if it was hidden before would involve adding a bunch of state that I'd like to avoid if possible.

Sounds reasonable. Being a developer myself I can certainly appreciate the motivation to not add complexity that isn't absolutely needed.

> Or, I could make return trigger "rename", like the Finder does.

Renaming a table is a pretty rare (and possibly dangerous) thing IMO. I don't think it should be quite that easy to accidentally do it.

**Comment by jakob** [comment]
I've decided to leave it as is.
