### ISSUE TITLE
Add shortcut to switch between Content and Structure

### ISSUE THREAD

**Issue by ulope** [jakob/Postico#191]
It would be nice if there was a shortcut to switch between the Content and Structure views.

Perhaps `⌘1` and `⌘2` could be used for that.

**Comment by jakob** [comment]
There's `⌘⌥T` (Check the Navigate menu for more keyboard shortcuts)

I'd like to reserve `⌘1`,  `⌘2` for the sidebar.

**Comment by ulope** [comment]
No idea how I missed that. Sorry for the noise.

**Comment by trapias** [comment]
@jakob perhaps I'm missing something, but wasn't it also possible to click the table name while pressing Alt (Option) to go to structure mode?

**Comment by jakob** [comment]
Yes, I removed that shortcut; it wasn't documented and not intuitive. Postico now always opens the last used view. To open a specific view, you can use the context menu now.

**Comment by trapias** [comment]
@jakob ok, I can live without it ;-)
