### ISSUE TITLE
Provide table CREATE scripts

### ISSUE THREAD

**Issue by scrimshander** [jakob/Postico#192]
It would be really handy to be able to copy out or save table CREATE scripts from the structure view - as is possible with views. I do this all the time in pgAdmin for various admin/loading tasks & would rather use Postico!

**Comment by petersirka** [comment]
+1 :+1:

**Comment by thousandsofthem** [comment]
Super-useful. Postico missing stuff like this. Falling back to command line for simple operations like this is surely painful

**Comment by prgagarina167** [comment]
+1 this feature is really necessary!

**Comment by petersirka** [comment]
Is there any news?

**Comment by sebastian-meier** [comment]
+1

**Comment by wadewegner** [comment]
Yes please!

**Comment by swrobel** [comment]
I believe this duplicates https://github.com/jakob/Postico/issues/34

**Comment by martinjankoehler** [comment]
Hi folks, good news!

We've posted a new developer build for this feature in the issue thread: https://github.com/jakob/Postico/issues/34

Please post your feedback there, we'll close this dupe.

Best regards,
Martin
