### ISSUE TITLE
Inconsistent double quotes in array data

### ISSUE THREAD

**Issue by sul4bh** [jakob/Postico#193]
Data in array column has inconsistent double quotes.

![localhost-_fc3_ _fc3data_ _public_ _provider_makemap](https://cloud.githubusercontent.com/assets/109486/13676822/587b1d0e-e6b5-11e5-85c3-21dbb41de42b.png)

Data inserted as:
`ARRAY['MERCEDES BENZ', 'MERCEDES-BENZ']`
Column definition:
`character varying(100)[]`

**Comment by jakob** [comment]
That's just the way that the PostgreSQL server outputs arrays. Values with spaces or special characters are printed with double quotes, and values with letters only are printed without quotes. Postico doesn't have any special handling of array types yet, so it just prints the text that the server sends.

**Comment by sul4bh** [comment]
I see. Thanks for clarifying.
