### ISSUE TITLE
Can not connect

### ISSUE THREAD

**Issue by sleepnova** [jakob/Postico#195]
Version 1.0.5, updated from v1.0.3

Connect fail with following message:
FATAL:  password authentication failed for user "xxx"

**Comment by sleepnova** [comment]
Can I downgrade to an older version?

**Comment by jakob** [comment]
[Postico 1.0.3](https://eggerapps-downloads.s3.amazonaws.com/postico-1.0.3.zip)
[Postico 1.0.4](https://eggerapps-downloads.s3.amazonaws.com/postico-1.0.4.zip)
[Postico 1.0.5](https://eggerapps-downloads.s3.amazonaws.com/postico-1.0.5.zip)

**Comment by jakob** [comment]
I'm not aware of any changes since 1.0.3 that would cause this error. You can download a previous version from the links I posted above.

Please let me know if this bug is indeed limited to version 1.0.5; if it is, I'd like to fix it.

**Comment by jakob** [comment]
Closing this since I got no more feedback. Feel free to reopen if you still have issues!

**Comment by jotto** [comment]
I didn't try an older version, but I get `password authentication failed for user` (with 1.0.10) when connecting via SSH and a private key **and a User**
