### ISSUE TITLE
Copy insert doesn't include schema

### ISSUE THREAD

**Issue by jspeis** [jakob/Postico#197]
Copy insert in Postico 1.0.5 does not include the schema of the table when copying e.g.

![screen shot 2016-03-18 at 2 47 30 pm](https://cloud.githubusercontent.com/assets/87581/13888550/5f616b64-ed18-11e5-975d-2f9b8bde19f8.png)

e.g. if I have a table like my_schema.my_tables

the SQL just has: INSERT INTO "my_table" ... but should have: INSERT INTO "my_schema.my_table"

**Comment by qwesda** [comment]
+1

This would be very nice. The behaviour should be to include the fully qualified table name regardless of the current `search_path` setting.

**Comment by jakob** [comment]
Done. Will be in next version. Development build for testing:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1500.zip

**Comment by qwesda** [comment]
Have testes it and it works as expected, thanks!  The `Copy JSON` variant is  also very welcome.
