### ISSUE TITLE
Table contents not cleared in UI after Truncate

### ISSUE THREAD

**Issue by motns** [jakob/Postico#20]
After running a Truncate operation on a table from Postico, the (now deleted) contents of that table remain visible in the UI. Even after clicking on another table and back, the rows are still there. The only way to make them disappear is to close the window and re-connect.

**Comment by jakob** [comment]
You can press Cmd-R to refresh, but I agree, Portico should refresh automatically. Thanks for the suggestion.

**Comment by motns** [comment]
Thanks for the tip - I haven't spotted that there was an option to refresh!

I can certainly see the value in caching results, so that browsing is snappier in general; I suppose more than anything I'd just like it to be more obvious that the results I'm seeing are cached, and that I have to refresh to see changes.
On top of that, maybe having a setting in preferences to turn result caching on or off would make sense, but I'll defer to you on that.

**Comment by jakob** [comment]
Tables are now refreshed after truncating (in v0.26)

**Comment by motns** [comment]
Awesomeness - thanks! :+1:
