### ISSUE TITLE
force ssl, and verify connection information

### ISSUE THREAD

**Issue by doanerock** [jakob/Postico#201]
I would like to be able force SSL only connection.  I would also like to be able to verify if my connection is SSL or non SSL, and what the certificate information is if it is SSL enabled.

**Comment by jakob** [comment]
Postico always connects using SSL (unless the host is localhost). If connections via SSL are not possible, a warning is displayed.

In the next version (Postico 1.0.6) I'm adding a little button to the status bar at the top of the window that shows if you are using an encrypted connection or not. Clicking it tells you details like SSL cert etc.

The new version will be released soon, I just need to finish testing it. You can download the release candidate here: https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1.0.6.zip

Would love to hear your comments on this feature!

**Comment by doanerock** [comment]
I tried out the release candidate and I like how the certificate information is shown.  

I wold still like to be able to specify in the connection information, to only connect via SSL or non SSL.  I want that feature for two reasons.  I can specify no SSL to make sure the connection does not allow anything besides SSL.  I also want to specify only SSL because I don't want my connection information to be leaked by allowing a non secure connection.

You are basically allowing a downgrade attack, by allowing connection over non SSL.

**Comment by jakob** [comment]
I think you misunderstood. Postico requires SSL/TLS (or SSH). If the server claims to not support SSL, Postico shows a warning dialog, and asks you if you want to connect anyway. The default option is to cancel. (See screenshot)

I understand that being explicit would be better, but Postico is only vulnerable to an SSL stripping attack if you click "connect" in that alert message.

<img width="762" alt="screen shot 2016-04-10 at 19 47 21" src="https://cloud.githubusercontent.com/assets/198305/14411893/42446302-ff55-11e5-9430-e8c8fb81382e.png">
