### ISSUE TITLE
Syntax highlighting between `$$` pairs in functions

### ISSUE THREAD

**Issue by ehamberg** [jakob/Postico#206]
When writing functions in Postico, I have to comment out `$$` delimiters to get syntax highlighting for the function body. For example, in the code below, everything between the `$$` pairs will be coloured orange.

```sql
create function foo(bar integer)
returns text
$$
  select title
  from foo
  where foo.id = bar
$$
language sql immutable strict;
```

It would be great if the code between the `$$` pairs would also be syntax highligted (like Github does above :).

**Comment by jakob** [comment]
(this is a duplicate of #8)
