### ISSUE TITLE
Client connection parameters

### ISSUE THREAD

**Issue by aboltunov** [jakob/Postico#207]
Unless I've missed it, it appears to be impossible to supply client connection parameters (http://www.postgresql.org/docs/current/static/runtime-config-client.html). Being able to supply these would be particularly useful for making read-only connections with `default_transaction_read_only`.

**Comment by gcaraciolo** [comment]
Adding my suggestion about this feature:

> I'd like to suggest a security feature: asking for a password when doing danger operations like UPDATE, DELETE queries or DROP DATABASE, or any other operation that may change the database state.

**Comment by jakob** [comment]
We've just added a feature to Postico 2 that allows you to set client parameters with a startup query! You can find details in issue #702
