### ISSUE TITLE
ability to organize favorites?

### ISSUE THREAD

**Issue by wellsoliver** [jakob/Postico#209]
Probably not an issue for most, but I have about 25 connections, and the straight list of favorites is a little unwieldy. Is there a way we can add favorite folders, or categories, or draw borders between favorites, or something to organize this a little better than just using a straight list?

Thanks!

**Comment by jakob** [comment]
This suggestion absolutely makes sense (previous discussion: https://github.com/jakob/Postico/issues/21)

I think long-term I really need to rethink the favorites window. Right now it is optimised for people just getting started with PostgreSQL, and it works okay for people who only use a handful of databases, but it's really not ideal for power users :(

**Comment by pakohan** [comment]
I really like that idea. Funnily, it only affects users who are paying for the product since only they're able to have more than five connections *hint*

**Comment by thommcgrath** [comment]
Just adding my support for this. I have a probably 2 dozen favorites and it would be nice to be able to group them in beyond just reordering.

**Comment by felixge** [comment]
I got almost 60 favorites and would also love a better way to organize them :)

**Comment by jzelez** [comment]
+1

**Comment by derosm2** [comment]
+1 This would be great. I'd like to see filtering as well.

**Comment by Meradan** [comment]
I would like to see a function to sort the favourites by name to make the list more manageable. I currently have enough connections to make the drag-and-drop manual sorting a bit tedious to use, but not yet too many to make grouping necessary.

**Comment by DeoLeung** [comment]
I have been doing a full sequential scan of my favourite everyday, definitely a plus to have some ordering/search/grouping logic

**Comment by jakob** [comment]
I'm closing this issue because most of these suggestions have been implemented in Postico 2. Thanks for your feedback!

Postico 2 isn't released yet, but you can get preview builds here: https://eggerapps.at/postico2/

If you have suggestions how to further improve the favorite management in Postico 2, please open a new issue!
