### ISSUE TITLE
Usability of favorites window degrades as more connections are added

### ISSUE THREAD

**Issue by ulope** [jakob/Postico#21]
The current favorite window layout is only usable up to a relatively small number of saved connections.

I work as a freelancer and have a lot of connections to various client's databases saved. I'm currently at 22 favorites (and those are only the most active clients and projects) and it's already getting aggravating to find the correct one, even with a very strict naming scheme.

For the short term I'd suggest adding the possiblity to search / filter the favorites. Longer term I'd be very happy about a folder or tag based favorites system.

**Comment by nathanpalmer** [comment]
I don't have nearly that many, but even at 5+ I think some organization would be great. I usually have 2-3 per customer for Local, Staging and Production so some sort of grouping system would be nice. But I do love the simplicity of the list so I'd favor even section headers or something to keep it out of the way but informative.

**Comment by wellsoliver** [comment]
I was thinking something like Panic does w/ their Transmit FTP app, if you are familiar.

**Comment by jakob** [comment]
Yup, Transmit has always been a source of inspiration for me :)

**Comment by timiyay** [comment]
This feature would also help me too, now that Postico has become a tool I use every day

My use case is:  
* I work on lots of different client web apps
* for each project, we have >= 3 versions of our DB- usually development, staging and production
* in Postico’s favourites list, I usually have >= 3 databases per project
* this gets messy, and it can be hard to find the database I’m after

If the favourites list was able to group items into folders, or minimisable groups, that would help me out a bit.

**Comment by humancopy** [comment]
This is a really needed feature, please add it :)

**Comment by kimostler** [comment]
I like the folder and/or grouping suggestions.  I'd also like to have the favorites sorted automatically with an on/off button in preferences.

**Comment by jakob** [comment]
We've added a way to organize and filter favorites in Postico 2.

Postico 2 isn't released yet, but you can get preview builds here: https://eggerapps.at/postico2/

I'm closing this issue! If you have suggestions how to further improve the favorite management in Postico 2, please open a new issue!
