### ISSUE TITLE
Feature request: Keyboard shortcut for query window

### ISSUE THREAD

**Issue by pedrocunha** [jakob/Postico#211]
As the title says would be great to be able to focus on this guy with a keyboard shortcut.

Thanks

**Comment by jakob** [comment]
There the "Go To Terminal" command with shortcut `⌘⇧T` (in earlier versions the SQL Query View was called the SQL Terminal). This jumps to the query view.

If the focus is on the side bar, press the tab key twice to focus on the editor.
