### ISSUE TITLE
Support authentication using client certificates

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#218]
Currently, Postico will authenticate with client certificates if you store the cert and key at the paths `~/.postgresql/postgresql.crt` and `~/.postgresql/postgresql.key` respectively.

It would be convenient to be able to chose files at a different location, and to use different settings per favorite.

**Comment by twrobel3** [comment]
👍

This would be great.  So far Postico is the only graphical SQL client that I've found that works with [CockroachDB](https://github.com/cockroachdb/cockroach), but that ONLY supports auth using client certs (and in all the tutorials show multiple users, with their own cert sets), so a more convenient way to toggle user certs/have them tied to a favorite would be far more convenient.

Cockroach is still in early beta, but is gaining a lot of speed and attention, so being the first/only graphical client to support them will likely generate a lot of new users ;)

**Comment by jakob** [comment]
I've added a new issue concerning general CockroachDB compatibility: #224

**Comment by jakob** [comment]
I've now added a way to select client certificates per favorite:

1) click on the "Edit" favorite button
2) In the "Options" popup menu, click "Use TLS Client Certificate"
3) Now select both the .key and .crt files

This feature will be released in the next update. You can download a prerelease here:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1436.zip

**Comment by jakob** [comment]
Fixed in 1.0.7
