### ISSUE TITLE
Empty to NULL doesn't trigger 'save changes'

### ISSUE THREAD

**Issue by espen** [jakob/Postico#219]
1) Field has empty value: ''
2) Change to NULL.
3) Doesn't show 'save changes'

**Comment by jakob** [comment]
Thanks for the bug report. I assume you are talking about the sidebar?

I've discovered the cause of the issue and fixed it. The fix will be in the next update.

You can try a dev build with the fix here:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1426.zip

**Comment by espen** [comment]
Yes it was in the sidebar, sorry for not being clear about that. Thanks for the quick update!

**Comment by espen** [comment]
Just did a quick test - looks like it works now :)
