### ISSUE TITLE
Navigation between foreign keys

### ISSUE THREAD

**Issue by ulope** [jakob/Postico#22]
It would be very useful to have the option of navigating to a foreign key's target from within the row view (also from the sidebar, but less so I'd imagine).

Additionally if this were to be added the option to open the target in a new window would be great (e.g. by holding cmd while clicking the "link" - similar to how you'd open a link in a new browser tab)

**Comment by eliduke** [comment]
I want to give this one a :+1: 

> It would be very useful to have the option of navigating to a foreign key's target from within the row view (also from the sidebar, but less so I'd imagine).

**Comment by jakob** [comment]
I've now added a way to navigate to the related row today. I was a bit unsure how to implement it, so I'd love to hear your thoughts if its practical in this way. You can download todays build here: [Postico 2015-08-07](https://eggerapps-downloads.s3.amazonaws.com/postico-2015-08-07.zip)

(I forgot about the Cmd-Key opens new window idea, I'll add that at a later point)

**Comment by ulope** [comment]
I like the popup, however I would have expected the referenced row in the target table to be highlighted, or the filter to default to the foreign key value...

**Comment by jakob** [comment]
The referenced row should be highlighted in the target table... Hmm.

Could it be that you changed the row in the popover before clicking "Open Table"? In that case Postico jumps to the previous selected row (which I should probably fix?).

What version of PostgreSQL are you running?

**Comment by ulope** [comment]
Select row:
![Select row](http://cl.ly/image/2z0P153q423N/postico_fk_1.png)

Click on navigate button:
![Click on navigate button](http://cl.ly/image/2s2o2Q1W1F46/postico_fk_2.png)

Open target table:
![Open target table](http://cl.ly/image/3q2P2N1k0E29/postico_fk_3.png)

As you can see nothing gets highlighted and the target table also is not scrolled to correct row.

**Comment by jakob** [comment]
OK, thanks @ulope 
Is anything printed to Console.app?

**Comment by ulope** [comment]
Interesting. I just noticed that highlighting works correctly in other databases. 
The database I used above has `WITH OIDS` on almost all tables. Maybe that causes the Problem?

Also there is nothing logged to Console.app.

**Comment by jakob** [comment]
Okay, the problem was that Postico igrnored OIDs when looking for the related row. Thanks for pointing me to this issue @ulope 

Fixed in v0.26
