### ISSUE TITLE
Avoid sorting by clicking column header

### ISSUE THREAD

**Issue by aamine** [jakob/Postico#221]
For very large tables (50,000,000,000 rows for my case), sorting does not work completely.  Once we start sorting the table, all other queries stop working...

Sorting by clicking column header is handy nice feature for smaller tables, but it is too dangerous for large tables.  Do you have any idea to disable or avoid sorting?

My idea: I always disable "Always sort tables" and "Retrieve exact row counts" options because it does not work for many (large) tables.  What do you think that the option disables all kind of sorting action (from UI) ?

**Comment by jakob** [comment]
Did you try pressing cmd-. to cancel the query? Does that not work?

**Comment by aamine** [comment]
Yes, cmd-. magically works, thanks!

But I still think the sorting feature is not error proof, especially for non-engineer people.  In my company, a dozen people are analyzing large log tables using Postico, and they accidentally click the column header every day.

Even worse, Postico memoizes sorting settings for each table, so their Postico processes dispatches sorting query again and again, until they explicitly cancel it and click column header again (to cancel sorting operation).  That is too complicated opeartion, isn't it?

**Comment by jakob** [comment]
Would it help if Postico automatically cancelled the query when people click the column header (to change sort order) while a previous query is still running?

**Comment by aamine** [comment]
Yes, I think it is reasonable!

**Comment by jakob** [comment]
Postico now automatically cancels the query if it is still running when clicking the table header. This change will be in the next update.

You can download a prerelease version here:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1427.zip

**Comment by aamine** [comment]
Amazing, that looks nice!!!  Thanks
