### ISSUE TITLE
Ability to cancel queries in the table view

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#223]
If you are viewing the data from a big table and accidentally sort on the wrong column where no index can be used, you are basically forced to wait quite a while of force quit the application. 

A cancel button – maybe next to the display of the execution time of the current "query" – would be very handy in this situations.

**Comment by qwesda** [comment]
Force quitting the app does't even help, since the same table with the same order will be restored when postico re-opens.

**Comment by jakob** [comment]
You can add a cancel button to the toolbar by right clicking and choosing 'customize toolbar'

Or you can press cmd-. To cancel queries

**Comment by qwesda** [comment]
damn, never looked there. Nice.
