### ISSUE TITLE
CockroachDB compatibility

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#224]
[CockroachDB](https://www.cockroachlabs.com) is a hot new database that lots of people are talking about.

It uses the PostgreSQL client/server protocol, so it is possible to connect to CockroachDB servers with Postico.

However, CockroachDB is very different from PostgreSQL, so Postico needs a lot of changes to become fully compatible with CockroachDB.

I've started working on adding CockroachDB support, and basic operations work. I'm not sure how much effort I should put into this, since CockroachDB is still in beta, but I at least want to get basic functionality working.

In this issue I'll post updates related to CockroachDB.

If you are using CockroachDB and would like me to work on compatibility, please +1 this issue!

**Comment by jakob** [comment]
New build: https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1435.zip

This build of Postico detects that it is connecting to CockroachDB, and now displays databases and tables on the server. Basic operations like inserting, updating rows, creating tables, adding columns, already work.

**Comment by joeblew99** [comment]
wow that was really quick. thanks so muc @jakob
