### ISSUE TITLE
regression: can't update boolean values with postico 1.0.7

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#227]
The `Numbers in generated SQL are no longer quoted` feature introduced a bug, where boolean values can't be updated anymore in the table view. Changing a bool value generates for example this query:

```UPDATE "statements"."statement_issuer_revenue_type" SET "is_stream"=1 WHERE "id_statement_issuer_revenue_type"=1 RETURNING ...```

in older build the generated statement was:

```UPDATE "statements"."statement_issuer_revenue_type" SET "is_stream"='1' WHERE "id_statement_issuer_revenue_type"='1' RETURNING ...```

At least postgres 9.5.1 doesn't cast the integer value to bool implicitly. (I'm  a bit surprised, that it accepts a string here. thought only mysql did this ...)

**Comment by jakob** [comment]
Thanks for catching this! Fixed it in Postico 1.0.8.

PostgreSQL doesn't actually cast strings to bools implicitly. It just assumes that the literal is of type BOOL. 

From [the manual](https://www.postgresql.org/docs/9.4/static/typeconv-query.html):
> If the expression is an unknown-type literal, the contents of the literal string will be fed to the input conversion routine for the target type.

**Comment by qwesda** [comment]
I see ...  

Come to think of it, the same thing is happening with date or range literals.
