### ISSUE TITLE
Fuzzy Table Search / Quick Open

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#228]
Many text editors and IDEs have a command to quickly open files by typing parts of a file name.

It would be convenient if Postico allowed navigating to tables by tying a part of the name, and using fuzzy string matching to find the tables.

**Comment by ottob** [comment]
cmd+p ?

**Comment by jakob** [comment]
Like Sublime? Usually Cmd-P is print; I don't want to use such a standard shortcut in case I ever add print support. (I just realized that Sublime doesn't have a print command...)

Anyway, a quick survey shows that there seems to be no standard keyboard shortcut for this command:

- XCode uses Cmd-Shift-O (Open Quickly…)
- BBedit uses Cmd-D (Open File by Name…)
- TextMate uses Cmd-T (Go To File…)
- Sublime uses Cmd-P (Goto Anything…)

I don't want to use Cmd-P since that usually means "Print", and I don't want to use Cmd-T since that usually means "New Tab". But I'm open to suggestions.

**Comment by ottob** [comment]
Atom and Visual Studio Code also use cmd+p for fuzzy find. But I understand your concern regarding printing.

**Comment by jakob** [comment]
@ottob @clessg

I've added a "Quick Open" command to Postico. I decided to use cmd-P for now, despite the fact that if I ever add a print feature I'll probably need to change that shortcut.

This feature was mostly implemented by @SandroPeham, who was an intern in my company in June.

Anyway, here's a link to the latest build:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1488.zip

Would love to hear your comments.

**Comment by ottob** [comment]
Works great so far. Nice work!

**Comment by clessg** [comment]
Agreed, works great - very happy that this feature will be implemented soon! My only complaint is that it can be a little slow after you type something in. If it were more instantaneous, that would be wonderful.

**Comment by jakob** [comment]
@clessg Yes, it's slow the first time you use it. Maybe I can improve speed by using cached data from the sidebar.

**Comment by jakob** [comment]
I've just released version 1.0.9, which includes this feature. I'll leave the performance improvements for later, since that'll require a lot of refactoring unrelated to this feature.

**Comment by 1st** [comment]
Why not "Command + Space", like in all code editors for autocompletion?
