### ISSUE TITLE
wrong row count retained from previous filter

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#230]
I noticed the following behaviours when `retrieve exact row count` is turned of:

- pick a sufficiently large table
- filter on column where `column = x` returns a small subset
- clear the filter
- *result*: the row count of the filtered subset is still shown. If the row count is smaller then the paging size you are prevented from paging through the table until you reload the data

I also noticed a similar behaviour where except for clearing the filter you select a different field to filter on (and maybe a different operator like `IS NULL`). The result is the same, but I haven't been able to reproduce this reliably. It seems to work for some columns but not for others ...

**Comment by jakob** [comment]
Thanks for pointing this out! I've fixed the issue. As usual, here's a link to the latest nightly build:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1443.zip

**Comment by qwesda** [comment]
the fix seems to work fine
