### ISSUE TITLE
Set filter when following a foreign key

### ISSUE THREAD

**Issue by remys** [jakob/Postico#232]
When clicking the icon to open the "foreign key pop-up window", the pop-up's filter should be initialized with the referenced value

**Comment by jakob** [comment]
Does this make sense? Then only a single row would be shown. Right now, the popup has the same filter  it had last time it was used, and the referenced value is selected.

However, it might be a good idea not to store the filter; most times you probably want to search for different rows each time...

**Comment by remys** [comment]
The use case is to “drill down” to the referenced table;
Example: I have one table “document” containing several attribues describing a document and one table document_attachment containing a bytea attribute with the scanned document.
When browsing document, I would then like to “drill down” to the attachment by opening the “foreign key pop-up”, positioned on the specific row.
In the case of a bytea field, this is particularly important because downloading all the rows of “document_attachment” is quite inefficient. (Actually that’s why I have split my table in two parts (actually a 1:1 relation)
As an alternative, may be there could be a way to do a “lazy download of bytea attributes”, e.g. to download it only when shown in the detail pane of the browser.

**Comment by jakob** [comment]
Lazy loading of large fields (bytea, geometry) would be a good idea; see also #212. I'm not sure how much effort that would be to implement...

**Comment by jakob** [comment]
In Postico 1.0.9, I've added a heuristic that resets the filter. I don't want to add a filter that only shows the selected row, because that would be very inconvenient for data entry.

I'm closing this issue, since the real solution for the problem with loading times is lazy loading, which is tracked in another issue.
