### ISSUE TITLE
Open SQL query view without leaving content or structure view

### ISSUE THREAD

**Issue by gormster** [jakob/Postico#235]
I should be able to make SQL queries while referencing the structure of a table or multiple tables. It's annoying when I have a database with hundreds of tables to have to keep scrolling back to the top of the list to get back to the SQL query view, especially when I'm doing a query with a lot of JOINs.

**Comment by jakob** [comment]
There's a keyboard shortcut Cmd-Shift-T to quickly go to the SQL Query View.

You can also just open a second window, so you can have the table view / structure view and the query view side by side. 

I'm also working on adding support for tabs using the new window tabbing feature introduced in macOS Sierra (see issue #44 <https://github.com/jakob/Postico/issues/44>)

Hope this helps!

**Comment by mclaeysb** [comment]
Maybe the 'SQL Query' could be a button in the toolbar?

**Comment by jakob** [comment]
@mclaeysb If you right-click on the toolbar you can customize it and add an "SQL Query" button. I didn't want to add it by default since I was afraid it would clutter the interface.

**Comment by mclaeysb** [comment]
Excellent!
