### ISSUE TITLE
"Favorite" SQL Queries

### ISSUE THREAD

**Issue by mehcode** [jakob/Postico#246]
The SQL query history is nice but can become unwieldy. It'd be nice to have a list of possibly named SQL queries that I could execute with a click.

**Comment by jakob** [comment]
I wonder if there's a reason you closed this issue?

**Comment by mehcode** [comment]
@jakob I saw at least 4 other issues that are almost exactly like this. You even had a build that had some support for it. I figure I'll wait to poke that as it probably satisfies most of what I want here.
