### ISSUE TITLE
Display TIMESTAMPTZ and similar columns in my timezone with an icon to change the displayed timezone

### ISSUE THREAD

**Issue by mehcode** [jakob/Postico#249]
More on this .. 

TIMESTAMPTZ by default shows ISO format -- it'd be interesting to show the timestamp in my locale's preferred format as well (again with changing from a gear/similar icon in cell)

**Comment by Dorian** [comment]
This would help us a lot too 👍 e.g. Blazer does that

**Comment by jakob** [comment]
In Postico 2 it's now possible to set the timezone and datestyle with a startup query, for example:

```sql
set DateStyle = Postgres, Euro;
set TimeZone = 'Europe/Vienna';
``` 

See issue #702 for details!
