### ISSUE TITLE
[cockroachdb] drop index syntax is wrong

### ISSUE THREAD

**Issue by giskarda** [jakob/Postico#251]
Hi,

The grammar to drop indexes in cockroachdb is different from the postgresql one:

https://www.cockroachlabs.com/docs/sql-grammar.html#table_name_with_index

`drop index table@index_name`

Would be nice to support it.

**Comment by peter-dudbridge** [comment]
+1

**Comment by jakob** [comment]
I've added supponrt fr reaming and dropping indexes in cockroachdb

You can try a development build here:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1500.zip
