### ISSUE TITLE
turning off having all of the content saved in the SQL editor?

### ISSUE THREAD

**Issue by wellsoliver** [jakob/Postico#256]
Seems like you introduced a feature where the contents of the SQL editor are maintained through a restart-- any chance I can turn this off? :) For whatever reason it's driving me bananas. I'm high maintenance, though.

**Comment by wellsoliver** [comment]
(though, I think the bigger issue is that it's connection independent-- meaning the contents of an entirely different unrelated DB come up when I connect somewhere else and that always throws me)

**Comment by jakob** [comment]
Unfortunately there's no way to turn that off, and I don't really want to add a setting for that.

**Comment by wellsoliver** [comment]
can you make a little setting I can adjust with defaults? will buy you beer!

**Comment by jakob** [comment]
OK, I added a hidden setting for you:

1) Download latest nightly:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1495.zip

2) Type the following in Terminal:
`defaults write at.eggerapps.Postico DontRestoreQueryViewText 1`

(This setting only affects query restoration after closing the window. Window restoration (eg. after a crash) still restores your query.)

Considering that you're on the other side of the ocean, I'll accept emoji beer as payment.

**Comment by wellsoliver** [comment]
🍺🍺🍺🍺🍻🍻🍻🍻🍕🍕

**Comment by wellsoliver** [comment]
or if you're into wine🍷🍷🍷
