### ISSUE TITLE
auto-commit?

### ISSUE THREAD

**Issue by jongyonkim** [jakob/Postico#257]
Any plans of supporting ```auto-commit``` option when running SQL queries?

[MySQL Workbench feature example](https://www.quora.com/How-can-I-commit-changes-in-MySql-workbench)

**Comment by jakob** [comment]
As far as I understand, PostgreSQL doesn't have an auto-commit option like MySQL.

Whenever you execute queries, they will be wrapped in an implicit transaction. To execute multiple queries, you can select them and press Cmd-Return; or you can press Cmd-Alt-Return to execute all queries.

If you want explicit control of transactions, you can use the BEGIN TRANSACTION/ROLLBACK/COMMIT commands.

Does that help? If not, could you explain in more detail what you'd like Postico to do?

**Comment by jongyonkim** [comment]
I think it's more of a client-side feature than having to do with specific databases.

I found [this](https://aws.amazon.com/premiumsupport/knowledge-center/redshift-no-data-copied/):
> If the SQL client’s default behavior is to disable autocommit, you can resolve the issue in either of these ways:
• Enable autocommit for the SQL client...
• Explicitly commit the transaction...

You are correct that I can use the transaction verbs. However it would be convenient to have ```auto-commit``` turned on to avoid having to remember appending ```commit``` for every SQL query.

**Comment by jakob** [comment]
But that is exactly what Postico does, isn't it? If you don't execute BEGIN, the query is implicitely wrapped in a transaction and committed automatically.

Is this different on Redshift? Do you need to type COMMIT even if you never typed BEGIN?

**Comment by tclass** [comment]
I use Redshift too and never had a problem with that. I never typed in Commit except if I defined my own transaction obviously. I even used the Copy command and had no problems! Works fine

**Comment by jakob** [comment]
Thanks @tclass, I was beginning to wonder if I did something really wrong when testing my app...

Anyway, I found a reference to autocommit in the PostgreSQL docs:
https://www.postgresql.org/docs/current/static/ecpg-sql-set-autocommit.html

According to the docs, this is only relevant for "Embedded SQL", which is a weird old technology that Postico doesn't use.

I think there is some misunderstanding going on here; I'm closing this issue, since I don't understand how autocommit is relevant to Postico.

**Comment by nikitar** [comment]
Would it be possible to allow user to _disable_ autocommit, similar to `\set AUTOCOMMIT off` in [psql](https://www.postgresql.org/docs/current/app-psql.html#APP-PSQL-VARIABLES-AUTOCOMMIT)?  Just trying out Postico and this is one feature from psql I do miss. It gives me a lot of peace of mind when connecting to a production database, as a defence against fat fingers.

Thanks for making this app, by the way. I also tried DBeaver, and Postico is so much more pleasant to use!

**Comment by jakob** [comment]
@nikitar I don't want to add an `autocommit off` mode to Postico. It would add a lot of complexity for a rarely used feature. Maybe setting transaction mode to read only would be useful? See this page in Postico docs for more info: https://eggerapps.at/postico2/documentation/read-only-connections.html
