### ISSUE TITLE
`on update` and `on delete` properties of foreign keys should be editable

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#264]
Right now the foreign key has to be deleted and re-created. The UI could have the `on update` and `on delete` properties of the FK as editable and generate the proper `DROP CONSTRAINT / ADD CONSTRAINT` query.

**Comment by jakob** [comment]
Editing Foreign Key constraints is now possible (and you can change everything)

You can download a nightly build from https://eggerapps.at/postico/builds/
