### ISSUE TITLE
Connect via SSH: Private Key; The File Couldn't be Opened

### ISSUE THREAD

**Issue by wfortin136** [jakob/Postico#267]
I am currently encountering an error attempting to load a pem file for ssh tunneling. After I select the "Connect via SSH", and attempt to select a private key, I continually get "The File Couldn't be Opened." While I have changed the permissions for both the Postico App as well as those for the pem file while trying to troubleshoot, the current permissions are setup as follows (which mimics a coworker who does not have this issue).

Pem file: 
-rw-------

Postico:
ls -le /Applications/Postico.app
drwxr-xr-x@

Executable in Postico App:
ls -le /Applications/Postico.app/Contents/MacOS
-rwxr-xr-x@

Is this a problem seen before with Postico? Do you know if there is a log that will capture the error that is occurring on file open?

Cheers,
BIlly

**Comment by jakob** [comment]
Are you sure that you want to use a SSH tunnel?

PEM files are usually used for SSL/TLS connections, not for SSH connections. If that is the case, please select the "Use TLS client certificate..." option instead of the SSH option.

**Comment by wfortin136** [comment]
We are hosting our postgres db on aws which is locked down to access through a specific VPC. So we ssh tunnel through a server in the same VPC. In any case, when attempting to read the file through the SSL/TLS connection, I get the same The File Couldn't be Opened error message. Any thoughts?

**Comment by wfortin136** [comment]
@jakob Any additional thoughts? I've really liked Postico outside of this issue. Me and a handful of people at my company have bought Postico licenses as a trial group. But I really can't recommend the purchase of additional licenses if I can't get ssh tunneling to work. I suspect it has something to do with the Mac file systems permissions and the interaction with Postico, but I can't for the life of me figure out what is configured differently. Any possible insights would be greatly appreciated.

**Comment by jakob** [comment]
Hi @wfortin136, sorry for the delayed response. 

When do you get the error message "The File Couldn't be Opened"? Right after you click "Open" in the dialog? Or after you click "Connect"? Can you send me a screenshot of the error message? My email is jakob@eggerapps.at

Please also tell me about what version of OS X you are running? And are you storing the private key on a network volume?

**Comment by jakob** [comment]
In case someone else has the same issue, further digging revealed that this was due to the following underlying error from the security framework: Error Code 256 "Failed to retrieve app-scope key".

I don't know what exactly causes this issue, and googling for the error message results in the following suggestion from an Apple support engineer:

> I can see two potential causes for this:
> something is borked with code signing on the user’s machine — The scoped bookmark machinery needs to be able to get the code signature of your app in order to do its magic, and if that failed you’d get an error like this.
> something is borked with the user’s keychain — The scoped bookmark machinery stores a secret in the keychain (you can see it in Keychain Utility by searching for “com.apple.scopedbookmarksagent.xpc”) and you’d get this error if that was failing somehow.
> Of these, #2 seems most likely.  It’s also easy to test.  Have the user create a new account and repeat their test in that account.  The new account will have a new keychain, and thus avoid any potential borkage with the user’s current keychain.
> Share and Enjoy 
> — 
> Quinn “The Eskimo!” 
> Apple Developer Relations, Developer Technical Support, Core OS/Hardware 

https://forums.developer.apple.com/thread/46583

**Comment by wfortin136** [comment]
Just to follow up for anyone encountering this issue, I needed to reset my keychain as described here:
http://apple.stackexchange.com/questions/153720/how-do-i-delete-or-fix-my-keychain-after-changing-my-password

Once that was completed, I was able to load my pem files and ssh tunnel with no problem. You can probably expect it to wack out some of your certificates which you'll need to re-aquire, but problem solved!

**Comment by smiley325** [comment]
@wfortin136 it happened to me right after resetting my password, solution worked
