### ISSUE TITLE
Ed25519 support

### ISSUE THREAD

**Issue by SijmenSchoon** [jakob/Postico#268]
I have recently switched my keys to Ed25519 for my SSL connections due to its speed and security. However, Postico doesn't seem to support them:
![Image](https://sijmenschoon.nl/_matrix/media/v1/download/sijmenschoon.nl/VvgcioGuEBeCFQClGGEZLiYs)

**Comment by jakob** [comment]
Postico uses libssh2, so I'm limited to whatever libssh2 supports. Unfortunately, there's no support for elliptic curve cryptography yet.

**Comment by jakob** [comment]
See this issue for details https://github.com/libssh2/libssh2/issues/39

**Comment by fenichelar** [comment]
@jakob libssh2 now supports ed25519!! Any chance Postico could upgrade? Hopefully it is simple.

**Comment by fenichelar** [comment]
@jakob It works already!! I should have tried it earlier. https://libssh2.org/ is no longer correct.

**Comment by jakob** [comment]
@fenichelar Sorry, I must have forgotten to update this issue. Postico supports EDCSA and Ed25519 keys since version 1.4.

(There hasn't been a libssh2 release since 2016, but development has been ongoing, so I've switched to using an "unstable" build of libssh2)
