### ISSUE TITLE
Auto-Uppercase SQL Keywords

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#271]
It would be nice to have an option to automatically uppercase SQL keywords.

This request is slightly related to #155 (auto-format SQL statements), but probably simpler to implement.

**Comment by benoittgt** [comment]
+ 1

**Comment by troex** [comment]
there is [atom-beautify](https://github.com/Glavin001/atom-beautify) package for Atom editor, it uses [sqlformat](https://github.com/andialbrecht/sqlparse) (python) to "beautify" 

they basically has the settings for sqlformat, that's not probably what you want just showing the idea
![atom-b](https://cloud.githubusercontent.com/assets/436912/25510321/01ef6806-2bc8-11e7-90e1-bbfb0cbe9247.png)

**Comment by dominijk** [comment]
Simpler still is the [pg-formatter](https://github.com/gajus/pg-formatter) package

**Comment by martinjankoehler** [comment]
Hey @dominijk @troex,
we've been working on this feature (Auto-Uppercase for SQL Keywords),
it's available in Postico 2 via the built-in updater or manually at 
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-9141.dmg

Please let us know should any issues occur.

Best regards,
Martin

**Comment by jakob** [comment]
In case anybody is looking for the new AUTO-UPPERCASE feature, here's where to enable it:
<img width="853" alt="Bildschirmfoto 2021-12-06 um 16 07 59" src="https://user-images.githubusercontent.com/198305/144870601-65150fff-3d1d-4293-b103-a015329596aa.png">
