### ISSUE TITLE
Remember SQL Query divider position

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#273]
The default position of the divider between the SQL query editor and the result view is near the top. It would be convenient if Postico remembered the position of this divider and wouldn't always reset it to the default position.

**Comment by martinjankoehler** [comment]
We have implemented the first issue (sticky horizontal query window divider) with Postico 2 build 8375,
available via the built-in auto-updater or as manual download at
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8375.dmg

Best regards,
Martin
