### ISSUE TITLE
PL/pgSQL Support

### ISSUE THREAD

**Issue by inkrement** [jakob/Postico#275]
Is PL/pgSQL supported by the editor?

**Comment by jakob** [comment]
No, not really. If you have a CREATE FUNCTION command or similar, Postico just marks the code as a character literal (which it technically is).

I need to improve the syntax highlighting code to detect code blocks and also highlight them.

See issue #8

**Comment by martinjankoehler** [comment]
Hello @inkrement,

we've been working on this issue (syntax highlighting and autocomplete in dollar quoted code blocks).

This feature is now available in Postico 2 via the built-in auto-updater
or as a manual download at https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8831.dmg

Please let us know should any issues occur.

Best regards,
Martin
