### ISSUE TITLE
Click X button accidentally

### ISSUE THREAD

**Issue by enderahmetyurt** [jakob/Postico#277]
Hi,

When click "X" button accidentally the database connection is closed. I need to back this process. I mean how I can undo that.

Cheers.

**Comment by jakob** [comment]
Unfortunately there is no way to 'undo' closing a window. I'm not even sure what that should do.

Do you want to restore the contents of the SQL query editor? The latest version of Postico does that; just reconnect to the database.

**Comment by enderahmetyurt** [comment]
@jakob should you add a "cancel" button near the "buy" and "no thanks" 🤔
