### ISSUE TITLE
The shortcut for Filter should be ⌘F

### ISSUE THREAD

**Issue by csuhta** [jakob/Postico#279]
⌘F is not bound to anything in Postico, but it's the macOS conventional shortcut for finding things.

Is there a reason that ⌥⌘F was chosen as the Filter shortcut instead?

**Comment by firedev** [comment]
Maybe ⌘F is supposed to be used to search tables, but it's not working either, you have to click on the Search field

**Comment by senjaz** [comment]
Technically it is possible to have it do both depending on what has focus. The menu item needs to be set up as a nil targeted action and implement that action doing different things at appropriate points in the responder chain. I'm not sure that doing so is a good thing though.

**Comment by brandondrew** [comment]
⌥⌘F can be used for filtering fields in the right-hand data panel, and ⌘F for filtering data in the main (table) panel.

**Comment by jakob** [comment]
In Postico 2 we added the shortcut ⌘F to open/close the filter bar.

It's indeed a bit messy, because ⌘F normally triggers the Cocoa text Find panel / bar, but we found a workaround. I hope we don't run into any conflicts.

You can download the Postico 2 Preview here: https://eggerapps.at/postico2/
