### ISSUE TITLE
Start typing should focus search field

### ISSUE THREAD

**Issue by firedev** [jakob/Postico#280]
It would be great to be able to just type the name of the table to get the list filtered. If not - a shortcut to go to the search field. When you have a large db with multiple schemas it's not very easy to find the table you need.

**Comment by jakob** [comment]
Postico now has an "Open Quickly" command: Just press Cmd-P and start typing a table name. Postico will perform a fuzzy-match search over all tables in all schemas

Is this what you are looking for?

**Comment by firedev** [comment]
Oh, didn't know that, thanks! 

Another suggestion, though. Right now you can type a letter and it goes to the table that starts with this letter. What if it focused directly on the search box once you start typing?

**Comment by jakob** [comment]
@firedev that would be a good idea. I'm renaming this issue

**Comment by jakob** [comment]
(allthough I'm not 100% sure that this would be good, since it would also remove focus from the table view)

**Comment by firedev** [comment]
It should behave like this when the focus in on the tables list I imagine, right now there is a first-letter search which is not very helpful with many tables and tenants.

In other words it would be cool if I could simply type `transactions` and get this:

![image](https://cloud.githubusercontent.com/assets/115612/19384630/6437662c-9234-11e6-852f-88f6869917ff.png)

**Comment by jakob** [comment]
@firedev yeah, it makes sense. Right now you can also use the Cmd-Shift-F shortcut to bring this field to focus.

**Comment by firedev** [comment]
Oh, thanks! Had to learn the hard way, couldn't find it, guess next time worth checking up the menu.

**Comment by senjaz** [comment]
The existing behaviour to select rows in a table based on what you type is way more useful and is also consistent with all other focused list behaviour throughout macOS. Changing it in my opinion would be a back idea.

**Comment by jakob** [comment]
I agree with @senjaz, and I've decided not to go forward with this suggestion.

Thanks for taking time to discuss this!
