### ISSUE TITLE
Can't see private key file name in settings

### ISSUE THREAD

**Issue by firedev** [jakob/Postico#281]
Wish I could see what file is in use:

![image](https://cloud.githubusercontent.com/assets/115612/19415459/f8585bec-939a-11e6-80a7-bd5043064c38.png)

**Comment by jakob** [comment]
I made the font size smaller and made the text field selectable so you can scroll by dragging. Hope this helps!

Prerelease build:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1623.zip
