### ISSUE TITLE
"Pin" favorite table, schemas, SQL window

### ISSUE THREAD

**Issue by Ricardo-C-Oliveira** [jakob/Postico#287]
My regular workflow uses the search bar quite a bit, this means that once I find the table or schema I usually have to clear it to bring the SQL Query back to the result panel in order to open it. I wonder how useful would be to be able "pin" the SQL Query, or even specific tables, so that it wouldn't disappear when using the search bar.

**Comment by jakob** [comment]
Not exactly what you've been asking for, but:
- you can add a "SQL Query" button to the main toolbar (right-click the toolbar and select  "Customize")
- you can press Cmd-Shift-T to go to the SQL Query View
- you can use "Quick Open" to navigate (Cmd-P)

**Comment by Ricardo-C-Oliveira** [comment]
Well, this changes everything. It even has the cancel query button! Love it!
