### ISSUE TITLE
Feature request: favorite optimisation and db exports

### ISSUE THREAD

**Issue by arbroen** [jakob/Postico#290]
Hello dear Postico creator,

As a frequent user I'd love to see a few ease of use updates. 

Favorites bar
- Groupable favorites (E.g. if you have an otap street way of working)
- Searchbar for favorites (I have like 50+ databses)
- Optimized scrolling when moving a DB. In my 50+ favorites moving one database favorite is absolute hell due to sensitive scrolling speed. 

Database interface
- A button to export an entire DB to whatever applicable file types. And vice versa. I've seen this request before, but this is my +1 I guess. 
- Autocomplete for SQL queries would be wicked awesome. 

If any could be added I'd be very grateful. 

Thank you for a great product!

Jeroen

**Comment by mikehanssen** [comment]
+1

**Comment by jakob** [comment]
I agree that the usability of the favorites window is one of the sore spots in Postico.

People want more settings (eg. #117, #157, #207) and a better way to organize them (#21, #209), and they also want to sync them (#282, #83). I don't think that the current design can be adapted easily to cover all these requirements.

For this reason, I'm planning to redesign the favorites window at some point. Unfortunately that also means that it will probably take some time.

I'll have a look at the scrolling issue, maybe I can fix that quickly.

**Comment by arbroen** [comment]
I'm impressed with the response time. I'm a fan of your product so please take your time to make something beautiful. 

Keep up the good work. :)

**Comment by MarkASwanson** [comment]
+1

**Comment by jakob** [comment]
It's a few years later now, but I think that Postico 2 can now check off most of those requests!

- Postico 2 allows grouping favorites
- Postico 2 has a search field for favorites
- scrolling issues have been fixed as well
- autocomplete has been in Postico 1.x already for some time

The only thing that's missing is DB export, but I think that feature is beyond the scope of Postico.

Postico 2 isn't released yet, but you can download a preview from https://eggerapps.at/postico2/

I'm closing this issue now! Please feel free to open new issues if you have any follow up suggestions!
