### ISSUE TITLE
auto-spacing column widths in query results issue?

### ISSUE THREAD

**Issue by wellsoliver** [jakob/Postico#291]
Has anything changed here? I'm noticing in 1.0.10 (and maybe 1.0.9) that the column widths are randomly excessively small or large.

MacOS Sierra now, not sure if that's causing any problem.

Not a big deal, more just a curiosity.

**Comment by jakob** [comment]
I just saw this as well, I'm not sure what's going on. I need to investigate this.

Jakob

**Comment by wellsoliver** [comment]
Any chance you can take look? Seems to be getting weirder :)

**Comment by jakob** [comment]
I've fixed the erratic column sizing in version 1.1.1. It should behave much more predictable now.

The behavior is now as follows:
- First time you execute a query, columns are always autosized
- If you execute a query with the same columns as the previous one, no autosizing occurs (to avoid jittering). You can autosize manually by right-clicking the table header.
- If you execute a query with different column names, the columns are autosized again.

In my testing, this seems to work well in most cases.

If you still have issues related to autosizing, feel free to reopen the issue, and let me know of any problems you have with the behavior!
