### ISSUE TITLE
"Nested" tables list

### ISSUE THREAD

**Issue by voltechs** [jakob/Postico#300]
Hello!

First let me just say how much I love Postico! Thank you for making a modern and powerful GUI for working in PostgreSQL.

I have a feature request.

One of the most beloved and powerful features that PostgreSQL offers is true native table inheritance.

My team and I have settled on a naming scheme that I think would be applicable to others as well, and shares a natural and known paradigm used today. Consider the following tables.

```
vehicles
vehicles/automotives
vehicles/automotives/cars
vehicles/automotives/bikes
vehicles/aeroplanes
vehicles/aeroplanes/fixed_wing
vehicles/aeroplanes/rotary
```

I understand above is a bit of a silly example. It's not my place to pedal the benefits or proper architecture of table inheritance, I leave that up to the individual. However, a pattern like this is not unreasonable.

What I'd like to request is that Postico sense this naming paradigm (slashes to indicate hierarchy) and use some nested expandable tree view. As projects mature and become enterprise-level, the complexity of the database increases. This would help with organization!

```
🔽 vehicles/
  ▶️ automotives/
  🔽 aeroplanes/
     *️⃣ fixed_wing
     *️⃣ rotary
```

To be clear, parent tables would still be selectable, just as a directory today in modern file managers are. 

Thanks for your consideration!

~ Dale

**Comment by jakob** [comment]
Hm. Instead of parsing slashes, Postico should probably really read the `pg_inherits` table. This would probably also be useful for people using partitions (see #274).

Of course, then you'd end up with something like this:
```
🔽 vehicles/
  ▶️ vehicles/automotives/
  🔽 vehicles/aeroplanes/
     *️⃣ vehicles/aeroplanes/fixed_wing
     *️⃣ vehicles/aeroplanes/rotary
```

Which is not quite as elegant. I could then go and hide prefixes shared with the parent table, but that might be confusing for people who don't know Postico does this.

One problem here is that PostgreSQL supports multiple inheritance, which can't be displayed in a hierarchical view.

One reason why Postico doesn't support inheritance yet is that I just haven't seen any people actually use it. I understand that your database schema is probably not public, but it would be really awesome to see how this feature is used in the real world.

**Comment by oakstreetsoftware** [comment]
I have used inheritance in my applications. I do it for code re-use, but it isn't supported across other DBMS's, so I often just use templates that serve the same purpose, but they don't show up in the schema. I like the idea of arranging tables according to their class hierarchy.

**Comment by jakob** [comment]
I have decided not to add this feature (nest tables according to name) because I don't see any evidence that this is a commonly used pattern.

(Support for inheritance/partitions is not related to this)

**Comment by voltechs** [comment]
> Hm. Instead of parsing slashes, Postico should probably really read the `pg_inherits` table. This would probably also be useful for people using partitions (see #274).

I think this is a good approach, and doesn't restrict any additional features you might want to build in later.

> ... I could then go and hide prefixes shared with the parent table, but that might be confusing for people who don't know Postico does this.

That's a fair point, but quite solvable via UI. For starters, you've got the full table name in the window/tabl title. You could also put in small, faded parentheses the full table name to the right of the shortened name. You could also have a setting that says "show full table names for inherited tables". I'm sure you'll figure out a good solution. After all, `Postico` _is_ a GUI (and a beautiful one at that) meant to make one's life easier and help organize/display an overwhelming amount of data/information in a pleasant manner.

> One problem here is that `PostgreSQL` supports multiple inheritance, which can't be displayed in a hierarchical view.

I would suggest showing the child-table under both parents. Of course we're not duplicating data, so this feels reasonable to me. Multiple Inheritance (MI) is something I haven't seen a lot of, but single inheritance I can definitely say I've seen. Not all languages support MI, and those that do have different nuances, so it's difficult to find consistency that could be mirrored at the application level.

For both of your two previous concerns, I think it's fair to say that those who are using inheritance in their tables have an above average understanding of `PostgreSQL` and should know their schema structure well enough to navigate appropriately.

> One reason why Postico doesn't support inheritance yet is that I just haven't seen any people actually use it. I understand that your database schema is probably not public, but it would be really awesome to see how this feature is used in the real world.

Unfortunately our schema is not public, but I know from experience that this is a very popular feature of `PostgreSQL`, and not uncommon in large enterprise-ish applications. When you say "Postico doesn't support inheritance yet", though, what exactly do you mean by this?

I expect many will experience (as my team and I have already) a lower barrier to entry on table partitioning, and those who aren't already, will leverage partitioning for scaling purposes. One of `PostgreSQL`'s power features is the partitioning, especially given the new [declarative partitioning](https://www.postgresql.org/docs/10/ddl-partitioning.html#DDL-PARTITIONING-DECLARATIVE) present in [10+](https://www.postgresql.org/about/news/1786/) and I expect many will (as my team and I have already) begin to leverage partitioning for scaling purposes given this reduced barrier-to-entry.

Apart from the inheritance to reflect different behavior, there is also the scaling (as mentioned above) partitioning by range, scalar or date. So for a chronologically partitioned table, you might have something like this:

<table width="100%">
<tr><th>Basic</th><th>Pretty</th></tr>
<tr>
<td valign=top><pre>
*️⃣ users
🔽 messages
   *️⃣ messages/2018/01
   *️⃣ messages/2018/02
   ...
   *️⃣ messages/2018/11
   *️⃣ messages/2018/12
   *️⃣ messages/2019/12
</pre></td>
<td valign="top" width="75%"><pre>
*️⃣ users
🔽 messages
   ▶️ 2017
   🔽 2018
      *️⃣ 01
      *️⃣ 02
      ...
      *️⃣ 12
   🔽 2019
      *️⃣ 01
</pre>
</td>

</tr></table>
