### ISSUE TITLE
Query errors should be made more visible

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#302]
I had the problem, that I had a query which was returning some rows, but also trowing an error. All I was seeing was that the number of rows was to small and that the amount of rows changed depending on what columns were selected. 

Turn out that Postgres was throwing an error when casting some values, but since the query status is only shown if no rows are returned it took me longer than necessary to figure out what was going on.

Postico could look for these errors and display a little error symbol (and maybe the number of errors) next to the query status/result dropdown.

Here is an example query that exhibits this behaviour.

```sql
SELECT col::numeric
FROM (VALUES ('1.1'), ('not a number')) AS data (col);
```

**Comment by jakob** [comment]
Thanks for reporting this issue, and thanks for the sample query. That's a pretty serious usability problem!

I've made two changes to address this problem:
- Postico now shows the "Query Status" message by default when an error occurs, even if rows are returned
- A little status icon is shown in the bottom right corner in the window (yellow for errors, green for success) after the query completes

You can download a prerelease build here:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1540.zip

**Comment by qwesda** [comment]
Thanks for the change. This will save people some head scratching in the future.
