### ISSUE TITLE
Division by zero: fails silently when divide MONEY by INTEGER or NUMERIC

### ISSUE THREAD

**Issue by maxdl-mx** [jakob/Postico#304]
Actual:
Dividing by 0 fails silently - it returns as many rows which do not contain 0 in the divisor, and then stops without error message.
Tested with:
- MONEY / INTEGER
- MONEY / NUMERIC
- MONEY::NUMERIC / INTEGER
- MONEY::NUMERIC / NUMERIC

Expected:
Other clients (such as PGAdmin) returns the error message: "ERROR:  division by zero"

**Comment by jakob** [comment]
This is probably the same issue as #302 

Could you try the following build if it behaves as expected?
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1540.zip

**Comment by maxdl-mx** [comment]
That's the fastest fix ever.!
Thanks, it works as expected.
