### ISSUE TITLE
Import/Export CSV and Dump Files?

### ISSUE THREAD

**Issue by tblanchard** [jakob/Postico#305]
I don't see the ability to dump or load a database or import a CSV file and have a table created with sensible defaults.

**Comment by codepushr** [comment]
Just bought a licence and learned that I can't import whole databases/sets of tables.

**Comment by jakob** [comment]
We're currently working on CSV import.

Importing/exporting SQL dumps is not something I have planned for now. Dumps created by pg_dump are pretty much only compatible with psql, and creating a psql-compatible parser is complicated by the peculiar line-based parsing that psql does.

If you create a dump with `pg_dump --inserts`, and it's not too big (less than say 50MB), you can just open it in the SQL query view, and execute it.

Import/Export is still a weak spot of Postico. I want to improve it, but backup and data migration will never be the main focus of the app.

**Comment by jsmestad** [comment]
Would love to see this as well

**Comment by frankcash** [comment]
any update on this?

**Comment by jakob** [comment]
We're working on CSV import. We've already implemented two different user interfaces, but both of them had usability issues in some use cases. @chrispysoft is now working on our third attempt to make an intuitive & versatile import UI.  This one will hopefully be the final one.

**Comment by andelar** [comment]
+1

**Comment by pboese** [comment]
+1

**Comment by jhiemer** [comment]
This would be a really nice feature. Would love to see it in Postico soon.

**Comment by chrispysoft** [comment]
Hi! We just released the first public development build of the all new CSV import feature. Now you can easily import CSV files to you databases in a quick and intuitive way using a modern UI. Please let us know how it works for you!

**Comment by chrispysoft** [comment]
You can download build 2043 from
https://eggerapps.at/postico/builds/
😊

**Comment by dominijk** [comment]
Is there any documentation on this feature, its not obvious to me how it works

**Comment by jakob** [comment]
@dominijk There is no documentation yet for the import feature -- we don't want to write docs before we've finalised the design. We've tried to make the feature as discoverable as possible; if something is not obvious we need to fix it.

I'd love to hear more about the issues you are having with the import feature:

1. What did you try to do?
2. What did you expect to happen?
3. What actually happened?

In case that your data is not confidential, could you send us a copy of the file you are having trouble importing? You can reach me at jakob@eggerapps.at

**Comment by flaccid** [comment]
Was anything implement for dumps as opposed to csv ?

**Comment by jakob** [comment]
@flaccid No, we haven't worked on dumps at all.

Adding support for importing/exporting SQL dumps would be a lot of work and also require a lot of ongoing maintenance. And I don't see any opportunities for big improvements compared to just using pg_dump / pg_restore from the command line.

**Comment by jakob** [comment]
Hey everyone! I'm closing this issue, since it is very similar to #68.

Let's continue discussion of the CSV Import feature in #68.

With regards to SQL dumps, we have no plans to work on this at the moment (see my reasoning above).
