### ISSUE TITLE
Touch Bar

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#311]
@chrispysoft has been working on adding support for the Touch Bar on the new Macbook Pro. We've added some convenient buttons for editing & executing queries, as well as buttons to quickly insert special values like "NULL" or "DEFAULT" etc.

If you're an early adopter of the new MacBook Pro, we'd love to hear your thoughts. Any other frequently used functions that would be convenient on the touch bar?

You can try a prerelease version here:

https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1560.zip

**Comment by mohdaminyuddin** [comment]
Just tested the 1560 version. It's nice, very cool. 

![Touch Bar](https://cloud.githubusercontent.com/assets/300463/22107790/d0739994-de8a-11e6-8901-5c40810e0bc2.jpg)
