### ISSUE TITLE
Is there a way to update an existing column type?

### ISSUE THREAD

**Issue by wihodges** [jakob/Postico#312]
Wondering if there is a way through Postico to alter the column type of table? E.G. Change a text column to an integer column and have it update all existing rows. Currently if you try to change field type you will get the the "Hint: You might need to specify "USING " message.

**Comment by wihodges** [comment]
Ok so was able to solve pretty easily using Postico SQL Query window. 
`ALTER TABLE "public"."name_of_the_table" ALTER COLUMN "name_of_col" SET DATA TYPE numeric USING (name_of_col::numeric);`
Click execute and returns AlTER TABLE. It required me to quit Postico and re-open again to see updated structure.

**Comment by jakob** [comment]
You can also just type the using clause in the type field!

Eg, just type "numeric USING (name_of_col::numeric)" into the type field.

(not very intuitive, but it works)

**Comment by jakob** [comment]
Also, no need to quit Postico; just press Cmd-R (or use the refresh button in the tool bar)
