### ISSUE TITLE
Postgres passwords with $, at least, don't seem to work

### ISSUE THREAD

**Issue by jotto** [jakob/Postico#315]
Create a Postgres user, set a password:

`ALTER USER myuser WITH PASSWORD 'pa$sword';`

and Postico 1.0.10 fails password authentication

**Comment by jakob** [comment]
It works fine for me. Did you check that pg_hba.conf is set up correctly? Does connecting with psql work?

**Comment by jotto** [comment]
Thank you for the confirmation; I think the specific machine I'm using actually has a different password than I was told.

When setting up an SSH tunnel (to ensure it doesn't peer auth), psql does indeed fail with the password I was using.

Sorry for the false alarm, and BTW, Postico is amazing software. I am a proud supporter and evangelist.
