### ISSUE TITLE
Breadcrumb does not contain schema

### ISSUE THREAD

**Issue by jakajancar** [jakob/Postico#32]
The breadcrumb lists:

    Server > Database > Table

But without the schema between the database and the table, the table is ambiguous.

**Comment by adi-** [comment]
+1

**Comment by jakob** [comment]
This will be fixed in version 0.27.
Prerelease build: https://eggerapps-downloads.s3.amazonaws.com/postico-2015-09-30.zip

**Comment by jakob** [comment]
Fixed in 0.27
https://eggerapps.at/postico/changelist.html
