### ISSUE TITLE
[Feature request] auto completion of keywords, schema, table and field names

### ISSUE THREAD

**Issue by jtzemp** [jakob/Postico#322]
Hey, Jakob.

I'm a licensed user and I really am grateful for Postico. One thing that would make the experience a ton better, would be to do hotkey-based completion. I'm sure you've seen it in lots of editors, but the idea is when you start typing `SEL` and hit the TAB key (or other configurable hotkey), the editor helps you out and completes `SEL` into `SELECT`. It'd be even better to allow completion for schema names, table names, field names and other things as well.

It's probably not an easy addition, or you'd have done it already, but it'd be awesome for sure.

Thanks!

**Comment by jakob** [comment]
Thanks for letting me know! This has already been requested; it's probably the most popular feature request for Postico.

I'm closing this issue since it is a duplicate. Original issue is #52
