### ISSUE TITLE
Always show SQL Query when searching for tables

### ISSUE THREAD

**Issue by dietervanhoof** [jakob/Postico#324]
When searching for tables, the 'SQL Query' item is used in the search as well. A QOL improvement would be so always show this, whatever you search for.

![image](https://cloud.githubusercontent.com/assets/13898980/22923973/b19a0a62-f2a3-11e6-837c-3fa0b1877ff8.png)

**Comment by jakob** [comment]
Good point. I've changed the behaviour of the filter so that it doesn't apply to the SQL Query item.

I'd appreciate it if you could test a prerelease build:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1593.zip

**Comment by dietervanhoof** [comment]
Seems to work just fine!
![image](https://cloud.githubusercontent.com/assets/13898980/22945376/54b89632-f2f4-11e6-9852-10bd557e3078.png)
Thanks so much for this, that was insanely quick! I'm assuming this couldn't possibly affect other features but I'll make sure to use this build in the upcoming days to see if anything goes wrong.

**Comment by jakob** [comment]
This specific change probably wont break anything, but the 1593 build also contains a few other fixes (see "what's new" in the help menu) and a lot of refactoring related to state restoration.
