### ISSUE TITLE
If a table is empty, an alert shows 'There are no rows on page 1. Displaying page 1 instead.'

### ISSUE THREAD

**Issue by dietervanhoof** [jakob/Postico#325]
**Version 1593**

![image](https://cloud.githubusercontent.com/assets/13898980/22966682/9a6928ee-f363-11e6-8252-4ecd57c0d9c7.png)

**Comment by dietervanhoof** [comment]
Should I be posting these as separate issues or rather as a comment somewhere? Or even some other way?

**Comment by jakob** [comment]
Ouch! How did I miss that!

This is related to issue #67, but in my opinion it's best to post separate issues if you are unsure where to post something. It's easier to cross-reference issues than it is to split issues.

**Comment by jakob** [comment]
Here's a build with a fix: https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1594.zip

**Comment by dietervanhoof** [comment]
Works fine. Thanks so much.
