### ISSUE TITLE
Indexes: add "Copy as SQL" button

### ISSUE THREAD

**Issue by thousandsofthem** [jakob/Postico#327]
Since plain old sql query for an index is gone in the latest release there are no way to copy any specific index (nor view it in its raw sql form). I'm (and thousands of other developers) surely more familiar with the standard sql notation.
Proposal: add "copy as sql" button for indexes along with graphical representation

relevant: https://github.com/jakob/Postico/issues/34

**Comment by jakob** [comment]
Thanks for your suggestion! I'm aware that the SQL view for the indexes is a necessary part that's currently missing, and I will add a way to view it again; but I still need a bit of time to do it.

**Comment by martinjankoehler** [comment]
Hi @thousandsofthem , good news!

We've posted a new developer build for this feature in the issue thread: https://github.com/jakob/Postico/issues/34

Please post your feedback there, we'll close this dupe.

Best regards,
Martin
