### ISSUE TITLE
Query failed when clicking foreign key cell in table view

### ISSUE THREAD

**Issue by stpe** [jakob/Postico#330]
When clicking a cell value in a column which is a foreign key to another table, the popup is not able to show that row in the table of the foreign key.

It fails with the following error:
```
Could not load table rows.
Query failed
PostgreSQL said: invalid input syntax for integer: ""
```

Screenshot:
https://dl.dropboxusercontent.com/u/20181/Screenshot%202017-02-27%2009.57.39.png

Happy to help debug it. (Is there an option to log/show the queries that Postico itself does?)

**Comment by jakob** [comment]
Oh... this is a problem with the filter. You probably filtered by id, and the next time Postico opened the popover it cleared the filter value; now it tries to search for `id = ''`.

I'll have to make Postico smarter about this. In the mean time, click the "Clear" button to clear the filter.

**Comment by jakob** [comment]
To answer your second question, there is no query log for Postico, but that would be very useful in some cases!

**Comment by stpe** [comment]
Ah, I see, now I understand why it behaves the way it does. Thanks for the quick reply and work-around.

Feel free to close this issue or turn into a feature request to make it smarter as you described.

**Comment by jakob** [comment]
I've fixed this in build 1705.

You can download a prerelease version here: https://eggerapps.at/postico/builds/
