### ISSUE TITLE
Be able to copy query time and numbers of rows returned

### ISSUE THREAD

**Issue by benoittgt** [jakob/Postico#334]
Hello

I would like to be able to quickly copy informations like rows count or timing of the query.

![capture d ecran 2017-03-03 a 15 05 55](https://cloud.githubusercontent.com/assets/8417720/23553870/ea324bbe-0022-11e7-9f51-21c2cc479d9b.png)

Thanks

**Comment by jakob** [comment]
I have made the row count & time elapsed labels in the SQL query view and in the table view selectable.

Please try a recent build from https://eggerapps.at/postico/builds/!

**Comment by benoittgt** [comment]
That's perfect. Thanks @jakob
