### ISSUE TITLE
Keyboard shortcuts for font size

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#335]
It would be convenient to be able to change font size with a keyboard shortcut, eg Cmd + and Cmd -.

(depending on first responder status either table view or SQL editor)

**Comment by ddrscott** [comment]
+1

**Comment by jakob** [comment]
I've added keyboard shortcuts for changing the font size (⌘+ and ⌘-) in build 1628.

You can download the latest development build from https://eggerapps.at/postico/builds/

**Comment by ddrscott** [comment]
Works exactly as expected. Thanks!
