### ISSUE TITLE
Feature Request: Export query results results to JSON

### ISSUE THREAD

**Issue by defkode** [jakob/Postico#338]
Export to CSV is handy, but in my work export of query results to JSON format is even more suitable.

**Comment by jakob** [comment]
Good point. There is the "Copy Special -> JSON" command which copies rows as JSON, but that is inconvenient for large tables.

**Comment by defkode** [comment]
I missed that possibility. This option is good enough for me. Thanks. Feel free to close this request.

**Comment by Andrew1431** [comment]
> Good point. There is the "Copy Special -> JSON" command which copies rows as JSON, but that is inconvenient for large tables.

Dopeeeeeeeee! Didn't know this existed and is exactly what i need!
