### ISSUE TITLE
Copy create table SQL

### ISSUE THREAD

**Issue by sul4bh** [jakob/Postico#34]
How about adding a 'copy create table SQL' in the context menu for a table please?

**Comment by sul4bh** [comment]
Something like this:
![_mysql_5_5_42__localhost_reporting_client_pending_and_copy_create_table_sql_ _issue__34_ _jakob_postico](https://cloud.githubusercontent.com/assets/109486/8810530/8afd38e8-2fbd-11e5-8341-1eaff0968c03.png)

![_mysql_5_5_42__localhost_reporting_client_pending](https://cloud.githubusercontent.com/assets/109486/8810478/3f56ab36-2fbd-11e5-9243-4d775b523e9e.png)
Sequel Pro also has a tab that displays table information.

**Comment by jakob** [comment]
That would definitely be a useful addition. I have this feature planned for the future, but it's a bit more difficult to implement on Postgres compared to MySQL.

Background: Unlike MySQL, PostgreSQL has no server side function for querying the CREATE syntax. To implement such a feature, I'd need to recreate it from the pg_catalog tables. Since this is a complex task, I'd prefer to use an existing implementation (from pg_dump) to avoid inaccuracies. Bundling pg_dump is probably the best way to achieve this.

Since this is a bit complex, I have to postpone this feature a bit.

**Comment by basicinside** [comment]
Maybe i'm missing sth., but shouldn't a simple query like
```CREATE TABLE table_copy AS (SELECT * FROM table);``` allow this?

**Comment by jakob** [comment]
@basicinside That command would copy the table, but it won't give you the SQL command to create the table. People might want the SQL for a variety of reasons. For example you might want to set up a similar table on a different server, then you need some way to get the CREATE TABLE command.

**Comment by LauLaman** [comment]
+1

**Comment by eyeman2006** [comment]
+1

**Comment by jspeis** [comment]
+1

**Comment by mayankpantgithub** [comment]
+1

**Comment by captify-afilimonov** [comment]
+1

**Comment by dietervanhoof** [comment]
+1

**Comment by blainerothrock** [comment]
+1

**Comment by radcliff** [comment]
+1

**Comment by macarthy** [comment]
+1

**Comment by macarthy** [comment]
What about

` pg_dump -t 'aschema.atable' --schema-only database-name`

**Comment by colegleason** [comment]
+1

**Comment by miketwalker** [comment]
+1

**Comment by thom-ek** [comment]
Same for creating views.

**Comment by jonasarts** [comment]
+1

**Comment by gerhat** [comment]
+1

**Comment by jong-eatsa** [comment]
+1

**Comment by rohanc** [comment]
This is the one feature that has me hopping back to pgAdmin III all the time.  That app provides the functionality when you right-click on the table name, choose Scripts and then, "CREATE script".

**Comment by ivosabev** [comment]
+1

**Comment by hwsoderlund** [comment]
+1

**Comment by dpanzer** [comment]
Quick point in regard to @basicinside 's solution - when you create a table in this fashion, indexes do not get copied so you'll need to recreate primary keys etc

**Comment by mergenchik** [comment]
+1

**Comment by pboese** [comment]
+1

**Comment by Hormold** [comment]
+1

**Comment by sozorogami** [comment]
+1

**Comment by refrigerator** [comment]
+1

**Comment by rredkovich** [comment]
+1

**Comment by sepehrvakili** [comment]
+1

**Comment by jens-nedal** [comment]
+1 !!

**Comment by martinjankoehler** [comment]
Hi folks, good news!

We have been working on this issue!

Related changes:
- Added new DDL navigation item, which displays the CREATE TABLE SQL
- Segmented control now contains three choices: Content / Structure / DDL
- 'Navigate' menu now contains menu items for switching between views, Option-Command-T now cycles through all three

Download Build [B2608](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2608.zip), or check out the [list of recent builds](https://eggerapps.at/postico/builds/).

Best regards,
Martin

**Comment by jakob** [comment]
BTW, currently latest build with the DDL view is [2609](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2609.zip), not 2608. (the build failed for some reason, I re-triggered it)

**Comment by otto-md** [comment]
Very nicely done. Thanks!

**Comment by sul4bh** [comment]
I tested the latest build with AWS Redshift. It works flawlessly. Awesome job.

**Comment by sepehrvakili** [comment]
@martinjankoehler sweet, thanks!

**Comment by martinjankoehler** [comment]
Hi,

please download **Release Candidate** Build [2668](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2668.zip), or check out the [list of recent builds](https://eggerapps.at/postico/builds/).

Please report any issues, if any.

The build contains the latest fixes from master (foreign key issue, et cetera).

Best regards,
Martin

**Comment by jakob** [comment]
DDL View is now released in Postico 1.4!

**Comment by leebickmtu** [comment]
When looking a DDL of a view it seems to get double semicolons on the end.
