### ISSUE TITLE
Tabbed Interface for SQL Queries.

### ISSUE THREAD

**Issue by barrycenter** [jakob/Postico#340]
I really like Postico but I find myself limited with just one window for editing SQL queries. Especially when I'm writing several different versions of stored procedures. 

I know I can open multiple windows but they become unwieldy to manage since they all have the same name. Ideally, I'd like to have tabs, like in a web browser, to allow me to select between multiple pages of queries. Then, each tab could have a separate query starting at line one matching the error messages.

Ideally, each tab would be contextually mapped to the command-S keyboard shortcut for saving as well (does this keyboard shortcut work anywhere in Postico?) so I don't habitually hit command-S, only to later discover that nothing was actually saved.  :)

**Comment by jakob** [comment]
Postico has supports for tabs (press cmd-T to open a new tab), but it requires macOS 10.12 or later. 

In the most recent build 2268 I've improved Autosaving behavior of Postico: Queries are now saved per tab (as files inside the Application Support directory), and restored automatically when you open tabs again.

It's not perfect yet, but it seems to me that Postico is now pretty close to what you were describing.

(Apologies for not responding sooner; the amount of issues posted on Github is overwhelming)
