### ISSUE TITLE
rows per page preference ignored

### ISSUE THREAD

**Issue by roovo** [jakob/Postico#35]
If I set this to something else (say 100) I still get back the default 1000 rows.

Also after quitting the app, it's set back to 1000

And thanks for the app btw - very useful and nice to use :)

**Comment by jakob** [comment]
I just investigated this. It looks like you need to press enter after typing a value to make sure the changes take effect.

I'll make sure to change this so that closing the window (or switching to a different window) also makes the changes take effect.

**Comment by roovo** [comment]
Brilliant - thanks jakob - I can confirm that pressing enter does indeed persist the changes :)

**Comment by jakob** [comment]
I've fixed the issue in verison Postico v0.26. Pressing enter is now no longer necessary!

**Comment by roovo** [comment]
brill - thanks jakob - just installed and looking good - much appreciated
