### ISSUE TITLE
Re-evaluate using Sparkle for automatic updates

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#351]
While Postico does automatically check for updates, it does not automatically update itself, requiring users to manually download and install new versions. This is a bit inconvenient, and as a consequence, a lot of users are using outdated versions of Postico.

When I last evaluated using the Sparkle framework for automatic updates, it was not really usable for sandboxed apps. Apparently there is a branch now that supports sandboxed apps. I have to see if this is suitable for use with Postico.

**Comment by swrobel** [comment]
Auto-updates would be great! Is there really nothing better than Sparkle these days?

**Comment by jakob** [comment]
I've just finished reading through the epic [Sparkle Sandbox thread](https://github.com/sparkle-project/Sparkle/issues/363). It looks like **zorgiepoo** has rewritten Sparkle to support sandboxed apps, and maybe that branch might end up becoming the next version of Sparkle.

**Comment by jakob** [comment]
I've looked a bit through the code of the new Sparkle branch. The new version is huge and pretty complex. It seems that not very many people are using it, and the original author of the branch can no longer contribute as he is now working for Apple. So it could take a long time until the new branch of Sparkle will be ready....

I could of course use the new branch before it is officially released, but I really don't want to be one of the first people to use the new Sparkle branch. Then I would probably end up finding and fixing all the bugs.

So for now, I've decided not to use Sparkle for updates, and focus on more important updates to Postico.

Sorry.

**Comment by natanrolnik** [comment]
@jakob I love Postico, just purchased the full version via website.

Couldn't you add Sparkle only when it's build not for the AppStore? I mean, two configuration modes. Doing manual updates is substantially more complicated, and sparkle is the "default" in almost all good macOS apps out there ([Reveal](https://revealapp.com), [Transmit](https://www.panic.com/transmit/), [Paw](https://paw.cloud), Evernote).

Pretty please 🙏

**Comment by jakob** [comment]
@natanrolnik We'll probably adopt Sparkle in a future version (I get complaints about the update process every time we release a new version). But I can't make any promises regarding when. We're working on a few tricky things right now, and while I'm aware that auto update is currently inconvenient, I want to get a few other things out the door first.

**Comment by ehamberg** [comment]
In case anyone doesn't know this, I'll just mention that it's possible to install and update Postico through [homebrew-cask](https://github.com/Homebrew/homebrew-cask), too.

To install:

    brew cask install postico

To upgrade:

    brew cask upgrade

**Comment by jakob** [comment]
@ehamberg  Good point! Thanks a lot to whoever created the Postico cask (and keeps it up to date)

**Comment by swrobel** [comment]
Wait, does cask upgrade actually upgrade binaries now?!

**Comment by ehamberg** [comment]
@swrobel: It does! The future is here!
