### ISSUE TITLE
Drop down for type field in structure view

### ISSUE THREAD

**Issue by jdub** [jakob/Postico#355]
Would be lovely to have a drop down for types in the structure view, mainly so I don't have to remember the names of all the types PostgreSQL supports. 😄

Bonus points:
- show only types that are supported by the server you're connected to (given different PostgreSQL versions, Redshift, etc.)
- combo box (sorry, old Windows term) so you can type whatever you want even if it's not in the list

Thanks -- I'm on my first day of having fun with (beautifully designed) Postico, and will probably buy it soon.

**Comment by jakob** [comment]
Thanks for the suggestion. These are very good points.

I'm closing this issue because a similar request has been made before: #113

**Comment by maisnamraju** [comment]
Any plan to do this ? This is one thing that is really lacking in postico
