### ISSUE TITLE
Scrollbar visual glitch

### ISSUE THREAD

**Issue by dsego** [jakob/Postico#365]
This is really a nitpick. Some even/odd striping is showing in the sidebar when dragging the scrollbar. 
Version 1.1.2 (1619)
MacOS 10.12.4

<img width="229" alt="screen shot 2017-04-06 at 4 50 22 pm" src="https://cloud.githubusercontent.com/assets/578557/24760519/30222780-1ae9-11e7-9ec9-455e699f7b4c.png">

**Comment by jakob** [comment]
Took me a bit to track this one down, but changing the text color to a literal value instead of the default control text color seems to fix it. I still need to test if this breaks anything else, but I hope that it should be fixed in the next release.

**Comment by jakob** [comment]
So changing the text color did not work (caused the same glitch on 10.10).

I managed to fix it by subclassing NSOutlineView and overriding allowsVibrancy to return true. This now works on both macOS 10.10 and 10.12.

You can download build 1641 or later; it should be fixed now.
https://eggerapps.at/postico/builds/
