### ISSUE TITLE
"IS DISTINCT FROM"-Filter

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#368]
`IS DISTINCT FROM` should be available as a filter. I can't really think of a use for `IS NOT DISTINCT FROM` over the available filters `IS NULL` and simple equality.

**Comment by jakob** [comment]
I've replaced the "is not exactly" with "is distinct from", since having both seems confusing to me (and "is distinct from" works more like one would expect)

The new filter is in build 1705
https://eggerapps.at/postico/builds/
