### ISSUE TITLE
Option to export query results with different formats

### ISSUE THREAD

**Issue by ottob** [jakob/Postico#37]
Right now the only option is csv format like this:
```
"guideid","icd","count"
20,"M545",2
20,"M546",1
```
But this can not be imported into Numbers without extra conversion. But with semicolons it works:
```
"guideid";"icd";"count"
20;"M545";2
20;"M546";1
```

Tab separated values in a `.tsv` file also seem to import with drag and drop. So some kind of control over the export format would be nice.

**Comment by jakob** [comment]
In Postico v0.22 I added settings to change the export CSV format. When you choose "Continental" from the popup, Postico will generate a CSV file suitable for European countries (with semicolon as column separator, and comma as decimal separator)

![CSV Export options](https://cloud.githubusercontent.com/assets/198305/8976437/fef0f886-368c-11e5-83bc-b8ebb91c4289.png)

**Comment by jakob** [comment]
Also, the quickest way to get data into Numbers is to just use copy & paste!

**Comment by ottob** [comment]
Great, I didn't read the fine print of the "Continental" setting. That works for me.
