### ISSUE TITLE
Add ability to alter column position

### ISSUE THREAD

**Issue by gajus** [jakob/Postico#370]
There appears to be no way to change the column order.

https://sequelpro.com/ (a MySQL client) allows to change column order.

It would be a nice feature to have.

**Comment by jakob** [comment]
Unfortunately reordering columns is not easily possible in PostgreSQL. That's the one advantage MySQLhas over PostgreSQL :)


See this link for more info
https://wiki.postgresql.org/wiki/Alter_column_position

**Comment by gajus** [comment]
I read the wiki prior to raising the issue. I understand the complexity.

I've raised the issue more to keep track of it rather than expecting this to become a feature overnight.

**Comment by jakob** [comment]
Thanks for your comments, but I'm going to close this issue now. There is no way that I am going to implement one of the workarounds from the Wiki in Postico -- all of them are too complicated for the general case, when you might need to update views, foreign keys, procedures etc....

As soon as PostgreSQL supports reordering columns, I'll add the feature to Postico as well.

If you want to raise awareness for this issue, post to the PostgreSQL mailing lists!

**Comment by jakob** [comment]
I just wanted to mention that Postico does have a way to change column order on the cluent side. You can drag column headers in the table content view to rearrange columns. Postico remembers column positions. There's just no way to do it in sttucture view, since PostgreSQL doesn't allow changing column order.

**Comment by DiegoRBaquero** [comment]
@jakob Holy polly, that's so useful! Thank you so much!

**Comment by CreepGin** [comment]
@jakob I think it'll be a great feature for the structure view to also handle re-ordering client-side.
