### ISSUE TITLE
Respect existing indentation [sql editor]

### ISSUE THREAD

**Issue by gajus** [jakob/Postico#372]
If I am editing a query that contains two-spaces, 4-spaces or tabs as indentation, then using TAB key in the query editor should use the identified indentation. It appears that now it simply uses tabs all the time.

**Comment by jakob** [comment]
You can select spaces or tabs in the preferences.

**Comment by gajus** [comment]
A lot of IDEs support indentation auto detection.

https://www.sublimetext.com/docs/2/indentation.html

It is fairly basic feature, though it is a nice to have.

Regardless, for my use case preference setting is enough. Thank you.
