### ISSUE TITLE
Disable ESC shortcut while editing

### ISSUE THREAD

**Issue by ddrscott** [jakob/Postico#379]
The `<esc>` shortcut while editing has some strange behaviour. I propose dropping it altogether or binding the behaviour to a different key.

When `<esc>` is typed on an empty line, it adds a capital `I`. When I hit it again because I don't want an `I`, the letter doesn't go away. I'm forced to `<delete>` it away.
When I type "select" then `<esc>`, it word completes to "selecting". When I hit `<esc>` again, the "ing" autocompleted "ing" goes away (which is what I would expect).

It would be nice if the behaviour was consistent. Hitting `<esc>` twice would have the same output as never hitting `<esc>`.

Also, as a heavy hitter of `<esc>` as a force of habit (from Vim), it's annoying for anything to happen at all, which is why I would propose for the behaviour to be moved some where else or configurable.

![postico-esc](https://cloud.githubusercontent.com/assets/1975119/25503564/7b416bf4-2b60-11e7-9a9c-bba94a241a38.gif)

Anyone else having the same issues?

**Comment by jakob** [comment]
Good point. This is Apple's built-in autocomplete, which is useless in the query view case. I've already disabled it in most text fields; looks like I need to look through the UI and remove it everywhere.

**Comment by ddrscott** [comment]
Wasn't sure how to Google it, but I found the setting on Mac.

https://discussions.apple.com/thread/7311015?start=0&tstart=0
```
#!/bin/bash
defaults write -g NSUseSpellCheckerForCompletions -bool false
```
Feel free to close the ticket or keep it open if you want to disable it for the text control.
Note, auto suggest behaviour is also occurs in `Preferences -> Rows per page:`

**Comment by jakob** [comment]
@ddrscott Thanks for providing the workaround, but I do consider this a bug in Postico :)

I'll go through all the fields in Postico and disable it everywhere. I really see no point in this feature (escape should probably mean "cancel editing" in most text fields, and do nothing in the query text view)

**Comment by jakob** [comment]
I've investigated this issue, and discovered that Apple has actually changed the default keyboard shortcut for the "complete:" command from Esc to F5 in macOS 10.12. This means that this issue should only affect people on 10.11 and earlier.

Nevertheless, I've started to address this issue. The [latest build](https://eggerapps.at/postico/builds/) disables completion in the SQL Text View, in the preferences window, and in the page selection field.

TODO: 
- [ ] Favorites Window
- [ ] Filter Bar
- [ ] Table Structure Editor 
- [ ] test on older versions of macOS

**Comment by ddrscott** [comment]
Guess that means I should upgrade OSX. I'll save that for another day.

<img width="698" alt="about_mac" src="https://cloud.githubusercontent.com/assets/1975119/25616335/9a71959a-2f01-11e7-8d25-de87d80df292.png">

Thanks for the updates!

**Comment by jakob** [comment]
Blargh... finally done with this issue. ESC now no longer triggers auto-complete, and aborts editing in text fields as expected, even on older versions of  OS X.

In my testing on 10.10 and 10.12 everything seems to work now -- you can now even dismiss the filter bar with ESC (I guess this should have been the standard behavior from the beginning...)

I'd appreciate it if you could download a [recent build](https://eggerapps.at/postico/builds/) and try if it works as expected now!

**Comment by ddrscott** [comment]
Works great so far. I even undid the OS X setting to make sure.

Thanks!
