### ISSUE TITLE
Allow Changing Font Size

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#38]
It should be possible to change the fonts and font sizes used.

There probably need to be settings for two fonts:
- "Data font" used in Table View
- "SQL font" used in Query View etc.

**Comment by markbatbean** [comment]
+1

(paid license)

**Comment by radim** [comment]
+1

**Comment by wellsoliver** [comment]
+1 !!!

**Comment by Teggy** [comment]
I strongly support this request.  Changeable font size would allow me to use Postico in a classroom setting (rooms with 20+ rows calls for adjustable/large fonts).

**Comment by ear** [comment]
Yes please!

If adding it somewhere in the UI is a bit of a pain and is blocking the issue then I suggest to just make it a `defaults` option. I think it would be alright for people who care (and/or have problems reading the tiny font right now.) You can always add the UI afterwards.

:heart:

**Comment by jakob** [comment]
Adding an option in the preferences is not the problem... The problem is that the table view uses a highly optimized cell for text drawing, which is has a fixed font size. I will need to do a bit of refactoring to allow changing the font size.

**Comment by ear** [comment]
Would it be possible, in the meantime, to have an option at least for the `SQL Query` textview?

That would go a long way to help with readability. Also thank you for the incredibly fast response.

**Comment by ear** [comment]
If it can be of any help: I think the way Chrome does it, with the subtle appearance of small overlay arrows upon sliding left and right is less disconcerting than having the whole view slide out just when you were trying to scroll horizontally. You get a visual clue that you can backtrack from without visual distress.

I suppose this is not what users of Safari are accustomed to, but I think it's a rather good design. (On the other hand you still can't zoom the Safari developer tools—what is up with *that*? :see_no_evil:)

**Comment by jakob** [comment]
Good point @ear 

Here's a build that lets you change the font size in the sql text view:
https://eggerapps-downloads.s3.amazonaws.com/postico-1249.zip

**Comment by ear** [comment]
Oh wow… thank you very much!

**Comment by Teggy** [comment]
This tipped me over.  Bought a license. ;-)

**Comment by hwsoderlund** [comment]
+1 Any idea when this might make it into a "real" release?

**Comment by jakob** [comment]
@hwsoderlund 
- Changing SQL Query Font size was released in 1.0.1 (Nov 23rd)
- I'm working on changing table view font size.

**Comment by hwsoderlund** [comment]
I am on 1.0, build 1243. But when I do "check for updates" I get no notifications about 1.0.1.

**Comment by hwsoderlund** [comment]
Anyway, downloaded 1.0.3 manually now. Thanks!

**Comment by jakob** [comment]
Hi everyone! I've now added a preference for changing the font size in the table view as well. Unfortunately the preferences dialog ended up pretty messy now, I think I still need to redesign that.

Anyway, here's a link to a nightly build that lets you change table view font size:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1309.zip

I'd love to hear if this does what you expect. Right now, the font size of the headers doesn't change. Does that matter, or would you prefer the header to have the same font size as the content?

**Comment by jakob** [comment]
I've now redesigned the prefs dialog. I consider this feature completed now -- if you have any further input, let me know!

Prerelease:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1334.zip

**Comment by ear** [comment]
This is fantastic :clap:

I wanted to comment about the big amount of whitespace around the text in the rows (but I did not understand it was because you fit more lines into it!) Letting one choose the number of lines displayed per row is very graceful.

Do you think you'll add font face options as well for the query and rows? For some kind of data it could be handy to have a monospace option.

All in all awesomely done.

**Comment by Teggy** [comment]
Finally.  Awesome, Jaokb!  👍🏼

**Comment by bleonard33** [comment]
You briefly mentioned it in the initial comment, but being able to change the font used in TableView (particularly to a fixed width font, even if that's the only option) would be useful. Normally the current view is way nicer to use than any other Postgres client that uses fixed width fonts, but being able to compare character by character with fixed width is much easier when the need arises. Not a huge problem but would be nice to have as an option along with font size!

**Comment by jakob** [comment]
I've just added a preference to use a fixed width (monospace) font for the table view!

I'd appreciate it if you could test a prerelease build:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1593.zip

**Comment by ear** [comment]
Fiddled around a bit with a number of tables and the initial impression is that it is pretty solid! Good work.

**Comment by tagspace** [comment]
Hey Jakob.  I use Postico (paid version) to teach SQL at a school here in Berlin.  The font-size changes have made a huge difference to being able to see everything clearly on a classroom screen.

Is there any way make the column headers also increase with size when the table font size increases?
