### ISSUE TITLE
Feature Request: Command+Option+Arrow to switch tabs

### ISSUE THREAD

**Issue by innonate** [jakob/Postico#381]
Would love a key command (command, option, arrow key would follow Chrome conventions) to switch tabs.

**Comment by jakob** [comment]
The keyboard shortcut is Ctrl-Tab. I don't think I actually chose that, I think it's the system default. Why Chrome has a different shortcut is beyond me.

PS: Find keyboard shortcuts by looking at menu items.

PPS: Change keyboard shortcuts by going to System Preferences -> Keyboard -> App Shortcuts
