### ISSUE TITLE
Query Time?

### ISSUE THREAD

**Issue by bendavies** [jakob/Postico#384]
Hey,

I was just trying to debug why a query time on my local postgres instance was 1ms, but reported to take 200ms on a production database.

I was very worried about the state of my production database until i realised that the query time reported by postico is actually the round trip time from the server?

Is there any way to actually display the query time, or both?

Thanks

**Comment by jakob** [comment]
Yes, that time does include the network round trip time.

If you want precise timings, use EXPLAIN ANALYZE

**Comment by bendavies** [comment]
indeed, that's how i got the real execution time :) thanks

**Comment by jakob** [comment]
(For normal queries, the server doesn't report execution time, so all Postico can do is measure the total time including network round trip time)
