### ISSUE TITLE
CLI support for favs

### ISSUE THREAD

**Issue by noma4i** [jakob/Postico#389]
Hi! Im happy with Postico at most but there is a small feature request to extend existing command line support:

- Ability to have cli support like `open postgres+fav://%fav_name%`

Iv done that kind of shortcut piggyback by automator and that's not reliable and slow :(

**Comment by sebyddd** [comment]
+q

**Comment by sebyddd** [comment]
+1

**Comment by jakob** [comment]
We've recently made some improvements to favorite URLs. You can now use a command like this to open favorites by name:

```bash
 open 'postico://?nickname=My+Connection+Favorite'
```

Full docs are here: https://eggerapps.at/postico/docs/v1.5.6/postico-url-scheme.html

Is that what you are looking for?

**Comment by noma4i** [comment]
Yes YES YES!
