### ISSUE TITLE
New table should go to current schema

### ISSUE THREAD

**Issue by gintsmurans** [jakob/Postico#39]
Clicking second click on a table **from the navigation sidebar** and clicking on the new table, that new table is created in public scheme, not the table's scheme, the click was made on.

**Comment by jakob** [comment]
I think I've fixed this issue already in the latest development build:
[Postico 2015-07-31](https://eggerapps-downloads.s3.amazonaws.com/postico-2015-07-31.zip)

**Comment by gintsmurans** [comment]
Yup, it also shows new table on the navigation list. :+1:
