### ISSUE TITLE
Multitab switching hotkeys

### ISSUE THREAD

**Issue by mrkcohen** [jakob/Postico#391]
I'm on macOS Sierra which natively supports a tabbed interface.  This alone has made my life in Postico much easier, with the ability to quickly navigate multiple Postgres sessions.

One feature that would be awesome--similar to browsing multiple tabs in an app like Google Chrome for example--is ⌘+ [n], where n = tab number one wishes to quickly navigate to.

Thanks for the consideration!

**Comment by jakob** [comment]
Good idea. Both Chrome and Safari use this shortcut by default, so I guess many people expect this shortcut. I've added the shortcut in revision 1736.

You can download a prerelease build from this website: https://eggerapps.at/postico/builds/
