### ISSUE TITLE
Bug with Magic Mouse Gestures on macOS High Sierra

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#397]
A customer has reported that Magic Mouse / Trackpad gestures cause Postico to get stuck in the beta version of macOS High Sierra.

As a temporary workaround, you can disable mouse / trackpad gestures in Postico preferences.

**Comment by Ashtonian** [comment]
+1

**Comment by jakob** [comment]
Short update: I was able to reproduce the issue a couple of days ago, and I've determined that this is a bug in the High Sierra Beta. NSPageController is simply broken in the beta.

I've reported the bug to Apple, and I hope that they fix it soon.

**Comment by jakob** [comment]
I haven't heard back from Apple, but it looks like this issue has been fixed in Beta 3 -- at least it now works on my test machine.

Could anyone else confirm?

**Comment by Ashtonian** [comment]
I re-enabled mouse gestures and its not freezing - so I'm assuming its working.  :)
