### ISSUE TITLE
Issue when dropping view and then create another view with same name

### ISSUE THREAD

**Issue by mclaeysb** [jakob/Postico#398]
When I drop a view, and immediately after create a new view with the same name but different SQL definition, then it takes the SL definition from the first view.

Not shure if it's only me or if others also have this problem?

I'm doing this often, e.g. creating views called 'temp' to do some quick edits during which I only want to see a certain selection of columns (as a workaround for #236).

**Comment by jakob** [comment]
Thanks for the bug report! There was an error in the logic that invalidates cached table & view information. I've fixed the problem in build 1711 (download [here](https://eggerapps.at/postico/builds/))

The new version should work if you use the UI to delete the view. If you delete & replace the view in a SQL script, Postico won't detect it, and you'll still have to refresh manually.

**Comment by mclaeysb** [comment]
Awesome, thanks!
