### ISSUE TITLE
Change filter hotkeys

### ISSUE THREAD

**Issue by teckays** [jakob/Postico#399]
As a full-time daily user I'd prefer the filter command to be bound to <kbd>⌘</kbd><kbd>F</kbd> instead of <kbd>⌥</kbd><kbd>⌘</kbd><kbd>F</kbd> as it makes it a lot more easier to use with one hand.

**Comment by jakob** [comment]
Unfortunately Cmd-F is already used by "Find (and replace)" in the SQL View. 

However, you can change the keyboard shortcut on your Mac in System Preferences -> Keyboard -> Keyboard Shortcuts -> App Shortcuts.
