### ISSUE TITLE
Find greyed out

### ISSUE THREAD

**Issue by super-cache-money** [jakob/Postico#400]
![image](https://user-images.githubusercontent.com/1463145/28195235-6b43cbf4-6849-11e7-96a7-e74052db5d6b.png)

And - I have a paid license.

**Comment by jakob** [comment]
Hi!

„Find“ is for searching/replacing text in the SQL query view.

You are probably looking for the „Filter“ command? (Shortcut is cmd-option-F.)

Jakob
