### ISSUE TITLE
Explain how to activate license somewhere

### ISSUE THREAD

**Issue by daviestar** [jakob/Postico#404]
My boss bought me a license for Postico and sent over the file to me (just a `.postico-license` file) and I spent far too long figuring out what to do with it!

For those wondering, just drag the file onto the Postico icon on the dock.

Cheers.

**Comment by jakob** [comment]
Not sure what to do about this.

1. There is an “Activate…” button in the favorites window
2. You can double click the license file
3. You can drag the license file on the icon in the dock or in the finder icon

In addition to this, the email with the license file has instructions how to activate Postico.

If you have any suggestions for improvement, I’d loce to hear them.

Would an “Activate…” button in the nag dialogs help?

**Comment by daviestar** [comment]
Yes, definitely appreciate my boss could have sent any accompanying docs!

I think what confused me is I'd not used (or seen before) the favourites panel while using the demo.

I'd expect to see an `Activate License...` menu item under `Help` or `Postico` menus, or somewhere in `Preferences...`, or even in the `About Postico...` window.

Loving Postico so far, keep up the good work.

Thanks,

Dave

**Comment by daviestar** [comment]
PS.  Or just write somewhere on your website that you can double-click the file, or drag it onto the dock icon 👍

**Comment by jakob** [comment]
I’m going to reopen this so I remember to do something about it

**Comment by jakob** [comment]
OK, I made it more obvious how to activate Postico. All nag dialogs now have an "Activate License…" button, and I've added an "Activate License…" menu item to the help menu.

**Comment by dongri727** [comment]
When I click activate button, finder window open and it say "Please select a Postico license file. PG Commander license files purchased after Sept 1, 2014 are also valid." but I can't the file anywhere

**Comment by jakob** [comment]
Postico 1.x uses license files

Since that was confusing, I switched to license keys in Postico 2.0.

If you have a license key, you purchased Postico 2.x, and you need to make sure you download Postico 2.x
