### ISSUE TITLE
Release Candidate for Postico 1.2

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#409]
I'm planning to release Postico 1.2 on Friday, August 4th.

You can download the release candidate here:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1.2.zip

## Free license for bug reporters
As a little thank you for beta testers, I'll offer a free license for Postico to everyone who finds a bug or regression in the release candidate for version 1.2 before the release. If you already have a license, you can give it to someone else! The reported issue must be reproducible and it must not have been reported before (fastest reporter wins).

## Changelist for Postico 1.2:

<h3>New Features</h3>
		<ul>
			<li>
				<b>Keep Connection Alive</b>: Postico now periodically sends a command to the server to ensure that the connection isn't terminated by a firewall or similar.
				This setting replaces the "Disconnect Automatically" function, which did not work reliably when using temp tables or changing settings like the search path.
				<a href="https://github.com/jakob/Postico/issues/310">#310</a>
			</li>
			<li>
				<b>Restore session settings</b>: Postico now remembers session settings (like time zone, datestyle, search path) and restores them after reconnecting when the connection was lost.
			</li>
			<li>
				The new <b>SQL Preview button for filters</b> lets you display the SQL generated by Postico
				<a href="https://github.com/jakob/Postico/issues/61">#61</a>
			</li>
			<li>
				Postico now displays partitioned tables (introduced in PostgreSQL 10)
			</li>
			<li>
				Postico can now display Redshift Spectrum tables
				<a href="https://github.com/jakob/Postico/issues/382">#382</a>
			</li>
			<li>
				Switch between tabs with ⌘1 to ⌘9
				<a href="https://github.com/jakob/Postico/issues/391">#391</a>
			</li>
		</ul>
		<h3>Improvements</h3>
		<ul>
			<li>
				I added an "is distinct from" filter, and removed "is not exactly" to avoid confusion.
				The difference is that the former includes NULL values while the latter does not.
				<a href="https://github.com/jakob/Postico/issues/368">#368</a>
			</li>
			<li>
				Filters with blank fields are now ignored.
				There is now a new filter that searches for empty strings.
				<a href="https://github.com/jakob/Postico/issues/330">#330</a>
			</li>
			<li>
				Made row count &amp; elapsed time selectable
				<a href="https://github.com/jakob/Postico/issues/334">#334</a>
			</li>
			<li>
				Added keyboard shortcuts for changing the font size (⌘+ and ⌘-)
				<a href="https://github.com/jakob/Postico/issues/335">#335</a>
			</li>
			<li>
				More consistent handling of the ESC key:
				<ul>
					<li>ESC now means "Revert Changes" in most text fields</li>
					<li>ESC no longer triggers System Autocomplete <a href="https://github.com/jakob/Postico/issues/379">#379</a></li>
					<li>ESC dismisses the filter bar &amp; page selector</li>
				</ul>
			</li>
			<li>
				Reloading no longer collapses schemas
				<a href="https://github.com/jakob/Postico/issues/102">#102</a>
			</li>
			<li>
				⌘↩ now applies filters in the table view
				<a href="https://github.com/jakob/Postico/issues/313">#313</a>
			</li>
			<li>
				Foreign keys are now editable
				<a href="https://github.com/jakob/Postico/issues/264">#264</a>
			</li>
			<li>
				Made it more obvious how to activate Postico. All nag dialogs now have an "Activate License…" button, and I've added an "Activate License…" menu item to the help menu.
				<a href="https://github.com/jakob/Postico/issues/404">#404</a>
			</li>
		</ul>
		<h3>Bugfixes</h3>
		<ul>
			<li>
				Fixed an issue that prevented pasting into the SQL Query View
				<a href="https://github.com/jakob/Postico/issues/244">#244</a>
			</li>
			<li>
				Fixed an issue where the Open Quickly command searched the wrong database
				<a href="https://github.com/jakob/Postico/issues/363">#363</a>
			</li>
			<li>
				Fixed minor display issues
				<a href="https://github.com/jakob/Postico/issues/281">#281</a>
				<a href="https://github.com/jakob/Postico/issues/365">#365</a>
			</li>
			<li>
				Fixed a problem where the detail sidebar always showed "no row selected"
				<a href="https://github.com/jakob/Postico/issues/336">#336</a>
			</li>
			<li>
				Fixed a problem when reloading a relation that changed type (eg. view -> table)
				<a href="https://github.com/jakob/Postico/issues/146">#146</a>
			</li>
			<li>
				Postico now sets the extra_float_digits parameter to 3 when connecting to the server.
				This ensures that no information is lost when transmitting float or double values.
				If setting the parameter to 3 fails (server older than 9.0), Postico falls back to extra_float_digits=2
				<a href="https://github.com/jakob/Postico/issues/289">#289</a>
			</li>
			<li>
				Fixed an issue where Postico showed old data when a table or view was replaced with a new one of the same name
				<a href="https://github.com/jakob/Postico/issues/398">#398</a>
			</li>
			<li>
				Truncating multiple tables now works on old PostgreSQL servers and Redshift.
			</li>
		</ul>

**Comment by BenderV** [comment]
For me, the application crash when I'm trying to "connect" to a db. https://gist.github.com/BenderV/279122266c9fa3b6486e6da0683ab54d

**Comment by jakob** [comment]
@BenderV Thank you very much for the crash report! The problem was the OS version. (I don't have a touch bar Macbook yet either...)

I've fixed the issue in release candidate 2. ([download](https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1.2.zip))

Email me and I'll send you a free license!

**Comment by jakob** [comment]
Done! I just released [Postico 1.2](https://eggerapps.at/postico/docs/v1.2/changelist.html).

Download directly from the [Postico homepage](https://eggerapps.at/posico/)

The Mac App Store version should also be live in a few hours (as soon as Apple is done with the review)
