### ISSUE TITLE
Save in Keychain does not work with same user on different hosts

### ISSUE THREAD

**Issue by mcb** [jakob/Postico#41]
Currently the 'Save in Keychain' function saves a password for a given user. However if you have the same user with a different password running on different hosts (e.g. we open up ssh connections through jump hosts that cannot be done in postico itself) it uses the last saved password from keychain. 

Possibly it would be better to save a password based on the nickname and user or implement this differently as it is extremely annoying always to hit connect only to find out the password was the one for the wrong host.

Thanks @jakob !

**Comment by jakob** [comment]
Not sure I understand correctly. Do you have multiple favorites with the same user and hostname, but different passwords?

Aside from that, I'm not sure I understand why you don't use Postico's built-in SSH tunneling?

**Comment by mcb** [comment]
I do have several instances of Postgres running on my local machine, running at different ports with same users and different passwords.

Aside from that we do have a vpn, where postico appears to not connect as it always hangs whenever I use the correct hostname which works through ssh (standard ports) which is why we map these to other ports additionally to the ones that are running locally.

For both the same problem persits, the password seems to be mapped to the user alone and as such it is not possible to have more than one password saved.

**Comment by jakob** [comment]
If I understand correctly, everything should work fine in your case, so there must be some bug in Postico.

Postico stores passwords in the keychain using user, host, and port. (If you use the built in SSH tunnels, they additionally take SSH user, SSH host and SSH port into consideration)

Postico will get confused when you have multiple favorites with the same host, port, and user name, but different passwords. Is this the case with your setup?

If not, could you check in Keychain Access if there is an issue with the passwords? Just search for "postgresql" to find the passwords stored by Postico.

I've seen rare glitches with the keychain when adding/modifying many items quickly. A way to fix these temporary glitches would be to quit Postico, remove passwords from the keychain using Keychain Access, and then adding them again in Postico.

**Comment by mcb** [comment]
@jakob thank you for your clarification. I removed all entries with postico inside the keychain and it seems like there has been an issue around this as it now creates them differently with ```postgresql://localhost (username)``` 

This fixes my problems, so I will close this issue. Thanks for help.
