### ISSUE TITLE
Connection info window is not scrollable

### ISSUE THREAD

**Issue by dsego** [jakob/Postico#413]
I noticed when clicking on the little TLS badge, the window that pops up with detailed information fills my small 13" screen top to bottom, but the content is not scrollable.

![connection](https://user-images.githubusercontent.com/578557/28984109-a6761956-795c-11e7-9168-fba8b663f020.gif)

**Comment by jakob** [comment]
That code for that window is a bit hacky... What version of macOS are you on?

**Comment by dsego** [comment]
@jakob macOS Sierra 10.12.05

**Comment by jakob** [comment]
Build 1747 should fix this issue: https://eggerapps.at/postico/builds/

**Comment by dsego** [comment]
Looks good 👍
