### ISSUE TITLE
Copy URL invalid encoding

### ISSUE THREAD

**Issue by bradleyayers** [jakob/Postico#419]
The Copy URL feature is really handy (in the favourites window), but it does not correctly URL encode usernames/passwords that contain URL reserved characters (e.g. `?`). This means that the copied URL can be invalid, which means it can't be used.

**Comment by jakob** [comment]
Thanks for catching this error. I don't know what I was thinking when I wrote that code.

Fixed in build 1756: https://eggerapps.at/postico/builds/
