### ISSUE TITLE
MySQL equivalent of NOW() ??

### ISSUE THREAD

**Issue by eliduke** [jakob/Postico#42]
Before diving into Postgres / Postico I was using MySQL / Sequel Pro. When creating a new row in a table I could put `NOW()` into a `created_at` field and upon submission it would automatically fill in a current timestamp into that field. Is there an equivalent here? Am I missing something? Thanks!

**Comment by jakob** [comment]
To implement a created_at field, I'd suggest to create a timestamp column with a default value of `now()`:
![screen shot 2015-08-05 at 22 22 46](https://cloud.githubusercontent.com/assets/198305/9097000/065d91f4-3bc1-11e5-8bc8-34601b73c8be.png)
However, PostgreSQL also supports some special values in date and time fields. You can just type `NOW` (without quotes) to insert the current timestamp. You can also type `TODAY` or `TOMORROW` and a few other special values (see [here](http://www.postgresql.org/docs/9.4/static/datatype-datetime.html#DATATYPE-DATETIME-SPECIAL-TABLE) for a full list)

Does that help?

**Comment by eliduke** [comment]
That is very helpful! I see now where my confusion was. Here's a new row that I created:

![screen shot 2015-08-05 at 2 20 06 pm](https://cloud.githubusercontent.com/assets/1372520/9098202/35c00772-3b7d-11e5-9f40-1478272c00fc.png)

Then I saved the changes:

![screen shot 2015-08-05 at 2 20 17 pm](https://cloud.githubusercontent.com/assets/1372520/9098215/4431d812-3b7d-11e5-979c-ebacd1a61590.png)

And then I had to REFRESH to get the timestamp to display correctly:

![screen shot 2015-08-05 at 2 20 30 pm](https://cloud.githubusercontent.com/assets/1372520/9098228/564110a4-3b7d-11e5-9fd3-552c085a46f5.png)

Maybe you could set it so that the timestamp displays on save? Just a thought.

**Comment by eliduke** [comment]
Also, the `allballs` special value doesn't work on my end.

![screen shot 2015-08-05 at 2 24 43 pm](https://cloud.githubusercontent.com/assets/1372520/9098288/bc3199e2-3b7d-11e5-96fe-8327d0ac6513.png)

Is that because `created_at` and `updated_at` have a type of `timestamp without time zone`? It's definitely not a big deal, but I really like the idea of being able to type `allballs`. So funny!

**Comment by jakob** [comment]
Unfortunately, I think `allballs` only works for the `time˚ type.

Anyway, here's a link to a newer build that reloads the row after saving, so you can type `NOW` or `TODAY` and immediately see the new value without having to refresh: [Postico 2015-08-04](https://eggerapps-downloads.s3.amazonaws.com/postico-2015-08-04.zip)

**Comment by eliduke** [comment]
Wonderful! Thanks for the preview on that. :+1:
