### ISSUE TITLE
Customize appearance of specific connections

### ISSUE THREAD

**Issue by d-winter** [jakob/Postico#422]
Hi,

it would be cool if I could change the style of connections. 
This would e.g. allow to mark production connections with a specific color (e.g. red) to avoid accidentally commands on the production database.

**Comment by jakob** [comment]
That's already possible. Click the "edit" button, then select "color" from the "Options" pop-up menu.

That being said, I really recommend to use a read-only user when connecting to a production database. Using a GUI with an admin user on your production db is a recipe for disaster.
