### ISSUE TITLE
Feature Request: Shortcuts for tabswitching

### ISSUE THREAD

**Issue by ebi** [jakob/Postico#424]
I would love to jump to tabs directly with cmd-number i.e. `cmd-3` for the 3rd tab similar to Google Chrome and many other programs.

**Comment by jakob** [comment]
I added that feature in 1.2 (see #391). Does it not work for you?

**Comment by ebi** [comment]
Woops missed the update sorry for that. Works like a charm! :)

**Comment by jakob** [comment]
OK. Thanks for the suggestion in any case!
