### ISSUE TITLE
Incorrect row counts in tables list

### ISSUE THREAD

**Issue by sfcgeorge** [jakob/Postico#426]
Some tables are shown as having 0 rows, 0 bytes, but some index size. Viewing the table shows there are actually rows in there. Reloading or restarting Postico doesn't fix. Screenshots show it best:

<img width="709" alt="screen shot 2017-08-22 at 09 53 14" src="https://user-images.githubusercontent.com/885003/29557350-b467162e-8720-11e7-9182-892d659bf384.png">
<img width="716" alt="screen shot 2017-08-22 at 09 53 48" src="https://user-images.githubusercontent.com/885003/29557352-b48174e2-8720-11e7-877a-c116d5cc6835.png">

There are several other tables showing as 0 rows that actually have one or more. There are also some tables correctly reported.

I guess this is either a caching issue in Postico, or I've somehow screwed up my database?

**Comment by jakob** [comment]
These row counts are only approximate, fetching exact row counts would take too much time. They are updated by ANALYZE.

Additionally, there is a caching issue in Postico, which causes it to never refresh this information.

I should really fix these issues -- probably by changing the column title to "approx row count", and of course by making sure that the metadata is refreshed properly when pressing Cmd-R.

**Comment by jakob** [comment]
To get exact row counts, open the table in Postico (then the exact row count is shown at the bottom), or execute "SELECT COUNT(*) FROM your_table"

**Comment by sfcgeorge** [comment]
Ok, I thought it probably wasn't a `COUNT` which is sensible (I love the general speed of Postico 💯), and once the table is opened yes that count is fine. 

This is a test database so it gets filled and wiped regularly; maybe that explains why ANALYZE would be off. Though it's very noticeable when you're expecting 1 and see 0; if it was a discrepancy on several thousands of rows as in production it wouldn't be an issue.

The reason I noticed is our app was complaining about duplicates in the test DB which should usually be empty... I open Postico and see it is empty... except it's not if I click on the table. But that's a very specific use case. For production DBs how you have it is fine, I wouldn't even rename it.

**Comment by jakob** [comment]
You aren't the first person to report this issue, so I do think I should probably fix it.

Some more details for the curious: The value displayed is the `reltuples` column from the [pg_class catalog table](https://www.postgresql.org/docs/9.6/static/catalog-pg-class.html)

**Comment by sfcgeorge** [comment]
<img width="1440" alt="screen shot 2017-08-22 at 10 23 31" src="https://user-images.githubusercontent.com/885003/29558469-0a04108e-8724-11e7-95a0-d5a34eb6c2c3.png">

There doesn't appear to be a caching issue then in this case. Postico is correctly reporting PG's stats. PG just seems to think the table is empty when it's not. So unless Postico automatically ran `ANALYZE` when you click refresh, I don't know what you could do? Wouldn't running analyze also be slow and probably unexpected to people who fine tune when analyze runs.

**Comment by jakob** [comment]
You are right -- I just checked and the stats are refreshed correctly by Postico -- it seems that I have already fixed this issue.

I completely agree that automatically calling ANALYZE is not a good idea.

However, I will rename the column to "Approx Row Count" or similar to make it more obvious that this is not an exact number.

**Comment by jakob** [comment]
I'm closing this issue because we've decided to remove this view in Postico 2. (There were a few more issues with it, and we've decided that we'd rather focus on other areas of the app rather than fix this view)
