### ISSUE TITLE
Loading table list is too slow

### ISSUE THREAD

**Issue by aamine** [jakob/Postico#430]
It seems loading table list is too slow (60 seconds or longer with our database) in Postico 1.2.  In my experience, Postico 1.1.2 returns table list in max 3 seconds.

I tried to capture long running query, but can get only incomplete query text... it begins with:
```
rel.relname,    rel.relkind,    rel.reltuples,  coalesce(rel.relpages,0) + coalesce(toast.relpages,0) AS num_total_pages,       SUM(ind.relpages) AS index_pages,       pg_user.usename AS owner FROM pg_class rel      left join pg_class toast on (toast.oid = rel.reltoastrelid)     left join pg_index on (indrelid=rel.oid)        left join pg_class ind on (ind.oid = indexrelid)        join pg_namespace on (rel.relnamespace =pg_namespace.oid )      left join pg_user on ( rel.relowner = pg_user.usesysid ) WHERE rel.relkind IN ('r','v','m','f') AND nspname = 'aamine'GROUP BY rel.relname, rel.relkind, rel.reltuples, coalesce(rel.
```
My environment: Postico version 1.2.2, Redshift 1.0.1430

Do you have any clue?

**Comment by jakob** [comment]
Postico executes the following two queries on Redshift to load tables:
```sql
SELECT
    rel.relname,
    rel.relkind,
    rel.reltuples,
    COALESCE (rel.relpages, 0) + COALESCE (toast.relpages, 0) AS num_total_pages,
    sum(ind.relpages) AS index_pages,
    pg_user.usename AS OWNER
FROM
    pg_class rel
    LEFT JOIN pg_class toast ON (toast.oid = rel.reltoastrelid)
    LEFT JOIN pg_index ON (indrelid = rel.oid)
    LEFT JOIN pg_class ind ON (ind.oid = indexrelid)
    JOIN pg_namespace ON (rel.relnamespace = pg_namespace.oid)
    LEFT JOIN pg_user ON (rel.relowner = pg_user.usesysid)
WHERE
    rel.relkind IN ('r', 'v', 'm', 'f')
    AND nspname = %@
GROUP BY
    rel.relname,
    rel.relkind,
    rel.reltuples,
    COALESCE (rel.relpages, 0) + COALESCE (toast.relpages, 0),
    pg_user.usename;

SELECT
    tablename,
    'redshift_external_table',
    NULL,
    NULL,
    NULL,
    NULL
FROM
    svv_external_tables
WHERE
    schemaname = %@;
```

`%@` is replaced by the schema name.

The second query (`SELECT ... FROM svv_external_tables`) is new. Could you check if this is what causes the delay? This query is necessary to get a list of Redshift Spectrum tables. If this query is what's causing the delay, I need to find a way to improve it.

**Comment by jakob** [comment]
(BTW you can press cmd-. to cancel the table loading query if you only want to access the SQL Query View)

**Comment by aamine** [comment]
Thank you for response!!

On my Redshift cluster, first query is fast (< 0.2 sec), but second query takes about 20 to 30 seconds:
```
00:57 => SELECT                 
    tablename,
    'redshift_external_table',
    NULL,
    NULL,                                                                        
    NULL,                            
    NULL                    
FROM
    svv_external_tables
WHERE                                                          
    schemaname = 'activity'
;
 tablename | ?column? | varchar | varchar | varchar | varchar 
-----------+----------+---------+---------+---------+---------
(0 rows)

Time: 22386.742 ms      <----- !!!!
```
This difference may come from the fact that my AWS region (Tokyo, apne1) does not support Redshift Spectrum yet....

**Comment by jakob** [comment]
I asked about this in the Redshift AWS forums... do you know if there is a better way to contact the Redshift team?

**Comment by aamine** [comment]
I retried `svv_external_tables` query and I found the query makes fast now!!
```
aamine 11:19 => SELECT
    tablename,
    'redshift_external_table',
    NULL,
    NULL,
    NULL,
    NULL
FROM
    svv_external_tables
WHERE
    schemaname = 'activity'
;
 tablename | ?column? | varchar | varchar | varchar | varchar 
-----------+----------+---------+---------+---------+---------
(0 rows)

Time: 72.495 ms
```
Our Redshift cluster software was updated in the last weekend (version 1.0.1459), and it seems that slow down problem is fixed in that version... To confirm it, I'm asking AWS support.

**Comment by aamine** [comment]
It seems that this speed up is caused by Redshift patch.  The problem is fixed, I close this issue.  Thank you very much @jakob for all your help!!
