### ISSUE TITLE
Add a command to create schemas

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#435]
A customer suggested to add a command for creating schemas.

**Comment by qwesda** [comment]
I was just about to report this too. 
I was looking for "New > Schema" in the sidebar context menu.

**Comment by villuorav** [comment]
I thought it was simply a `CREATE SCHEMA my_new_schema`.
Alternatively maybe a Cheat-Sheet, with some common commands/phrases and links to official documentation (looking up the version with `SELECT version()`).
And when the feature comes up. Also mentioning the flow possibility there.

**Comment by leebickmtu** [comment]
"New > Schema" option would be great. I know the command is simple to type, but that's all the more reason that it shouldn't really be the hard to add.

**Comment by leebickmtu** [comment]
And updates on if this feature request is being considered or not being that it is so old now?

**Comment by martinjankoehler** [comment]
We've just added this feature to Postico 2. Thanks for your feedback!

Postico 2 isn't released yet, but you can get preview builds here: https://eggerapps.at/postico2/

If you have suggestions how to further improve the favorite management in Postico 2, please open a new issue!
