### ISSUE TITLE
Problem with Array and Geometry

### ISSUE THREAD

**Issue by gustaflindqvist** [jakob/Postico#436]
Using ARRAY with two GEOMETRY Linestring `geometry(LineString)[]` in Postgres via GIS extension and getting query failed:
```
Could not load table rows.
Query failed
PostgreSQL said: function st_asewkt(geometry[]) does not exist
Hint: No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by jakob** [comment]
Thanks for the bug report! There was a bug in the typ checking code, so Postico thought it was a geometry type, and wrapped the value in `st_asewkt` for more readable output -- but of course this doesn't work with arrays.

I've now fixed the type checking code.

The newest build now works with columns of this type. Please download build 1858 from https://eggerapps.at/postico/builds/

Unfortunately however, these columns then only show up as binary gibberish in Postico...

**Comment by gustaflindqvist** [comment]
@jakob Awesome work! Nice to resolve bugs in speed sometimes! 👍 

Yeah. A lot of work needs to be done for not having binary gibberish, I guess.
