### ISSUE TITLE
Request to recover tabs that are accidentally closed

### ISSUE THREAD

**Issue by balajikvijayan** [jakob/Postico#439]
Many times when I'm querying and going between multiple programs I'll accidentally press ctrl + w or ctrl + q because of fat fingers. It would be nice to be able to recover those sql tabs that aren't explicitly saved to a .sql file

**Comment by villuorav** [comment]
@balajikvijayan Those commands can be overridden from the keyboard -> shortcuts.
I did those for some apps, that I cannot afford to be closed.
Plus the history tool also helps alot in those cases 😄

**Comment by balajikvijayan** [comment]
Fair point @villuorav. I also encounter a scenario where I accidentally click the "X" when attempting to switch into a tab; which history tool are you using to recover these SQL windows?

**Comment by thegaryroberts** [comment]
@balajikvijayan In the SQL Query view you can click on the clock icon to get a list of previous SQL queries that you can paste back into the main SQL Query window.

**Comment by balajikvijayan** [comment]
Thank you @thegaryroberts
