### ISSUE TITLE
Tabbed interface

### ISSUE THREAD

**Issue by jopotts** [jakob/Postico#44]
I know this is a big one but... can we have a tabbed interface please?!

I still like the option to have multiple windows. Keep that. But within one window, instead of having the browser style back and forward, can we have tabs instead? I know it's a big change but wanted to raise the topic to see if others agree.

**Comment by eliduke** [comment]
:+1:  :+1: :+1: :+1:

**Comment by qwesda** [comment]
+1

I'll second this – I like to have one window with multiple tabs for one database. There should also be the functionality from sequel pro where double-clicking the tab duplicates the tab state to a new tab, I use that all the time.

**Comment by markbatbean** [comment]
+1

**Comment by kevinjbayer** [comment]
+1

Not a dealbreaker, but it would be awesome to have.

**Comment by gbalytnikov** [comment]
+1

**Comment by jurgemaister** [comment]
+1 Tabbed interface would be the feature that would make me pay for Postico

**Comment by smnorris** [comment]
this is what is missing from PGAdmin

**Comment by wellsoliver** [comment]
+1 would be huge. yuge, bro.

**Comment by charleskimAvant** [comment]
+1

**Comment by fesplugas** [comment]
:+1:

**Comment by DrummerKH** [comment]
+1

**Comment by julian-work** [comment]
:+1:

**Comment by skilbjo** [comment]
+1, paid license

**Comment by wellsoliver** [comment]
+ 1, paid license, really good all around guy, would buy you a beer any time you're in southern California

**Comment by bobcolner** [comment]
+ 1000

Can't wait!

**Comment by jakob** [comment]
It seems that Apple will solve this problem for me; macOS Sierra has a feature named "Automatic Window Tabbing" that adds support for tabs to every app.

So later this year, when you upgrade to macOS 10.12,  Postico will get a fully native tabbed user interface!

Anyway, during testing it seems that the feature is still a bit buggy, and I did have to make some minor changes to Postico to ensure everything works smoothly.

If you are using the Sierra beta, you can try tab support right now:
1) Upgrade to the latest Sierra beta (currently beta 4, earlier betas are even more buggy)
2) Download the latest Postico build here: https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1486.zip
3) Connect to a database, and press Cmd-T to open a new tab

For some reason, the "new tab" button in the tab bar isn't always shown. This seems to be a bug in Sierra. The "New Tab" menu item in the file menu should always work.

(I don't recommend upgrading to the Sierra beta yet; there are still many issues, and it's slow.)

**Comment by qwesda** [comment]
Works as expected. Anything particular that should be tested?

**Comment by jakob** [comment]
@qwesda Thanks for the quick feedback. No, there's nothing in particular to be tested.

One more caveat with tabs: Just like windows, the tabs are independent; therefore changes in one tab don't show up in other tabs until you reload. This is not perfect, but synchronising changes between windows/tabs is pretty complex, and will require some rethinking...

**Comment by qwesda** [comment]
@jakob I will use this version as the primary client and will report anything I encounter.

Re tab data sync: I would not have expected a different behaviour – maybe you should ask around if anyone really does. Automatic synchronisation of data in tabs/windows (across different connections) sounds hard. There might be some lower hanging fruit in the open issues. ; )

What I found more unintuitive is that the every window/tab are separate connections. This can be annoying if you work with temp tables and want to have one window to view the data and one to write queries/commands. But it's no deal breaker.

**Comment by flanger001** [comment]
@qwesda I know I personally am only looking for the same functionality as Sequel Pro regarding tabs, and Sequel Pro has that behavior - every tab is a separate connection. I agree that would not be a deal breaker for me either.

**Comment by jakob** [comment]
@qwesda The main reason for using separate connections is that it should be possible to execute multiple queries simultaneously. (very important for analytics workloads)

**Comment by jakob** [comment]
I've just released Postico 1.0.9, and I'm closing this issue.

**Comment by seanlindo** [comment]
Is it possible to open a new tab with a different connection?
