### ISSUE TITLE
Allow changing font face for table view and query view

### ISSUE THREAD

**Issue by anurag-redmart** [jakob/Postico#440]
Postico currently only allows changing _font size_ for table and query view. It would be great to be able to change the actual font face.

**Comment by jakob** [comment]
You can change the fixed pitch font in Postico with the following command:

    defaults write at.eggerapps.Postico NSFixedPitchFont "Courier"

I like Source Code Pro (from Adobe)

    defaults write at.eggerapps.Postico NSFixedPitchFont "SourceCodePro-Regular"

**Comment by anurag-redmart** [comment]
Thanks! works perfectly.
