### ISSUE TITLE
Shortcut to jump to table

### ISSUE THREAD

**Issue by WCByrne** [jakob/Postico#443]
It would be nice to have a menu item + shortcut to jump to a table. Something similar to spotlight or the common 'jump to symbol' command in many code editors. 

This can kinda be done with ⇧⌘F but that leaves the tables filtered and focus can change as your key down through the results. 

Hope this can make it in to an update.

**Comment by jakob** [comment]
Postico has an "Open Quickly..." command that does pretty much what you are describing (including fuzzy matching the name). The default shortcut is cmd-p.

I just realised that this (very important) command is missing in the list of keyboard shortcuts in the documentation -- I'll fix this in the next release.

**Comment by WCByrne** [comment]
@jakob Thanks, was on an older version (1.0.x)... 

I had checked before creating this issue for an update via prefs > Check for updates but nothing came back. I just downloaded manually and found the command. That's what I was looking for.

**Comment by jakob** [comment]
Thanks for the feedback! And I'm sorry for the problem with the update notification. I should probably switch to Sparkle for updates at some point...
