### ISSUE TITLE
Realtime updates

### ISSUE THREAD

**Issue by cotorusso** [jakob/Postico#45]
Please insert realtime updates in table views.

**Comment by jakob** [comment]
What exactly are you thinking about? Are you thinking about a function that automatically refreshes the table every 10 seconds or so?

**Comment by cotorusso** [comment]
yes something like this :+1:

**Comment by jakob** [comment]
OK. I'll consider it, but I have a few more urgent things to do first.

What's your use case for this feature, if I may ask?

**Comment by cotorusso** [comment]
When i need to see what happens on my db with cronjob without reconnecting for example. It's frustrating reconnecting each time for update a table. Also a refresh button would be useful.

**Comment by jakob** [comment]
You can hit Cmd-R to refresh. Also you can add a refresh button to the toolbar by right-clicking and then choosing "Customize Toolbar"

Lots of people asking for this, so I guess I should show the button by default...

**Comment by cotorusso** [comment]
Ohh thanks :dart:

**Comment by jakob** [comment]
Postico v0.26 now has a reload button in the toolbar by default
