### ISSUE TITLE
Add support for Apache Hive

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#453]
A user has requested support for connecting to [Apache Hive](https://hive.apache.org).

It seems like a useful addition, since a lot of people are already using Postico with other data warehouse solutions. However, I don't think that Hive is compatible with the PostgreSQL protocol, so this would probably be a bigger project

Is anybody else interested in support for Hive?

**Comment by andrewcstewart** [comment]
Seems pretty far outside the current scope of Postico.  imho, I imagine you'd be looking at something on the order of a completely new client that is compatible with any ODBC driver.  That sounds like quite a feat.

I'd def buy it though!

**Comment by jakob** [comment]
Thanks for the feedback!

I've done a bit of research, and adding support for Apache Hive would indeed require a completely different driver, and there's not much similarity to PostgreSQL. For this reason I've decided not to add support for Hive.
