### ISSUE TITLE
Split pasted host with port into the separate input fields

### ISSUE THREAD

**Issue by vvondra** [jakob/Postico#455]
Very often you copy a hostname with concatenated hostname and port, such as `mydatabase.com:5432`

If you post this into the host field, it will fail to connect and often the error is not obvious since the hostname is long and the port is hidden on the right.

It would be a nice UX touchup that if the pasted value contains a port, it would be automatically placed into the correct input field.

**Comment by jakob** [comment]
Good point. We could probably extend that to other strings (eg. URLs), so that you can paste a connection URL and it'll parse it and put everything in the right fields.

**Comment by jakob** [comment]
I've now added automatic parsing of hostname:port and URLs to Postico.

Can you download build 2235 and see if it works as expected?
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2235.zip

**Comment by jakob** [comment]
I've tweaked the behavior slightly so that it only triggers the parsing when you are at the end of the text field.

This should hopefully prevent accidental triggers of this feature while editing IPv6 addresses etc.

https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2239.zip
