### ISSUE TITLE
Table Structure: List Indexes

### ISSUE THREAD

**Issue by eliduke** [jakob/Postico#47]
It would be really helpful to see all of the specific indexes on a certain table listed below the columns in the table structure view.

![screen shot 2015-08-14 at 2 40 57 pm](https://cloud.githubusercontent.com/assets/1372520/9284733/2466fd24-4293-11e5-9145-6fd3df4101f3.png)

**Comment by jakob** [comment]
Thanks for the suggestion! I believe this is one of the biggest missing features right now -- also see #19. I've started working on it, but I'm still struggling with layout / design (especially for multi-column indexes and indexes involving expressions)

**Comment by eliduke** [comment]
Awesome. Well, know that it's on your radar, I'll close this one out. Thanks!

**Comment by jczaplew** [comment]
+1! I would love this feature - it's the only reason I open PgAdmin.

**Comment by mviau123** [comment]
+1!

**Comment by jakob** [comment]
To anyone subscribing this issue: I just posted a prerelease that support listing indices:
https://eggerapps-downloads.s3.amazonaws.com/postico-1240.zip

For further discussion see issue #19 

I'm marking this issue as a duplicate so it's clear that discussion is going on in #19
