### ISSUE TITLE
Autocomplete on 1.3 isn't fuzzy

### ISSUE THREAD

**Issue by bhrd** [jakob/Postico#471]
I used build 2051 which had fuzzy autocomplete, but 1.3 doesn't seem to support fuzzy autocomplete.

**Comment by jakob** [comment]
We were not totally happy with the way that fuzzy autocomplete worked. There were a lot of cases were it behaved oddly (especially with regard to tab completion). We didn't want to release a feature that didn't work well, but we also didn't want to delay the release of autocomplete any further.

For this reason we decided to limit autocomplete to prefix matching. 

We still think that fuzzy matching is a great feature, and we hope that we can add it in a future update. But we really need to make sure it works properly before we can do that.

**Comment by bhrd** [comment]
Thanks for the detailed explanation! Will continue to evaluate the build.
