### ISSUE TITLE
pager number formatting/truncation

### ISSUE THREAD

**Issue by tjmcewan** [jakob/Postico#472]
The pager in build 2142 shows a lovely thousands separator, but then truncates at the separator when the number is updated.

<img width="215" alt="screen shot 2017-12-18 at 12 25 08" src="https://user-images.githubusercontent.com/107308/34086315-fa8761f6-e3ee-11e7-93f8-b3d22c6bf6d5.png">

If I change the number above to `11,001` and press enter, I get taken to page 11. :)

**Comment by jakob** [comment]
I've fixed this in build 2153 by disabling the thousands separator.

https://eggerapps.at/postico/builds/
