### ISSUE TITLE
show empty schema

### ISSUE THREAD

**Issue by DeoLeung** [jakob/Postico#483]
You can use this template for reporting bugs.
Feel free to remove parts that are not relevant, or just write something free-form if you prefer.

## What did you do?

check left table window

## What did you expect to happen?

all tables clustered into schema folders, thus I need to see all schemas

## What actually happened?

schemas without tables are not showed

## What software versions are you using?

Postico version:  
1.3.1

macOS version:  
10.12.6 (16G1114)

PostgreSQL version:  
PostgreSQL 10.0 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16), 64-bit

**Comment by jakob** [comment]
Postico does show empty schemas. But:

1. You need to reload (cmd-R) after creating a schema
2. Postico does not show the public schema by default, it just shows tables from public as if they were not in a schema. (you can change this in preferences)
3. Some schemas are not shown (pg_toast & temp schemas from other connections). There are hidden preferences to show them. To show them, execute the following commands in Terminal: `defaults write at.eggerapps.Postico ShowOtherTempSchemas 1` and `defaults write at.eggerapps.Postico ShowToastSchemas 1`.

Does this help?

**Comment by DeoLeung** [comment]
right, it seems working now (maybe it's just got reloaded), thx~
