### ISSUE TITLE
Doesn't save settings...

### ISSUE THREAD

**Issue by 3rdResistance** [jakob/Postico#486]
I Have tried installing Postico fresh on 10.13.2 several times... no matter what I do it doesn't save the settings I enter.

Not sure how to debug, all I know is that most apps will update the app dynamically when you change settings and there's no save button, but with Postico literally nothing changes, and theres no save button. I close and re-open the app and everything I typed is reverted.

**Comment by jakob** [comment]
Are you talking about the connection favorites, ie. settings like host, port, user, password?

It‘s possible there‘s a problem with the core data database used for storing favorites.

Can you do two things:

1. Open Console.app, type „Postico“ in the search field, and see if any errors are logged when you edit settings.

2. Check the following directory:
~/Library/Containers/at.eggerapps.Postico/Library/Application Support/Postico

This directory contains Postico settings. Try deleting it (make sure you quit Postico first). Then restart your computer, and see if Postico still behaves oddly.

**Comment by 3rdResistance** [comment]
I actually see tons of errors but not related to Postico it seems.

I actualyl didn't have a `Library` folder within Postico so I just deleted the enter at.eggerapps.postico folder and it magically fixed it! Oddly enough it had the settings that were saved from a logn time ago.

Thanks!

![image](https://user-images.githubusercontent.com/32859780/35187523-1adf4e5a-fdf3-11e7-8992-92893d8df1a0.png)
