### ISSUE TITLE
Easier app update

### ISSUE THREAD

**Issue by deyhle** [jakob/Postico#49]
The app update process is quite complicated at the moment (Check for update, download, close app, drag new app to applications folder, restart app). 
An automated update mechanism like [Sparkle](http://sparkle-project.org/) would be great.

**Comment by qwesda** [comment]
+1

**Comment by xarg** [comment]
+1

**Comment by darkness51** [comment]
+1

**Comment by jakob** [comment]
Unfortunately Sparkle does not work with sandboxed applications. There are some forks of Sparkle that work with sandboxed applications, but they basically just provide a back door to get around sandbox restrictions, making the whole sandbox a bit pointless. More info here: https://github.com/sparkle-project/Sparkle/issues/363

I'll investigate alternatives. Currently it seems that the current method, while cumbersome, is the safest.

**Comment by jakob** [comment]
I think I came up with a nice idea. I can make an update installer, and let Postico download that installer and open it. Then you just have to click through the installer to update Postico. Saves you the trouble of manually quitting, moving, and restarting.

Anybody want to test it? Here's a link to a special version of Postico that lets you test the automatic update mechanism:
[postico-0.0.zip ](https://eggerapps-downloads.s3.amazonaws.com/postico-0.0.zip)

To test it, just click the "install" button in the favorites window.

It's still not as elegant as Sparkle, but probably an improvement. What do you think?

**Comment by adi-** [comment]
Why not put Postico as a free (limited) and paid version to appstore? Update process would be automated.

**Comment by jakob** [comment]
I'm working on getting Postico ready for the app store (however only the paid version of Postico will be on the App Store)

**Comment by adi-** [comment]
Great! Please, post a message here when you do.

**Comment by qwesda** [comment]
Been on holiday, sorry for the late reply.
The installer doesn't really save on actions necessary to update the app. 
Also installers feel weird on osx – usually apps that use installers are huge monsters (office, adobe) or contain crapware.

**Comment by jakob** [comment]
Thanks for the feedback.

Sparkle is insecure, installers feel insecure. I don't think there's a nice solution. In a few weeks Postico will hopefully be on the app store, that will probably be the most convenient (and secure) way to handle automatic updates.

**Comment by jakob** [comment]
Postico is now on the Mac App Store! If you want auto updates, you can [find it here](https://itunes.apple.com/us/app/postico/id1031280567?ls=1&mt=12).

As stated above, I'm not planning to add automatic updates. Postico does check for new versions, and it displays a "Download" button in the favorites window when an update is available. But you'll need to quit and delete the old version manually.

I'd like to apologize for the inconvenience, but I just don't see a good and secure solution for automatically updating a sandboxed app that's not on the Mac App Store.
