### ISSUE TITLE
Tab key broken related to autocomplete?

### ISSUE THREAD

**Issue by mpreisinger** [jakob/Postico#491]
## What did you do?

Open a new query editor.  Type the word "select".  Hit the tab key.  

## What did you expect to happen?

I expected a tab to be inserted at the current cursor position.

## What actually happened?

The word "select" became "SELECT".  No tab was inserted.  Pressed "tab" again, still no tab no matter how many times I press the key.

## What software versions are you using?

Postico version:  
1.3.2 (2318)

macOS version:  
10.13.3 (17D47)

PostgreSQL version:  
PostgreSQL 9.6.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9), 64-bit

**Comment by jakob** [comment]
@mpreisinger thanks a lot for your bug report!

Inserting tabs now works as expected after using Autocomplete in Postico 1.3.3

In addition, you can now also press option-tab to insert a tab at any time without triggering autocomplete.
