### ISSUE TITLE
Issue with redshift late binding views

### ISSUE THREAD

**Issue by SeanFLynch** [jakob/Postico#493]
I constantly get this error message when trying to load views after the latest update.

'Could not load table rows.
Query failed
PostgreSQL said: syntax error at or near "FROM"'

I've been advised that this is because of Redshift's new late binding views feature, described here - https://blog.fishtownanalytics.com/using-redshifts-late-binding-views-with-dbt-e735d80f9cfc

Any help on this would be appreciated.

Postico version:  
1.3.2

macOS version:  
10.12.6

PostgreSQL version:  
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.1657

**Comment by jakob** [comment]
Hi Sean, 

Could you check what query Postico is trying to execute? To find out, open the filter bar (Cmd-Alt-F), and then click the "SQL Preview" button.

If you copy paste that query to the SQL Query View, do you get the same error message?

**Comment by SeanFLynch** [comment]
SELECT  FROM "blah"."blah"    LIMIT 500

Same error message as it's missing a *

**Comment by jakob** [comment]
Fixed in Postico 1.3.3
