### ISSUE TITLE
"SQL Query View" section in preferences UI bugged

### ISSUE THREAD

**Issue by macfeaster** [jakob/Postico#494]
This one should hopefully be minor and easy to fix 😄

## What did you do?

- Select About > Preferences

## What did you expect to happen?

Since updating to 1.3.2, the *SQL Query View* part of the preferences is all collapsed together, the UI controls do not occupy the full view they're in. I would guess that some container doesn't occupy all the space it can anymore, instead resulting in all the UI elements being on top of each other. This looked correctly in v1.3 (not sure about 1.3.1.)

## What actually happened?

<img width="848" alt="screen shot 2018-02-13 at 12 05 12 pm" src="https://user-images.githubusercontent.com/6403471/36133168-d489bb1c-10b6-11e8-89c7-2b6c648ca2fd.png">

## What software versions are you using?

Postico version:  
1.3.2

macOS version:  
10.10.5

PostgreSQL version:  
9.6.3

**Comment by jakob** [comment]
@macfeaster Thanks a lot for the detailed bug report!

It looks like I used a constraint type that isn't supported on macOS 10.10. The fix will be in the next update. If you don't want to wait, you can download the prerelease build linked above!

**Comment by jakob** [comment]
Fixed in Postico 1.3.3
