### ISSUE TITLE
Make it easier to report errors/feature requests

### ISSUE THREAD

**Issue by DaleStanbrough** [jakob/Postico#495]
Current process to submit an error report or feature request requires email, or finding the repository, signing in and submitting.

A "Help" menu option (or two) would be helpful - one to email, one to send someone to the repository would make life simpler, and decrease the effort to submit an error/feature request.

**Comment by jakob** [comment]
Postico 2 has a feedback button that makes it easier to submit feedback!

See the Postico 2 preview announcement #689 for details!

**Comment by daleRMIT** [comment]
Thank you!

**Comment by DaleStanbrough** [comment]
Thank you!
