### ISSUE TITLE
Support for LISTEN / NOTIFY -- Feedback wanted!

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#496]
Hi everyone!

I've been working on adding support for LISTEN / NOTIFY to Postico.

There's a lot we could do with those commands, but for now I've decided to just show a notification whenever a NOTIFY message is received from the server.

Here's how to use it:

1) Download the [latest prerelease build of Postico](https://eggerapps.at/postico/builds/)

2) Connect to a database and execute the command `LISTEN some_channel_name;`

3) From a different connection, execute `NOTIFY some_channel_name, 'Some Informative Text';`

The main use case I have in mind for this is debugging applications that use LISTEN/NOTIFY.

Does anybody use LISTEN / NOTIFY with PostgreSQL? I'd love to hear about your use cases, and if you'd use this feature in Postico.

**Comment by qwesda** [comment]
Quick note: the notifications style for postico must be set to "Alerts" - mine was set to "Banners" and it took me a while to figure out why nothing was happening.

**Comment by jakob** [comment]
@qwesda Thanks for the feedback, this is a bug -- I have the default setting ("Banners") and it works.

What version of macOS are you on?

**Comment by qwesda** [comment]
oh ... well then here are my stats: MacOS 10.13.3 / Postgres 10.2, "do not disturb" is not enabled.

**Comment by jakob** [comment]
Could it be that you had multiple copies of Postico running? I've seen issues with user notifications when multiple copies of an app were active...

**Comment by qwesda** [comment]
nope, only the test build was running (also re-tested just now). 
Rebooting also didn't help.

**Comment by jakob** [comment]
OK, so I discovered the cause of the issue. The problem was that for some reason, the invisible "query done" notification was preventing the "notify" notification from showing -- but only on 10.13.

I've now changed how query done notifications work (see #342), and now the NOTIFY messages should show up.

Thanks a lot for the feedback @qwesda!

Build 2458 or later should now support LISTEN / NOTIFY as expected!
https://eggerapps.at/postico/builds/

**Comment by qwesda** [comment]
works as expected now. Tested it directly with (`NOTIFY a, 'hi';`) and with a `NOTIFY` in a plpgsql function.

But I think a feature like this would need a dedicated interface. As soon as you have multiple `NOTIFY` per minute having only the system notifications as a log will be awkward to use. I'm thinking of using  `LISTEN`/`NOTIFY` for a cache invalidation service and hooking into the message pipe with Postico would be great, but I would need a window/message log for it to be useful.

Maybe a separate window, where you can:
- specify the message pipe name
- start/stop the listening
- see a log of the messages
- toggle system notifications

Executing `LISTEN a;`could automatically open the message log window. The log window should also have its own connection, so it doesn't die when I close the wrong tab ...

**Comment by jakob** [comment]
Thanks. Those are good points. An interface like that would be much more useful than just displaying system notifications.

However, this would take a lot more effort than I want to put into this feature. I actually think that this would be enough functionality to build a standalone app...

So I think I'm going to leave the feature as it is, knowing that it's not quite there for "real work", but it's good enough to play a bit with LISTEN / NOTIFY. It's also unlikely to interfere, since you need to actively start listening.

For your use case, maybe you can use a simple python script like this: 
[listen.py.txt](https://github.com/jakob/Postico/files/1802396/listen.py.txt)

Anyway, thanks for your feedback!
