### ISSUE TITLE
app icon context menu entry for new window/connection

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#5]
The ability to create a new window from the app icon context menu would be useful. Currently there is no way of creating a new window in an empty desktop space. You have to go to the space where the app currently is, create the new window and then drag it where you want it to be. 

The menu entry could either just open the favorites view, or there could be a submenu to directly open a saved connection, but this could get overcrowded quickly.

**Comment by jakob** [comment]
I added a "new window" menu item to the dock menu in version 0.25. It let's you open a new window for any of your favorites. More info here: https://eggerapps.at/postico/changelist.html
