### ISSUE TITLE
Can't retrieve Postico license

### ISSUE THREAD

**Issue by supernintendo** [jakob/Postico#505]
There is no way to retrieve a Postico license if you have lost it and migrated to a new machine / reinstalled / etc. There should be a way to retrieve your Postico license on the site by entering your email address.

**Comment by jakob** [comment]
That sounds convenient, but it would probably require me to store customer data on a machine that's reachable from the internet. For privacy reasons, this is something I want to avoid for now.

If you lose your license, please email me -- I usually respond within 24 hours.

**Comment by Marlon-Monroy** [comment]
@jakob  I lost my lincense too. I there should a way to recover it, I have the exact same issue as @supernintendo

**Comment by supernintendo** [comment]
@Marlon-Monroy I ended up reaching out to Postico support via the email address on their site (postico@eggerapps.at) and they were quick to respond. Turns out I had purchased this software via the macOS App Store and was able to download an activated build through there. If this is not the case for you, I would just reach out to Postico support and they should be able to send you your license.
