### ISSUE TITLE
Remove the numerical tab indicator

### ISSUE THREAD

**Issue by mrkcohen** [jakob/Postico#506]
I think this was introduced in the most recent version, but the parenthetical number indicated tab order is confusing/visual clutter.  It would be great to a) remove it or b) make that a preference.

When you open tabs, it does add the right numbers but it makes me think that the tab has a notification for me (similar to an email counter) not actually a tab reference.

Additionally, when you close tabs, the indices/numbers don't update, so it just creates overall more confusion.  For example, here I previously had a tab 2 open, but now tab 3 looks like it's tab 2 and it is confusing where the command+# shortcut will take me.
![screen shot 2018-02-27 at 2 24 05 pm](https://user-images.githubusercontent.com/4603993/36758846-67fdc190-1bca-11e8-9487-6cc30446a1ff.png)

**Comment by jakob** [comment]
I added that number to the tab/window title for debugging purposes, and I forgot to remove it before the last release.

Every tab/window gets a serial number, which is used for autosaving queries. It has nothing to with tab order, which is used for cmd-# shortcuts.

Sorry for the confusion, I think we'll remove it in the next release
