### ISSUE TITLE
Filter button at the bottom should open a filter section close to the button

### ISSUE THREAD

**Issue by nathanpalmer** [jakob/Postico#51]
I believe this came with the very last 0.26 release but now when I click on filter it opens a section at the top. This leads me to go to the very bottom to click filter, then go all the way to the top to put in my filter. Prior to this the filter was at the bottom close to the button. I'd say either move the button up for the section back down

![screenshot 2015-08-17 15 08 31](https://cloud.githubusercontent.com/assets/125599/9313613/deefc6f2-44f1-11e5-9f36-2e0d6308c8eb.png)

This shows the filter button at the bottom, a table inbetween and the filter section on top of it. Less pronounced when I have it all squished like this but expanding it out a bit or full screen it's a much bigger deal.

**Comment by jakob** [comment]
You are right, this is confusing. That's why I had it at the bottom for some time, but people complained that they preferred it at the top ->  #27 

Hmm.

**Comment by kibs** [comment]
Just came here to create an issue mentioning this. I am very happy with Postico, but the UX is weird in that the filter button in the bottom opens a bar in the top :)

**Comment by jakob** [comment]
Thanks for the feedback! We've decided to leave the filter bar at the top. The UX isn't ideal, but we don't want to move the filter button to the toolbar, and moving the filter bar to the bottom isn't ideal either, and I don't want to move around things in the interface if there isn't a very good reason to do so.
