### ISSUE TITLE
Allow filtering tables in sidebar

### ISSUE THREAD

**Issue by anurag-redmart** [jakob/Postico#516]
## Feature Request
Searching for a specific table can be very hard if you have dozens of tables. I have to scroll a lot each time I open postico.

<img width="312" alt="screen shot 2018-03-13 at 9 39 08 am" src="https://user-images.githubusercontent.com/24892347/37322289-a024243c-26a2-11e8-98a5-3ed81e842e76.png">

It would be great to have a filter in the sidebar similar to SequelPro

<img width="200" alt="screen shot 2018-03-13 at 9 43 08 am" src="https://user-images.githubusercontent.com/24892347/37322356-020adcae-26a3-11e8-8e75-194af7181860.png">

## What software versions are you using?

Postico version:  
1.3.2 (2318)

macOS version:  
10.13.3

PostgreSQL version:  
PostgreSQL 8.0.2

**Comment by jakob** [comment]
We have a search field to filter tables in Postico, but it's at the bottom of the sidebar.

Keyboard Shorcut is Cmd-Shift-F

<img width="964" alt="sidebar filter field" src="https://user-images.githubusercontent.com/198305/37333669-30b07602-26aa-11e8-8cb2-5e8f38835b6a.png">

**Comment by anurag-redmart** [comment]
.....Now I feel stupid. Thanks to pointing that out.
