### ISSUE TITLE
Postico crashes when searching for a table -> attempting to right click to open the table structure

### ISSUE THREAD

**Issue by balajikvijayan** [jakob/Postico#521]
## What did you do?
- Search for a table in the DB explorer
- Find the table you are interested and right click to open the structure...
-- Postico invariably crashes and then re-opens tabs for all of my queries

## What did you expect to happen?
- No crashes :)

## What actually happened?
- The app crashed

## What software versions are you using?
Postico version:  
Version 1.3.2 (2318)

macOS version: 
10.13.1 (17B1003)

PostgreSQL version:  
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.1885

**Comment by jakob** [comment]
Thanks for the bug report. Could you check if there are any crash report(s)? You should find them in `~/Library/Logs/DiagnosticReports/`.

You can attach them to this issue or email them to postico@eggerapps.at

**Comment by balajikvijayan** [comment]
[Postico_2018-03-21-112452_balajivijayan.crash.zip](https://github.com/jakob/Postico/files/1834901/Postico_2018-03-21-112452_balajivijayan.crash.zip)

**Comment by jakob** [comment]
Hmm, it looks like NSOutlineView incorrectly recalculates the index of the clicked row when it is reloaded while the context menu is open. I think I have a workaround.

**Comment by jakob** [comment]
@balajikvijayan Thanks a lot for the crash report. Could you try the build linked above ([B2503](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2503.zip)), and see if it still crashes? In my testing, this build fixes the problem.

**Comment by balajikvijayan** [comment]
Confirmed it works! Thanks Jakob
