### ISSUE TITLE
work under schema

### ISSUE THREAD

**Issue by DeoLeung** [jakob/Postico#522]
it will be great if we can choose to work under a certain schema.

example:
schema_1
schema_2
...

if I choose schema_1, it can auto prepend it to the search path, like `schema_1, public, ...`

the use case is we have tons of schemas in the db with identical structure, to isolate users

**Comment by transoceanic2000** [comment]
Also it would be good if the user you login as has a single schema set as their search path that that schema is the one whose table list is opened, so I don't have to dig through lots of other schemas beforehand.

**Comment by jakob** [comment]
We're adding a feature to Postico 2 where you can change the search path with a startup query -- see issue #702 for details!

**Comment by jefflewis** [comment]
Navigating a multi-tenant schema in Postico is frustrating. An application with 100 schemas for tenants would require executing a "set search path" per tenant query. It would be much more convenient to select to start a query from inside a schema that would set the search path accordingly. This is approximately the flow for Navicat (schema being queried is visible in the query view, and a new query can be started from within the schema folder).
