### ISSUE TITLE
Postico doesn't properly display Unicode sequences with U+000000

### ISSUE THREAD

**Issue by andrewgross** [jakob/Postico#523]
You can use this template for reporting bugs.
Feel free to remove parts that are not relevant, or just write something free-form if you prefer.

## What did you do?

When viewing data with the NULL bye, U+000000, Postico will truncate display of that data instead of properly interpreting the character sequence.

Here is the data in Postico:

![](https://captured-pics.s3.amazonaws.com/4kitkIoFD3mi48XOSuQ3X1nCuJldpWXqUc.png)

Here is the data in Python:

![](https://captured-pics.s3.amazonaws.com/1Jef8LSsRmgpjTbPTVTBuoaMX5r3yAZBiI.png)

Notice the Python data is significantly longer.  Here is a JSON file with the sample data.

```
{"unicode_string": "\u5361\u6c76\u59ae 2014\u79cb\u51ac\u65b0\u6b3e\u5973\u88c5\u4fee\u8eab\u663e\u7626\u9542\u7a7a\u9488\u0000\u7ec7\u0000\u6253\u5e95\u886b \u591a\u0000\u8272\u0000\u9ad8\u0000\u5f39 \u7d2b\u8272 \u5747\u7801", "simple_string": "foo", "simple_string2": "bar"}
```

If you happen to have access to Redshift, you can reproduce this easily. [Here](https://gist.github.com/andrewgross/89edecf757c5df2415fe2537835a8f61) is a link to a Gist covering the exact issue with relation to Redshift, and also steps to reproduce.

## What did you expect to happen?

I expected to see the full unicode string displayed, instead of only up to the first NULL byte.

## What actually happened?

I only see a partial string, which stops at the first NULL byte.

## What software versions are you using?

Postico version:  1.3.3
(select "About Postico" from the Postico menu)

macOS version:  10.12.6
(selecting "About this Mac" from the Apple menu)

PostgreSQL version:  PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.1980
(execute the command "SELECT VERSION();" to find out)

**Comment by andrewgross** [comment]
Not a 100% sure if this is a Postico issue or a macOS issue.  Not looking forward to dealing with Apple.

**Comment by jakob** [comment]
It's a Postico issue. PostgreSQL does not allow zero characters in strings (at least in the default UNICODE encoding), so Postico assumes that textual data returned from the server does not contain null bytes.

It should be an easy fix.

**Comment by andrewgross** [comment]
Got it, chalk up another one to Redshift weirdness.  Thanks for investigating.

**Comment by jakob** [comment]
I've done some investigation, and I'm pretty it's a bug in Redshifts data loading. VARCHARs shouldn't contain zero bytes.

I've tried to insert a string with a 0 byte into a VARCHAR column. PostgreSQL absolutely refuses to do that (raises an error: `invalid byte sequence for encoding "UTF8": 0x00`, no matter how hard I try). I even tried using a hex editor to insert a 0 byte in the middle of the string. If I do that, PostgreSQL truncates the string there. So it seems in PostgreSQL, there is no way to get a 0 byte into a VARCHAR.

I also tried inserting 0 bytes into Redshift. I couldn't find a way to do that either with normal INSERT statements. Redshift just truncated the string at the zero byte.

But somehow you did manage to insert a zero byte, and it seemed like an easy fix to make Postico accept zero bytes, so I did that. Postico build bot should post a link as soon as CI is done testing.

I had no way to test if the fix actually works, so I'd appreciate your feedback.

**Comment by andrewgross** [comment]
Awesome, thanks for digging in.  To reproduce on Redshift I had to use the COPY command on JSON. Writing the following to a JSON file worked for me:

`{"unicode_string": "\u5361\u6c76\u59ae 2014\u79cb\u51ac\u65b0\u6b3e\u5973\u88c5\u4fee\u8eab\u663e\u7626\u9542\u7a7a\u9488\u0000\u7ec7\u0000\u6253\u5e95\u886b \u591a\u0000\u8272\u0000\u9ad8\u0000\u5f39 \u7d2b\u8272 \u5747\u7801", "simple_string": "foo", "simple_string2": "bar"}`

As far as I can tell Redshift is doing some weird stuff with the COPY/UNLOAD commands that gets around the normal Postgres ingestion routine, hence the ability to ingest `\u0000`

**Comment by andrewgross** [comment]
Excellent, it works now!  

Current (Buildbot Build) Version
![](https://captured-pics.s3.amazonaws.com/fCa9B2FFiZKml6haf2XlMHVLQMqfR2njRd.png)

Failing Version (1.3.3):

![](https://captured-pics.s3.amazonaws.com/jw5YefyxfdFyGd3UN3RbomltToiN0EATdU.png)

Thanks for the quick turnaround!
