### ISSUE TITLE
Quick Look for bytea

### ISSUE THREAD

**Issue by jakajancar** [jakob/Postico#524]
bytea types nicely show the PDF in the sidebar, but to see it in more than 5x4cm, you have to save it to a document. Quick-look would be nice.

**Comment by martinjankoehler** [comment]
Hey @jakajancar 

Thanks for reporting! 
We have introduced Quick Look for `bytea` in Postico 2.

Please see the Postico 2 preview announcement #689 for details!

Best regards,
Martin
