### ISSUE TITLE
New tabs don't have clean state in SQL editor

### ISSUE THREAD

**Issue by mrkcohen** [jakob/Postico#529]
I'm not sure when this was introduced but when I open a new tab, I expect a clean state on the SQL editor.  However, often times when I open a new tab, there is a relic of a past query already in the editor.

Would it be possible to always have a clear state when opening a new editor tab?

cc @indigoviolet

**Comment by jakob** [comment]
There’s a hidden preference to disable autosaving queries: https://eggerapps.at/postico/docs/v1.3.4/autosaved-queries.html

**Comment by mrkcohen** [comment]
Awesome! Thanks @jakob
