### ISSUE TITLE
Search, search and replace

### ISSUE THREAD

**Issue by trapias** [jakob/Postico#53]
Feature request: it would sometimes be useful to perform simple search (cmd+f) or search/replace operations while working in SQL Query - say you're editing a big query or function.

**Comment by qwesda** [comment]
yes, this would be very useful.

**Comment by jakob** [comment]
I've now added Search & Replace in the query view:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1402.zip

**Comment by trapias** [comment]
Great!!! :+1:
