### ISSUE TITLE
Default Time Zone

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#530]
Postico always shows time and date fields in the server time zone. 

You can temporarily change the time zone by executing a SET command in the SQL query view (eg. `set timezone = 'gmt';`), but this is inconvenient since the time zone resets to the server default next time you launch Postico (or when you open a new window)

It would be convenient if this was somehow configurable (either in the preferences, or per favorite)

**Comment by pdesantis** [comment]
I'd love to see it as a preference option!

**Comment by sanjaypojo** [comment]
I desperately need this feature! 🙏

**Comment by jakob** [comment]
Postico 2 allows changing the time zone automatically with a startup query -- see #702 for details!

**Comment by pdesantis** [comment]
It works, thank you!

I'd like to have a global option to apply the timezone to _all_ connections rather than having to add that query to each connection individually.

That being said, I'll take what I can get :) Thank you!
