### ISSUE TITLE
Postico 1.4 Beta: CSV Import, DDL View, better SSH support

### ISSUE THREAD

**Issue by martinjankoehler** [jakob/Postico#534]
Postico 1.4 Beta: CSV Import, DDL View, better SSH support
==========================================================

Hi!

We'd like to announce a new Postico Beta, and a small Bug Bounty.

Postico 1.4 Beta
----------------

~~Postico 1.4 Beta 1 is available today, please [download Build 2715](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2755.zip).~~
~~UPDATE: Postico 1.4 Beta 2 is available today, please [download 2731](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2755.zip).~~
~~UPDATE: Postico 1.4 Beta 3 is available today, please [download Build 2737](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2755.zip).~~
~~UPDATE: Postico 1.4 Beta 4 is available today, please [download Build 2755](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2755.zip).~~
**UPDATE:** Postico 1.4 Beta 5 is available today, please [download Build 2774](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2774.zip).
 
It has three big new features: 

- CSV Import
- DDL View
- better SSH support

We're planning to release the final version of Postico 1.4 on June 4, 2018.

CSV Import
----------

Postico now allows importing data from CSV files!

This feature has been a long time in the making.
We tried a few different UIs, and ended up with one that works pretty nicely.

We think it's pretty self-explanatory, but we've written detailed documentation just in case. 
If there's anything that's unclear, please let us know!

DDL View (CREATE TABLE)
-----------------------

You can now switch between Contents / Structure / DDL. The DDL (short for Data Definition Language) shows the CREATE TABLE statements for a table.
This feature was a bit tricky to implement, since the PostgreSQL server doesn't actually store the DDL -- Postico needs to generate it.

Better SSH Support
------------------

Postico now supports ED25519 and EDCSA keys.
They've been the standard key type on macOS for some time, so this should make it easier to connect to PostgreSQL servers.

Bug Bounty
----------

We will gift a free license of Postico to everyone who finds a bug in Postico 1.4 Beta!
(if you already have a license, you can give it to a friend)

Conditions:
- you must be the first to report the bug on Github Issues
- you must report the bug before June 4
- the bug must be reproducible

Best regards from

Jakob, Chris & Martin

**Comment by martinjankoehler** [comment]
Hi!

Postico 1.4 Beta 2 is available today, please [download Build 2731](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2731.zip).

We've fixed the first two bugs, issues #538 and #536, thanks for reporting!
- Postico 1.4 Beta: Crash when opening DDL View #538
- "Open Contents" and "Open Structure" in context menu don't work #536

Best regards,
Martin

**Comment by swrobel** [comment]
Please edit the original post with the new link. I'm sure most people, like me, followed the link in the email, downloaded that, scrolled down, and then saw there was a newer build and had to download again (or just missed the fact that there was a newer build).

**Comment by martinjankoehler** [comment]
Hi!

Postico 1.4 Beta 3 is available today, please [download Build 2737](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2737.zip).

We've fixed the first two bugs, issues #535 and #541, thanks for reporting!
- Table cell layout in sidebar can't handle error messages #535
- CSV import discards column matchings when current table is re-selected as target table #541

Best regards,
Martin

**Comment by martinjankoehler** [comment]
Hi!

Postico 1.4 Beta 4 is available today, please [download Build 2755](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2755.zip).

We've fixed the first two bugs, issues #543 and #544, thanks for reporting!
- Create related table sequences when using DDL #543
- Fix issue where Postico did not prompt for SSH passphrase of private key #544

Best regards,
Martin

**Comment by jakob** [comment]
There's a new Beta version: [1.4beta5 / Build 2774](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2774.zip)

This build uses a newer version of libssh2. If you are using ed25519 keys, please try this build!

**Comment by jakob** [comment]
Postico 1.4 is now released, just one week late!

Download from https://eggerapps.at/postico/

(The Mac App Store version will hopefully be available tomorrow)

Thanks to everyone who tried the Betas!
