### ISSUE TITLE
Table cell layout in sidebar can't handle error messages

### ISSUE THREAD

**Issue by tkrajacic** [jakob/Postico#535]
Epic 1.4 Beta bug 😉

## What did you do?

- I opened Postico 1.4 Beta
- A previous connection window opened
- The server was not running though

## What did you expect to happen?

- I expected to see a beautiful UI

## What actually happened?

- The layout in the sidebar to the left is not adjusting height for the long error message correctly

<img width="740" alt="screen shot 2018-05-17 at 15 09 00" src="https://user-images.githubusercontent.com/873717/40179444-a32d53ae-59e4-11e8-9291-1cbf9ecca2f1.png">

## What software versions are you using?

Postico version:  Version 1.4beta1 (2715)

macOS version:  10.13.4 (17E202)

PostgreSQL version:  not applicable

**Comment by jakob** [comment]
That error message is indeed epic!

I think that's not a new bug in Postico 1.4, but it's definitely something we should fix.

(I've emailed you a license)

**Comment by martinjankoehler** [comment]
Hi, 

thanks for reporting, we hope this is fixed with Postico 1.4 Beta 3, please [download Build 2737](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2737.zip).

Please let us know if you still encounter problems!

Best regards,
Martin
