### ISSUE TITLE
"Open Contents" and "Open Structure" in context menu don't work

### ISSUE THREAD

**Issue by jelmervdl** [jakob/Postico#536]
## What did you do?

- I select a view or table in the main window once connected
- I open the context menu
- I click "Open Structure"

## What did you expect to happen?

- I expected to see the structure window for the selected view, which can reach by double-clicking on the view or table in the main window and switching to the structure tab.

## What actually happened?

- Nothing happens. Context menu disappears, that's it

## What software versions are you using?

Postico version:  
Version 1.4beta1 (2715)

macOS version:  
10.13.5 Beta (17F70a)

PostgreSQL version:  
PostgreSQL 10.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 6.3.0) 6.3.0, 64-bit

**Comment by jakob** [comment]
Good catch, thanks for reporting!

Send me an email to jakob@eggerapps.at and I'll send you a license. Let me know what name/email you want on the license!

**Comment by martinjankoehler** [comment]
Hi, 

thanks for reporting, we hope this is fixed with Postico 1.4 Beta 2, please [download Build 2731](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2731.zip).

Please let us know if you still encounter problems!

Best regards,
Martin

**Comment by jelmervdl** [comment]
It indeed works again in Version 1.4beta2 (2731)

Thanks!
