### ISSUE TITLE
Crash when scrolling down right-side pane several times in a table with bytea fields

### ISSUE THREAD

**Issue by beroso** [jakob/Postico#540]
## What did you do?

- (1) I opened a table that have bytea fields (intended to store PDF and image data);
- (2) I clicked on some existing row, moved mouse to right-side pane, and scrolled the pane to bottom;
- (3) After doing step (2) several times, the app crashed.

## What software versions are you using?

Postico version: 1.3.5 (2653) and 1.4beta1 (2715)

macOS version:  10.13.4 (17E202)

PostgreSQL version:  
PostgreSQL 10.4 on x86_64-apple-darwin17.5.0, compiled by Apple LLVM version 9.1.0 (clang-902.0.39.1), 64-bit

## Additional info

[crash-report.txt](https://github.com/jakob/Postico/files/2017728/crash-report.txt)
[postico-crash.mov.zip](https://github.com/jakob/Postico/files/2017731/postico-crash.mov.zip)

**Comment by jakob** [comment]
Thanks for the crash report! Unfortunately I can't find a way to reproduce it on my machine. Is there any chance you could send me a SQL dump of the table?

The crash is happening inside AppKit, and it seems to be related to some NSTableView animation. From looking at the exception type, it looks like this is a memory error. The bug could be either in Postico or AppKit.

Could you try to reproduce the crash with "NSZombieEnabled=YES"?

You can start Postico with Zombies by executing the followig command:
```bash
NSZombieEnabled=YES /Applications/Postico.app/Contents/MacOS/Postico
```

Then try to reproduce the crash (Postico will be a lot slower and need a lot more memory with Zombies). Once Postico crashes, you should see a debug message in Terminal with more details. (eg: `*** -[NSObject retain]: message sent to deallocated instance`). Could you email us the full debug output?

PS: If you want to redeem your free bug bounty license, please send me an email to jakob@eggerapps, and tell me the name / email you want on your license.

**Comment by berosoboy** [comment]
Of course, @jakob . I'll follow your instructions and will send you the debug output soon.

**Comment by beroso** [comment]
Sorry for the long delay.
This problem was solved. I tested it again on current version of Postico and this problem no longer occurs.

### Software used:
Postico v1.5.14
macOS version: 10.15.6 (19G2021)

Postico 2 Preview is fine too 👍
