### ISSUE TITLE
[1.4beta2] CSV import discards column matchings when current table is re-selected as target table

### ISSUE THREAD

**Issue by reidab** [jakob/Postico#541]
## What did you do?

1. Start a CSV import by selecting a file
2. Choose a target table, say `widgets`
3. Configure column matching (via "Match columns by name" in my case)
4. Click to open the "Target Table" dropdown and choose the already-selected `widgets` table

## What did you expect to happen?

No change to the column match configuration, since the target table stayed the same.

## What actually happened?

All the column match settings were reset to "Do not import"

## What software versions are you using?

- Postico version:  Version 1.4beta2 (2731)
- macOS version:  10.13.4 (17E199)
- PostgreSQL version: 9.6.6

**Comment by martinjankoehler** [comment]
Hi, 

thanks for reporting, we hope this is fixed with Postico 1.4 Beta 3, please [download Build 2737](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2737.zip).

Please let us know if you still encounter problems!

Best regards,
Martin

**Comment by jakob** [comment]
@reidab Since this qualifies for the bug bounty, please email me the name / email address you want on your free Postico license!
