### ISSUE TITLE
Create related table sequences when using DDL 

### ISSUE THREAD

**Issue by ryanolton** [jakob/Postico#543]
## What did you do?

- Select a table that is using a sequence
- Went to the **DDL** view
- Copy and pasted generated code into another Postico window (connected to a different database)

Example (as generated via DDL):

`CREATE TABLE categories (`
`    id integer DEFAULT nextval('categories_id_seq'::regclass) PRIMARY KEY,`
`    name character varying(255),`
`    created timestamp without time zone,`
`    modified timestamp without time zone`
`);`

## What did you expect to happen?

- I expected Postico to determine that the sequence did not exist and to create it, as it does (via a prompt) in the **Structure** view when using _serial_.
- Alternatively, if Postico would generate the code to create the sequence automatically via _serial_, that would probably be ideal.

Example:

`CREATE TABLE categories (`
`    id serial PRIMARY KEY,`
`    name character varying(255),`
`    created timestamp without time zone,`
`    modified timestamp without time zone`
`);`

## What actually happened?

- I received the following: `ERROR:  relation "categories_id_seq" does not exist`

## What software versions are you using?

Postico version: 1.4beta2 (2737)
- Note: I'm using 1.4 Beta 3 (per #534), however, the "About Postico" screen still says beta2

macOS version: 10.13.4

PostgreSQL version: 9.6.7

**Comment by jakob** [comment]
Thanks for reporting this! Beta 4 now uses a heuristic to detect SERIAL columns.

If you'd like a free copy of Postico (Bug Bounty), please send the name/email you'd like on your license to jakob@eggerapps.at

**Comment by martinjankoehler** [comment]
Hi, 

thanks for reporting, we hope this is fixed with Postico 1.4 Beta 4, please [download Build 2755](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2755.zip).

Please let us know if you still encounter problems!

Best regards,
Martin
