### ISSUE TITLE
No buttons when duplicating Favorites via Favorites Window

### ISSUE THREAD

**Issue by ryanolton** [jakob/Postico#545]
## What did you do?

- Close Postico completely (though this can also occur without first closing Postico)
- Reopen Postico
- Immediately duplicate any Favorite shown on the Favorites Window

## What did you expect to happen?

- I expected to see buttons along the bottom of the duplicated Favorite (Options, Done, Connect)

## What actually happened?

- There are no buttons at all, and one must allow Postico to lose and regain focus before the buttons appear
- Note: if Postico has been open awhile (focus has been lost and regained), this is less likely to happen, so make sure Postico is closed fully before in order to verify issue

## What software versions are you using?

Postico version: 1.4 Beta 4 (2755)

macOS version: 10.13.4

PostgreSQL version: 10.4 (via Postgres.app)

![screen shot 2018-05-24 at 10 04 22](https://user-images.githubusercontent.com/1325073/40490578-e3b59530-5f39-11e8-921e-478ded0e2ad0.png)

**Comment by jakob** [comment]
If I had a dollar for every display bug in that window.... (I now understand why very few apps have table views with dynamic row heights)

I'll see what I can do. I can't promise that we can fix it.

If you'd like to redeem your free bug bounty license, please send me the name/email you'd like on the license to jakob@eggerapps.at

**Comment by ryanolton** [comment]
I completely understand - I have the same sort of issues with my iOS projects - I just wanted to bring it to your attention. Switching to another app and then back to Postico seems to fix the issue every time, so not a huge deal, thanks!

And I appreciate the bug bounty offer, but I must decline; I'm so thankful that you added **DDL** that I still feel like I owe you for saving me so much time by adding that feature!

**Comment by jakob** [comment]
Turns out it was a simple fix. Just had to call my method that fixes table view in the animation completion handler :)
