### ISSUE TITLE
Use different colors for single and double quoted strings

### ISSUE THREAD

**Issue by patrickf3139** [jakob/Postico#548]
Since single quotes and double quotes mean different things in the Postgres SQL dialect, I think it would be nice if those two string types could show up in different colors, as right now they are the same orange color.

**Comment by martinjankoehler** [comment]
Hey @patrickf3139 !

Thanks for reporting! 
We have introduced Syntax Highlighting Colors in Postico 2.

Please see the Postico 2 preview announcement #689 for details!

Best regards,
Martin
