### ISSUE TITLE
Significant UI lag on MacOS Mojave 

### ISSUE THREAD

**Issue by raspasov** [jakob/Postico#552]
First off, thank you for the great app! 😃 I use it every day for Postgres.

On the newly released (today) beta of MacOS Mojave there's a significant UI lag on every interaction. It's not something minor, and that's why I'm reporting it. The app is technically usable but it's a very slow/painful experience. Every click or action has an additional 1-3 seconds lag which basically freezes the whole UI. I hope it's an easy fix for you, I know how annoying and unpredictable system update changes can be 🤨.

Postico version:  
Version 1.3.5 (2653)

macOS version:  
10.14 Beta (18A293u)

PostgreSQL version:  
PostgreSQL 9.6.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16), 64-bit

**Comment by jakob** [comment]
Thanks for the sample. It might be related to the drawing of the breadcrumb nav. Can you try removing the breadcrumb navigation thing from the toolbar and see if that makes Postico snappy again?

**Comment by jakob** [comment]
(you can remove stuff by cmd-dragging or right clicking on the toolbar and selecting "customize...")

**Comment by reganjohnson** [comment]
Seems to have solved it for me. I will update further as I use the app today. Thanks for the quick reply! Love the app.

**Comment by jakob** [comment]
I finally got the Mojave Beta running on my Mac! The issue in Postico turned out to be a pretty quick fix.

I also saw a lot of mostly cosmetic issues, but we’ll fix those later. At least it’s usable now!

Thanks to everyone for reporting the issue!

**Comment by reganjohnson** [comment]
New build confirmed working for me - thanks again.
