### ISSUE TITLE
I can't save changes to fields

### ISSUE THREAD

**Issue by stevevance** [jakob/Postico#554]
## What did you do?

I edited a field and then tried to Save Changes.

## What did you expect to happen?

I expected that the changes would be saved immediately. 

## What actually happened?

The changes couldn't be saved and I got this error message in a dialog box. It doesn't matter which button I press, the changes are not saved. 
<img width="450" alt="screenshot 2018-06-07 10 59 41" src="https://user-images.githubusercontent.com/1330459/41111609-0c3eba28-6a42-11e8-9a5b-43c789b5e910.png">

## What software versions are you using?

Postico version:  
1.3.5

macOS version:  
10.13.4

PostgreSQL version:  
9.6.6

**Comment by stevevance** [comment]
I resolved the issue by adding a PRIMARY KEY field

**Comment by jakob** [comment]
If there‘s no primary key, Postico compares all columns. If one of the columns has changed in the meantime, that error might show up.

**Comment by stevevance** [comment]
None of the columns had changed in the meantime (there are no applications that use this table). 
Is it possible that another row had duplicate values?
