### ISSUE TITLE
"Starts with" and "Ends with" filters for text fields, similar to "Contains"

### ISSUE THREAD

**Issue by jakajancar** [jakob/Postico#56]
Perhaps even a full "Like" filter that allows you to do "foo%".

**Comment by jakob** [comment]
I just added the new filter types (begins with/ends with/like). They will be released in 0.27.
Prerelease build: https://eggerapps-downloads.s3.amazonaws.com/postico-2015-09-30.zip

**Comment by jakob** [comment]
0.27 is out now: https://eggerapps.at/postico/changelist.html
