### ISSUE TITLE
Empty SQL

### ISSUE THREAD

**Issue by NAlexandrov** [jakob/Postico#563]
## What did you do?

- I clicked on Structure
- Then I clicked on column in unique index
- Then I clicked on Operator Class field
- Then I pressed a ESC key

## What did you expect to happen?

- No SQL changes

## What actually happened?

- I see SQL changes. If click on SQL Preview button then Preview is empty

## What software versions are you using?

**Postico version:**
1.4.2 (2845)

**macOS version:**  
10.13.5

**PostgreSQL version:**  
PostgreSQL 10.0 on x86_64-apple-darwin17.0.0, compiled by Apple LLVM version 9.0.0 (clang-900.0.37), 64-bit

![kapture 2018-06-19 at 21 24 41](https://user-images.githubusercontent.com/157640/41603492-457efcac-7407-11e8-8a92-ddc4922a856e.gif)

**Comment by martinjankoehler** [comment]
Hey @NAlexandrov We've been working on this issue!
The attached build 3399 contains the fix, please let us know if any issues remain.
[postico-3399.zip](https://github.com/jakob/Postico/files/2332643/postico-3399.zip)

**Comment by NAlexandrov** [comment]
Hello. Everything works as expected! Thank you.
