### ISSUE TITLE
Feature to visually distinguish connections (e.g. development, production, etc.)

### ISSUE THREAD

**Issue by madis** [jakob/Postico#566]
It would be nice to be able to tag or otherwise visually distinguish connections made from favorites but not only. Example would be when I connect to production database I would like to be able to set  Postico window borders or top bar at the window to different color so I immediately know I won't start running update queries.

I'd be happy even if it was only manually possible. E.g. you make connection and then from either _Connection_ or _Window_ menu select color, similarly how the tags work in MacOS Finder

![screen shot 2018-06-25 at 17 31 53](https://user-images.githubusercontent.com/674621/41856406-adf1ff9c-789d-11e8-8306-f60836f66af4.png)

**Comment by jakob** [comment]
Are you aware of the color setting? In the favorites window, click the edit button, then select a color from the options pulldown menu

**Comment by madis** [comment]
Very nice. That's pretty much what I was looking for.
