### ISSUE TITLE
Filter Schema

### ISSUE THREAD

**Issue by thomaschui-stack** [jakob/Postico#580]
You can use this template for reporting bugs.
Feel free to remove parts that are not relevant, or just write something free-form if you prefer.

## Feature Enhancement

RedShift/Postgres creates a bunch of `pg_temp` schema, it'll be great if we have the option to hide these temp schemas

## What software versions are you using?

Postico version:  
1.4.2

macOS version:  
10.13.6

PostgreSQL version:  
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.2915

**Comment by jakob** [comment]
Postico normally shows only your own temp schema, but unfortunately `pg_my_temp_schema()` is not available on Redshift.

We're aware of this problem, and we're planning to fix it in an upcoming major release of Postico. (The workaround is not trivial, so unfortunately we can't do this in a minor update)
