### ISSUE TITLE
Can't add cookies to domains with ports

### ISSUE THREAD

**Issue by icithis** [jakob/Postico#587]
While managing cookies, I cannot add a cookie to a domain with a port. For example, localhost:8080 (or http://localhost:8080, or http://localhost:8080/, etc). The issue arises when I click the '+ Add Cookie' button - the button has its color change for the click event, but no form appears.

**Comment by jakob** [comment]
This doesn't sound like it is related to Postico. Did you maybe accidentally submit this issue to the wrong project?

Anyway, I'm closing this now.
