### ISSUE TITLE
Copying from one table to another removes new-lines

### ISSUE THREAD

**Issue by xarg** [jakob/Postico#59]
If you select some rows from a table view and copy this to another table (say from production to localhost db) it will lose the new-lines from text fields.

**Comment by jakob** [comment]
I have now finally implemented support for copy/pasting text in RTF format, which also allows tabular data with newlines inside the cells.

Here's a link to download a development build:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1426.zip

This should now work as expected.

Thanks for reporting this, and sorry it took me so long.

**Comment by jakob** [comment]
Fixed in 1.0.7
