### ISSUE TITLE
Feature Request: Optional Timestamps on NOTICE Output

### ISSUE THREAD

**Issue by jvantuyl** [jakob/Postico#590]
I manage databases with a large number of partitions.  It is often desirable to run a command in a loop for each one of them (which, coincidentally, would look better if #583 were implemented).

For certain operations, it would be handy to know how long they took to run.  It would be nice to have an option in the preferences that would prepend notice output with a timestamp.

**Comment by jvantuyl** [comment]
As an example of the kind of thing I'm doing:

```
DO
$$
DECLARE
  schm varchar;
  tabl varchar;
BEGIN
  FOR schm, tabl IN
    SELECT
      table_schema, table_name
    FROM
      information_schema.tables
    WHERE
      table_name LIKE 'some_table_prefix_%' AND
      table_schema = 'schema_we_hide_partitions_in'
    ORDER BY
      table_name DESC -- because we want to process then in reverse order, because dates
  LOOP
    RAISE NOTICE '%', tabl;
    EXECUTE 'CREATE INDEX ON ' || quote_ident(schm) || '.' || quote_ident(tabl) || ' (col_a, col_b);';
  END LOOP;
END
$$;
```

This runs for 45 minutes, but the first 10 of them are on a single table.  It's hard to notice this without grabbing a coffee and just watching it.

**Comment by jakob** [comment]
That's a good idea. In your case you could work around this with `clock_timestamp()`:

```sql
DO $$
begin
   raise notice '%', clock_timestamp() || ': message 1';
   execute (select pg_sleep(1));
   raise notice '%', clock_timestamp() || ': message 2';
end
$$;
```

**Comment by jakob** [comment]
Better formatting:
```sql
DO $$
  BEGIN
    RAISE NOTICE '%: %', clock_timestamp(), 'message 1';
    EXECUTE pg_sleep(1);
    RAISE NOTICE '%: %', clock_timestamp(), 'message 2';
  END
$$;
```

**Comment by jvantuyl** [comment]
Workaround worked for me.
