### ISSUE TITLE
Postgis coordinates are not correctly formatted in query view

### ISSUE THREAD

**Issue by sul4bh** [jakob/Postico#594]
When I am browsing(click to open) a table:
![screen shot 2018-09-27 at 4 20 05 pm](https://user-images.githubusercontent.com/109486/46179717-69632b80-c271-11e8-8193-425ee86d0475.png)

When I run a select query on the same table:
![screen shot 2018-09-27 at 4 20 23 pm](https://user-images.githubusercontent.com/109486/46179742-88fa5400-c271-11e8-90d6-4277931d61fc.png)

Notice how the coordinate do not get formatted correctly in the select view.

I am on version 1.4.2 (2845)

**Comment by sul4bh** [comment]
I need to add `ST_AsText(coordinate)` in my query. Not a problem with Postico. Closing this.

**Comment by jakob** [comment]
Yes, Postico automatically adds that for geometry columns.

**Comment by jakob** [comment]
(in the table view)
