### ISSUE TITLE
Copy As Markdown

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#597]
I've received a request for "Copy as Markdown" (see also issue #245)

Original Markdown doesn't support Tables, but Github Flavored Markdown does (see https://help.github.com/articles/organizing-information-with-tables/)

Might be useful!

**Comment by jakob** [comment]
Two more samples of textual formats (from issue #615): [text tables](https://www.tablesgenerator.com/text_tables) and [Markdown](https://www.tablesgenerator.com/markdown_tables)

**Comment by martinjankoehler** [comment]
We've implemented Copy Special > Markdown support in the latest Postico 2 build,
available via the built-in updater or manually at https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-9378.dmg
