### ISSUE TITLE
Disable sorting a JSON field

### ISSUE THREAD

**Issue by haihappen** [jakob/Postico#60]
I just accidentally hit the column header of a JSON field, which resulted the error shown below. This error still appears after reloading the database (which was the first thing I did). If Postgres can't sort JSON data, maybe disabling could help with the UX.

![screen shot 2015-09-03 at 10 12 03](https://cloud.githubusercontent.com/assets/14321/9653540/4c80fc6a-5224-11e5-992b-bde712713847.png)

**Comment by jakob** [comment]
Yes, good point. I'll have a look.

As a workaround, you can click a different column to change the sort order.

**Comment by Tibus** [comment]
hello, I have the same error but I can't click on a different column because clicking on "ok" clause the table view popup (in case of editting a id link to other table view)

**Comment by jakob** [comment]
I changed Postico so that it can now sort JSON columns. If a column has type JSON, Postico now uses the command `ORDER BY json_col::TEXT`.

I hope this fixes the issue for you!
Download 1.0.3 here: https://eggerapps.at/postico/
