### ISSUE TITLE
Spacing incorrect in settings

### ISSUE THREAD

**Issue by henrikdahl** [jakob/Postico#607]
## What did you do?

- Opened settings.

## What did you expect to happen?

- See proper spacing.

## What actually happened?

- Double spaces (incorrect spacing) in paragraph text.

![spacing](https://user-images.githubusercontent.com/1430576/47999099-c28c6d80-e101-11e8-8ae2-79f6039c2728.png)

## What software versions are you using?

Postico version:
Version 1.4.3beta (3735)

macOS version:
Version 10.14 (18A391)

PostgreSQL version:  
10.4 on x86_64-apple-darwin17.5.0, compiled by Apple LLVM version 9.1.0 (clang-902.0.39.1), 64-bit

**Comment by jakob** [comment]
Thanks a lot for taking a look at the Beta! We've fixed this is in build 3754:
https://eggerapps-downloads.s3.amazonaws.com/postico-3754.zip

Please send an email to postico@eggerapps.at and tell us what name you want on your free bug bounty license!

**Comment by henrikdahl** [comment]
Thank you ✌️ 

Can confirm that bug is no longer present in `build 3754`.
