### ISSUE TITLE
making money from postico

### ISSUE THREAD

**Issue by jamesdixon** [jakob/Postico#608]
Hey @jakob,

Not sure if you recall, but I've been pretty vocal about my disappointment with still not having the ability to edit functions/stored procedures (#72). This still is the case and I'm still disappointed. That said, this got me thinking about the "why?"

I obviously have no insight into how many licenses Postico sells or any other factors that may affect development. However, I do know that your free version is really great and there are tons of people I know personally that use it and from them, you're not making any money. I also know that software isn't cheap to maintain so if you're not making enough money on it to support the development, then things start to stall. 

All that said, if that happens to be the case with Postico, I think you should totally change your model  to support additional development. A free trial with an option to buy after the trial would be totally worth it for people. I literally use Postico every single day. It's the best Postgres client on the market and I recommend it to every single person I know who uses Postgres and a Mac. I'd even be willing to pay a yearly maintenance fee or something that would allow me to have access to future versions.

All I'm saying is that you have a great application here that provides a shit ton of value to people and we obviously want even more from it. So if we need to pay, we need to pay!

Just my two cents. Would love to hear your thoughts.

Cheers,
James

**Comment by jakob** [comment]
### Sustainability

Postico makes enough for me, two part time developers, and a small cushion for unforeseen expenses. We're a sustainable business, and at the moment I see no immediate need to grow the team or increase prices.

### The Trial

The trial is generous on purpose. I'd rather have people use Postico for free than not use it at all. A bit of it is altruistic. I remember when I couldn't afford to pay for software.

But more important, the free trial is how we market Postico. We're a tiny company, and we need every bit of exposture we can get. The free trial allows us to reach a much bigger audience. And a lot of these "free" users buy a license eventually.

### Development Speed

Our time is spent roughly 50% on new features and 50% maintenance / QA.

We're a small team, so we can't add features as quickly as people like. Currently we release major new features about once or twice per year. For us, that's a sustainable pace, but I understand that it's frustrating when a feature you want takes a long time.

We're always working on new features, but I don't want to make any promises about specific features. Things always take longer than expected, and I don't want to disappoint people.

**Comment by jamesdixon** [comment]
@jakob sorry, I didn't see that you had responded. I appreciate the response. I'm glad that sustainability is not an issue. That said, it makes it a bit a disappointing that we're not seeing highly requested features being added. I had mentioned this before, but having a public roadmap to show what's currently in development and what's on the table would be really great. Otherwise, customers are in the dark. Can you at least give some insight as to what's coming?

**Comment by jakob** [comment]
The next feature we'll release is going to be support for dark mode.

We're also working on other features, but I don't want to promise anything in public. If you email me privately (jakob@eggerapps.at) I can tell you a bit more.
