### ISSUE TITLE
Copy Special > Markdown

### ISSUE THREAD

**Issue by jdub** [jakob/Postico#615]
Here's a goofy feature request.

I appreciate the flexibility of the "Copy Special" formats, but there's one I'm missing: old school monospace text tables, for documentation files, chat programs, etc.

So far I've been using Tables Generator for [text tables](https://www.tablesgenerator.com/text_tables) and [Markdown](https://www.tablesgenerator.com/markdown_tables). If you didn't want to add two items (and more as folk as for every wiki format under the sun), the Markdown one would be more widely applicable.

**Comment by jakob** [comment]
Thanks for the suggestion! A request for markdown is already tracked as issue #597

I guess for documentation, the text tables you link to look a lot nicer than the Markdown variant. Might be worth supporting both.

Anyway, I'm closing this issue since it is a duplicate.
