### ISSUE TITLE
Hiding sidebar is not persisted

### ISSUE THREAD

**Issue by pakohan** [jakob/Postico#617]
Sidebar reappears again after hiding and changing view.

## What did you do?

- I clicked on the button for enabling the right side bar (detail view sidebar)
- then I disabled it again
- then I changed into another view
- then I changes back in the previous view (not using the back buttons)

## What did you expect to happen?

- I expected the side bar to still be hidden

## What actually happened?

- the side bar was there again, and after reducing the width, the sidebar took the width it used to have before resizing

## What software versions are you using?

Postico version: 1.4.4

macOS version: macOS Mojave 10.14.1

PostgreSQL version: 11.1

**Comment by jasonfantasia** [comment]
Just FYI for anyone else having this issue.  I solved it (I assume temporarily) by deleting the config folder which lives at:
`/Users/you/Library/Containers/at.eggerapps.Postico`

Also, if it's not obvious, be aware that this kills any of your preferences... **INCLUDING** your saved connection settings.  This didn't matter to me, but I wanted to be clear that this is the "nuke it from orbit" solution.  I haven't spent any time trying to pin down where the configuration setting is being persisted to.  If this happens again, perhaps I will spend more time on it.

If anyone cares, I'm using Postico 1.5.3 on Mojave 10.14.2

(ps. Thanks to Jakob for the best Postgres GUI client out there)

**Comment by jakob** [comment]
Hi!

@jasonfantasia I'm not sure why deleting favorites would fix this issue...

In any case, I found the bug and fixed it. Please download build 4118 and let me know if it works:
[Postico 4118.zip](https://github.com/jakob/Postico/files/2773239/Postico.4118.zip)
