### ISSUE TITLE
Feature: Save "SQL Query" split-pane height preferences across app restart

### ISSUE THREAD

**Issue by jmooo** [jakob/Postico#619]
Per @jakob's request on issue #602:

Every time Postico restarts, the height of the split-pane divider resets so you end up with a little query pane and a lot of results pane. I'm sure everyone is different but I like that slider at about 70:30 query:results, it would be convenient if Postico remembered those pane positions just like it remembers the query pane contents (amount my fav feature, btw)

not a rush or a complaint, Postico is fantastic thanks for continued development!

**Comment by martinjankoehler** [comment]
@jmooo Thanks for your feedback.

We have implemented the first issue (sticky horizontal query window divider) with Postico 2 build 8375,
available via the built-in auto-updater or as manual download at
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8375.dmg

Best regards,
Martin
