### ISSUE TITLE
Postico v1.5 won't open in macOS Mojave 10.4.2

### ISSUE THREAD

**Issue by GreeKatrina** [jakob/Postico#621]
## What did you do?

- I updated my mac to Mojave 10.4.2
- I opened Postico (either version 1.4.3 or 1.4.4, not 100% sure), and it said a new version was available.
- I downloaded the new version and dragged it from Downloads to Applications and clicked `replace`. 

## What did you expect to happen?

- I expected Postico to open. I have updated Postico before in the same way and it worked fine.

## What actually happened?

- The app icon just kept bouncing in the dock.

**I tried:**
1. Removing it from the dock and clicking it in Applications, but got the same result.
2. Letting it bounce for a few minutes. It finally stopped. (see image below) No window opens when I click on it, but apparently it is opened because when I right click on it the `Quit` option is available. Furthermore, there is no white dot below the app icon suggesting that it's open.

![screen shot 2018-12-20 at 10 44 41 am](https://user-images.githubusercontent.com/6021090/50294699-72b0fe00-0444-11e9-8504-5d5b2116f17a.png)

3. Moving Postico to trash and re-downloading it. Got the same issue.

## What software versions are you using?

Postico version:  
v1.5

macOS version:  
Mojave 10.4.2

PostgreSQL version:  
9.6.10

**Comment by jakob** [comment]
Hi!

Could you check if you have any crash reports in this folder?

~/Library/Containers/at.eggerapps.Postico/Data/Library/Application Support/Postico/Crash Reports


In the mean time, you can download Postico 1.4.4 here:
https://eggerapps-downloads.s3.amazonaws.com/postico-1.4.4.zip

**Comment by GreeKatrina** [comment]
So for some reason my computer didn't bring the "Postico is an app downloaded from the internet" pop up to the front screen. I had like twenty of them open. It's working. I'm sorry. 😅

**Comment by jakob** [comment]
Glad you could resolve it.

Thanks for following up!
