### ISSUE TITLE
Slow Performance of SQL Text View

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#629]
The SQL text editor has performance issues with large amounts of text.

According to customer reports in issue #622, Postico seems to have gotten slower in version 1.5. However, I have not been able to reproduce any issues with 1.5 specifically. All performance problems I have found affect Postico 1.5 and Postico 1.4 equally.

I've discovered one specific issue that caused hangs when inserting large amounts of text in the SQL text view. I've addressed that issue in Build 4108.

Download here: [postico-4108.zip](https://github.com/jakob/Postico/files/2760026/postico-4108.zip)

Can you please try this build, and let us know if you are still seeing performance issues with that build?  Please also let us know the following:
1) Computer Model + Year
2) macOS system version

It would also be extremely helpful if you could send me the contents of the query editor, so we can try to reproduce any issues specific to queries you execute. I understand that this is not possible for most users since queries are probably confidential -- but maybe you cancome up with sample queries similar to yours that still exhibit the problem. You can send me sample data via email to jakob@eggerapps.at

**Comment by jakob** [comment]
After some more customer feedback I've been able to narrow the issue down to macOS 10.13. (it works fine on macOS 10.10 and 10.14)

There seems to be a bug in macOS when a text view has a transparent background. I've made the text view opaque again, and it seems to work again.

Can you try build 4109 and see if it works?

[postico-4109.zip](https://github.com/jakob/Postico/files/2760467/postico-4109.zip)

**Comment by newhouse** [comment]
I wasn't really having the same level of issues anymore after install 1.5.3, (so the issue was "closed" in my mind) but I also don't have a really-really big sql editor scratch pad. Nonetheless, I'll download and try this one!

**Comment by hayesr** [comment]
This made a big difference for me, I'm stuck on 10.13 for reasons.

**Comment by newhouse** [comment]
I'm on 10.14.x now on all my machines (and I can't remember if I was when I was having this issue), but things are good by me now. Thanks for the help!

**Comment by jakob** [comment]
@newhouse Thanks for the feedback!

The fixes discussed here were released in Postico 1.5.4. I'm closing the issue now.
