### ISSUE TITLE
DDL default now() is displayed as current time

### ISSUE THREAD

**Issue by DeoLeung** [jakob/Postico#642]
You can use this template for reporting bugs.
Feel free to remove parts that are not relevant, or just write something free-form if you prefer.

## What did you do?

create time with
```sql
CREATE TABLE course (
    id SERIAL PRIMARY KEY,
    create_time timestamp without time zone NOT NULL DEFAULT now() without time zone,
);
```
## What did you expect to happen?

as above

## What actually happened?

it shows the ddl
```sql
CREATE TABLE course (
    id SERIAL PRIMARY KEY,
    create_time timestamp without time zone NOT NULL DEFAULT '2019-03-23 00:30:22.718757'::timestamp without time zone,
);
```

## What software versions are you using?

Postico version:  1.5.6

macOS version:  
(selecting "About this Mac" from the Apple menu)

PostgreSQL version:   11.2

**Comment by jakob** [comment]
The code you provided has syntax errors.

What you describe is what would happen if you typed the following:

```sql
CREATE TABLE course (
    id SERIAL PRIMARY KEY,
    create_time timestamp without time zone NOT NULL DEFAULT 'now'
);
```

If you do this, it works as expected:

```sql
CREATE TABLE course (
    id SERIAL PRIMARY KEY,
    create_time timestamp without time zone NOT NULL DEFAULT now()
);
```

**Comment by jakob** [comment]
Oh... did you use the structure editor to create the table? Then you need to set the popup to "expression" -- if you set it to "constant" it would cause this issue...

<img width="770" alt="Bildschirmfoto 2019-03-22 um 18 36 40" src="https://user-images.githubusercontent.com/198305/54842296-d8c25100-4cd1-11e9-93f1-892e8b459fdc.png">

**Comment by DeoLeung** [comment]
yes, I think that comes from my `sqlalchemy` orm which I the sql turns out to be
```sql
CREATE TABLE course2 (
    id SERIAL PRIMARY KEY,
    create_time timestamp without time zone NOT NULL DEFAULT 'now()'
);
```
then it shows the above DDL, correct it using 
```sql
CREATE TABLE course2 (
    id SERIAL PRIMARY KEY,
    create_time timestamp without time zone NOT NULL DEFAULT now()
);
```
thank you
