### ISSUE TITLE
Hide column in Content View

### ISSUE THREAD

**Issue by StephaneJuban** [jakob/Postico#649]
Hi !

Is it possible to hide a column from the Content View ? Is it possible using the Filter option with a custom SQL for example ?

**Comment by jakob** [comment]
Unfortunately it's not possible to hide columns in Postico.

But you can create a view that just selects a few columns. If it is a simple view, it will automatically be updateable, and Postico also auto-detect foreign keys etc. from the source table.

**Comment by StephaneJuban** [comment]
Perfect, this do the job !
