### ISSUE TITLE
copy rows with headers

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#65]
Maybe there is some space in the "copy special" menu for "copy rows with headers".
Since sadly excel ist still the poor mans database of choice for many people and "copy rows" is the only command that pasts correctly into excel this command might save people some time. 

Also the row context menu might be a good place for an "export" or "save as" option with csv and excel.

**Comment by trapias** [comment]
+1

**Comment by jakob** [comment]
Impemented in 1.0.1
https://eggerapps.at/postico/changelist.html
