### ISSUE TITLE
[UX enhancement] A better layout for the main window.

### ISSUE THREAD

**Issue by prsquee** [jakob/Postico#650]
Hi jakob, 

I think the current layout for the main window is wasting a lot of space: 

![](https://i.imgur.com/0BHPzQe.png)

almost a third of vertical space is wasted. Maybe the "new favorite" can be a smaller button at the top, like how Safari and Mail does this in a toolbar style. This would give Postico more of that native feel.

Just an idea, thanks!

Postico version:  current
macOS version:  10.14.4

**Comment by jakob** [comment]
I agree that the favorites window is not ideal if you have a large number of favorites. When I designed it, I typically had around 5 favorites.

We're working on a new version of Postico with all new favorite management. If you'd like to help beta test it, please email me!

**Comment by jakob** [comment]
A preview of Postico 2 is now available  (see issue #689 or http://eggerapps.at/postico2/).

The new version has a much improved Favorite editor. I'm closing this issue for now, if you have further suggestions please open a new issue, or use the feedback button in the toolbar of Postico 2.
