### ISSUE TITLE
On Redshift, searching for a table or asking for its structure requires all previous pg_temp schemas to load

### ISSUE THREAD

**Issue by tpilewicz** [jakob/Postico#654]
## What did you do?
We use Postico to connect to our Redshift. I searched and clicked one of our tables to see its DDL statement.

## What did you expect to happen?
I expected it to answer quite quickly (I just want the structure of the table)
Benchmark: about 5 seconds on SQL Workbench J

## What actually happened?
It took about 30 seconds, because Postico needed to fetch contents for all of the schemas before answering, including all of the pg_temp ones. I guess Postico doesn't need to read all of the pg_temp schemas, only the last one, right?
This issue only happens every now and then, because once all schemas have been fetched, they don't need to be fetched again for some time.

## What software versions are you using?
Postico version:  Version 1.5.6 (4521)
macOS version:  10.14.4 (18E226)
PostgreSQL version:  
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.7078

**Comment by yurzo** [comment]
I second this request, postico is loading these pg_temp_* schemas, which are dependent on number of connections and temp tables, and delaying my usage that has nothing to do with pg_temp_*.

**Comment by tpilewicz** [comment]
To give more precision on this: it only happens if :

- You use the search bar to find your table, which needs to fetch the contents of the schema to give an answer
- You have "Show system catalogs" checked in Preferences > Sidebar. I guess this places all schemas including the system ones in the search_path.

Right now my personal workaround is to uncheck "Show system catalogs" from the preferences, I guess this is quite acceptable so I'm closing the issue.

**Comment by yurzo** [comment]
>  uncheck "Show system catalogs" 
Yeah! that works!

**Comment by jakob** [comment]
Great to hear you found a workaround! 

I'm sorry for the lack of response to this issue from my side.

I just wanted to acknowledge that we're aware of it, and we consider it a problem that should be fixed. We've started refactoring the catalog sync code, and hope to make filtering tables more efficient + responsive in the future, even on databases that have hundreds of schemas / tables.

However, at the moment that's still a somewhat distant goal, and I can't make any promises when the optimized catalog fetch code is ready for release.

**Comment by yurzo** [comment]
If anything I’d just change the default

**Comment by tpilewicz** [comment]
Good to know this will be optimized in the future!

> If anything I’d just change the default

If this rework of the table search is a long term goal, I think yurzo's suggestion is worth considering ;)
