### ISSUE TITLE
Lose my favorites after upgrade

### ISSUE THREAD

**Issue by testarossaaaaa** [jakob/Postico#661]
## What did you do?

Upgrade from 1.5.6 to 1.5.8

## What did you expect to happen?

See all my favorites and content of my sql tabs

## What actually happened?

Everything erased 

## What software versions are you using?

Postico version:  
1.5.8

macOS version:  
Mojave

PostgreSQL version:  
11

**Comment by jakob** [comment]
Hm. Can you check in activity monitor if the new version of Postico is sandboxed?

1. Open Activity Monitor
2. Search for "Postico"
3. Go to the "CPU" tab
4. Look for the "Sandbox" column (right click on the column titles to enable sandbox column if it is not visible)

**Comment by testarossaaaaa** [comment]
It says "No"

**Comment by jakob** [comment]
OK, then the app is most likely damaged. Please delete and re-download the app from https://eggerapps.at/postico/ 

If it still doesn't work, there may be an issue with verifying the code signature. Try restarting your computer and see if that fixes it. Often code signing issues can be fixed just by restarting the computer.

Some 3rd party tools and utilities have also been known to damage the code signature, by modifying files inside the app bundle. Some compression utilities may cause issues as well, so I recommend to just use the default Archive Utility that's built into macOS for uncompressing the ZIP file.

**Comment by jakob** [comment]
I'm closing this issue. Feel free to reopen if reinstalling Postico didn't fix the issue with the lost favorites!
