### ISSUE TITLE
A way to reset the cache?

### ISSUE THREAD

**Issue by deeTEEcee** [jakob/Postico#667]
My app is hanging because I have a postgres table with many columns (just assume it's near the limit). But after trying to open the "Structure" page and killing the app, I just want to start from the main loading screen for connecting to servers. For that reason, how do I reset the cache?

**Comment by jakob** [comment]
macOS stores the state of windows in the "Saved Application State" folder in your library. For Postico, that folder should be at the following path:

```
~/Library/Containers/at.eggerapps.Postico/Data/Library/Saved Application State/at.eggerapps.Postico.savedState
```

If you delete that directory, Postico will start with just the favorites window when you next launch it.

(I'd like to apologise for the late response; I hope you have been able to fix the issue on your own  in the mean time)
