### ISSUE TITLE
How can I deactivate In MacOS?

### ISSUE THREAD

**Issue by leeduckgo** [jakob/Postico#681]
I am going to use it in another computer, so I want to deactivate it in the computer I using now & active on the new computer. 
What should I do?

**Comment by martinjankoehler** [comment]
Hi, 

a Postico license can be used on multiple personal computers.

No need to deactivate.
If you wan't to do it nevertheless, just 
- open main menu _Postico > Help > License Information_
- click _Show License File_
- Finder will appear with the license file being selected
- Now you can move it away or delete it on this computer

Best regards,
Martin
