### ISSUE TITLE
Change reserved words colors

### ISSUE THREAD

**Issue by artpel** [jakob/Postico#683]
Hey Jakob and team at Eggerapps !

Thanks for this amazing soft that is Postico, I'm using it professionnaly everyday and it's one of the best software for Mac available, accross all verticals, mainly because it is deeply integrated to MacOS design and dev principles. Congrats !

That being said, it's not an issue, but more an accessibility improvement. Could you add to your backlog the ability to change to colors of reserved words, strings and operators (even with a basic `.plist` file to edit), I'm kind of colorblind and in light mode it's hard for me to focus on my SQL requests.

No rush, just a nice to have.

Cheers 💜

## What software versions are you using?

Postico version:  1.5.10
(select "About Postico" from the Postico menu)

macOS version:  macOS Catalina 10.15 (19A602)
(selecting "About this Mac" from the Apple menu)

PostgreSQL version:  PostgreSQL 9.5.15
(execute the command "SELECT VERSION();" to find out)

**Comment by martinjankoehler** [comment]
Hey @artpel!

Thanks for reporting! 
We have introduced Syntax Highlighting Colors in Postico 2.

Please see the Postico 2 preview announcement #689 for details!

Best regards,
Martin
