### ISSUE TITLE
Incorrect sorting on Timestamp fields

### ISSUE THREAD

**Issue by asakariya** [jakob/Postico#684]
You can use this template for reporting bugs.
Feel free to remove parts that are not relevant, or just write something free-form if you prefer.

## What did you do?

I tried to sort a Timestamp type in the client to find out I wasn't seeing the order as I expected. Upon closer examination I found that the sorting was incorrect. Possibly sorting of timestamp object is done lexicographically(?). 

As you will see in the image below, in the place_time column, second row, the time should be in the top row. But the row that's in the top has a truncated sixth digit (a 0, presumably). It is possible that truncation is causing a problem in the sort. 

## Postico Version 1.5.10 (5293)

macOS version:  
10.14.6 (18G103)

PostgreSQL version:  
PostgreSQL 11.5 on x86_64-apple-darwin16.7.0, compiled by Apple LLVM version 8.1.0 (clang-802.0.42), 64-bit

<img width="473" alt="Screen Shot 2019-10-31 at 10 15 22 PM" src="https://user-images.githubusercontent.com/13448860/67998025-30904580-fc2d-11e9-806c-0f5f2604c57c.png">

**Comment by jakob** [comment]
We fixed this in Postico 1.5.15
