### ISSUE TITLE
Postico 2 beta: SQL query history

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#686]
The query history seems to be missing from this build. 
I don't know if it was removed on purpose, or if it just hasn't found a new place in the new multi-query-interface yet. 

It's a feature I use often and I just stumbled over if (day 2 of using the beta).

One history per query "sql document" would be probably a good way to integrate it with the new design.

Postico version:  
Version 2.0beta (5705)

**Comment by martinjankoehler** [comment]
Hello,

we're restored the query history feature in build 6282,
available through the autoupdate or downloadable here: https://releases.postico.app/v2/download

Worth to mention is that the query history is now stored per-favorite, not per-file.

So I'm closing this issue for now, if you have further suggestions please open a new issue, or use the feedback button in the toolbar of Postico 2.

Best regards,
Martin
