### ISSUE TITLE
Postico 2 beta: new tab behaviour

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#687]
When opening a new tab in Postico 1 the tab would be opened with the same table and the same filter as the previous tab.

This was really handy. It would be great if Postico 2 could have the same behaviour or introduce another shortcut for this (like `CMD + SHIFT + T`).

Postico version:
Version 2.0beta (5705)

**Comment by jakob** [comment]
We fixed this in build #5773! The behaviour is now the same as in Postico 1.5.
