### ISSUE TITLE
Generated column support (Postgres 12+)

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#688]
Add support for generated columns:

- make then non-editable in the table view
- have them differentiated in the structure view
- fix the DDL 
```domain_part text  GENERATED ALWAYS AS (regexp_replace(email, '^.+@'::text, ''::text)) STORED,```
instead of
```domain_part text DEFAULT regexp_replace(email, '^.+@'::text, ''::text)```

**Comment by martinjankoehler** [comment]
@qwesda Thanks for the feedback!
We've decided to show an error instead with the hint to manually drop and re-add.
This is now available via in the built-in auto updater or manually at https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8602.dmg

**Comment by qwesda** [comment]
I tested the new build. It's ok as it is, but I think you can make the column definition non-editable. Maybe add a tooltip explaining that the server doesn't support the `ALTER` command. This would communicate what's going on to the user.

**Comment by jakob** [comment]
This is now supported in both Postico 1.5.20 and Postico 2.
