### ISSUE TITLE
Copy Special -> Copy JSON: obsolete space before colon

### ISSUE THREAD

**Issue by defkode** [jakob/Postico#693]
```json
[
  {
    "name" : "Archivo",
    "type" : "sans-serif"
  }
]
```
extra space before colon : is obsolete

**Comment by jakob** [comment]
Thanks for the suggestion. I agree it would look nicer without the space, but I don't think this is important enough to write our own JSON serialisation code (we use `NSJSONSerialization`, which does not allow customizing the format)
