### ISSUE TITLE
Crash in Postico 1.5.11

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#699]
We've just released Postico 1.5.11, and through our automatic crash reporter we've discovered there's a serious bug in the structure editor.

We're working on a fix. In the mean time, please downgrade to Postico 1.5.10:
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-1.5.10.zip

**Comment by jakob** [comment]
I just published Postico 1.5.12. My apologies to everyone affected by the bug.

As usual, you can download the latest build here:
https://eggerapps.at/postico/

**Comment by grahamburgsma** [comment]
Thanks for the quick fix! But I'm getting a 403 from the download link https://s3-eu-west-1.amazonaws.com/eggerapps-downloads/postico-1.5.12.zip

**Comment by jakob** [comment]
@grahamburgsma Thanks a lot for letting me know. I forgot to rename the file on the server.

**Comment by grahamburgsma** [comment]
It's working now, thanks!
