### ISSUE TITLE
Cannot drop procedure using delete option on functions tab (procedure is not a function)

### ISSUE THREAD

**Issue by Julien0002** [jakob/Postico#707]
## What did you do?
- I clicked on "functions" tab 
- select a stored procdures.
- right clic and select "Delete..."
![image](https://user-images.githubusercontent.com/17622527/80364761-bb719600-8886-11ea-992d-93660a77a275.png)

## What did you expect to happen?
- I expected the procedure to be dropped

## What actually happened?
- I got the following error message
```PostgreSQL said: db_xxx.proc_alrt_cnt(text) is not a function```
![image](https://user-images.githubusercontent.com/17622527/80365064-4ce10800-8887-11ea-9393-d87b97dd708f.png)

## What software versions are you using?
Postico version:  
Version 2.0beta (6492)

macOS version:  
10.15.4 (19E287)

PostgreSQL version:  
PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit

**Comment by jakob** [comment]
Thanks! I fixed this in build 6529. Use the "Check for updates" command to update, or download the update manually from https://releases.postico.app
