### ISSUE TITLE
Please support "execute current query" like sequel pro 

### ISSUE THREAD

**Issue by lheine** [jakob/Postico#71]
Please support to switch from "execute all" to "execute current query" like sequel pro.
This executes only the query where the blinking text cursor is positioned.

Example:

select 1;
select 2;
select 3;

Cursor is positioned in line 2.
Execute "execute current query" will only
run "select 2" and not all three queries.

I know you support the execution of the currently selected text only.
But it's not as convenient/safe because you have to reselect the query
part every time before you execute it.

Lorenz

**Comment by jakob** [comment]
I'm already working on this --- see issue #11
