### ISSUE TITLE
SQL editor slows down as more queries are added

### ISSUE THREAD

**Issue by FedericoMassaioli** [jakob/Postico#721]
The SQL editor slows down as queries are added or made more complex and the file grows.

This is particularly noticeable when using cursor keys to scroll.

**Comment by jakob** [comment]
Postico is generally not very performant when using very large query files, but scrolling really shouldn't lag.

What version of Postico are you on? How big are the contents of the query editor roughly?

**Comment by FedericoMassaioli** [comment]
I'm using Postico 2. Did I post in the wrong place? I'm sorry.

My query file is in the 6 to 8 KB range

**Comment by jakob** [comment]
Reporting here is fine, I just wanted to know which version you're on! The editor in Postico 2 has changed a lot.

Anyway, 8KB really shouldn't cause any performance issues.

There is a regression with selection highlight that causes lags when you have many very many statements, but I'm not sure if that would cause issues if the query file is only 8KB.

Is there any chance you could send us one of the query files that has slow performance? You can email to postico@eggerapps.at

**Comment by martinjankoehler** [comment]
@FedericoMassaioli we've been working on query editor performance improvements,
which are available via the built-in Postico 2 auto-updater or manually at
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8893.dmg

Please let us know if your experience has changed, and of any use cases still in need for further improvement.

Best regards and thanks,
Martin

**Comment by FedericoMassaioli** [comment]
@martinjankoehler , in one mont and half, the problem didn't manifest again.
If you want to close the issue, is fine with me.

Thanks
Federico

**Comment by martinjankoehler** [comment]
@FedericoMassaioli  Awesome! Thanks for testing!
