### ISSUE TITLE
Chrome Flagging 1.5.14 Download as Dangerous

### ISSUE THREAD

**Issue by mrchave3-hl** [jakob/Postico#722]
When attempting to download the recent update, 1.5.14, Chrome keeps flagging the download as potentially dangerous. I'm using the download provided via the in-app button.

![Screen Shot 2020-07-17 at 9 09 28 AM](https://user-images.githubusercontent.com/44783264/87807543-39519780-c80d-11ea-8171-40579167a184.png)

**Comment by jakob** [comment]
That's unfortunate. It's a signed and notarized app, I'm not sure why Chrome considers it suspicious.

Does downloading from https://eggerapps.at/postico/ work?

**Comment by mrchave3-hl** [comment]
Yes, downloading from there works fine. Interestingly it works fine now downloading from either source so Chrome must have decided it isn't an issue anymore.
