### ISSUE TITLE
Postico 2: Redshift external tables integration failing

### ISSUE THREAD

**Issue by charles-firth** [jakob/Postico#724]
## What did you do?

- Attempted to view a table in a Redshift Spectrum external schema by double clicking on the table name

## What did you expect to happen?

- The contents of the table come up!

## What actually happened?

- Query failed error message:
Query failed
PostgreSQL said: Operation not supported on external tables

![image](https://user-images.githubusercontent.com/50623567/88912304-ffde4a80-d256-11ea-8e12-2eb09234216a.png)

The table can be viewed when you query it via the query editor directly however (i.e. select * from schema_ext.table)

## What software versions are you using?

Postico version:  
Version 2.0beta (6838)

PostgreSQL version:  
Latest AWS Redshift version

**Comment by martinjankoehler** [comment]
Hello Charles!

Thanks for reporting.
We've been working on this issue, it should now be resolved in this pre-release build:
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-7187.dmg

Please let us know if this fixes the problem on your side.

Best regards and thanks,
Martin

**Comment by jakob** [comment]
We merged the fix. You can download the latest build from here: https://releases.postico.app

We're closing this issue. Please let us know if you run into any further issues!
