### ISSUE TITLE
Feature Request: Make font size of list of tables configurable

### ISSUE THREAD

**Issue by briangorman** [jakob/Postico#727]
## What did you expect to happen?
In preferences, I can increase the font size of the list of tables on the left pane

It is difficult to navigate the list of tables because the default font-size is tiny.

**Comment by vegetabill** [comment]
Big +1 on this. The SQL query text and table rows size are both configurable so this would be really helpful.

Blue skying it, having them all linked to that Cmd+Plus/Minus could grow and shrink them all together when screen sharing would be amazing but having a setting at all would make this fantastic tool even better!

**Comment by martinjankoehler** [comment]
Hey @briangorman @vegetabill ,

we've implemented font preferences in Postico 2:
![Bildschirmfoto 2021-12-22 um 16 59 40](https://user-images.githubusercontent.com/29398377/147120474-6e21b7a2-094f-40be-9128-e4a0e9f64245.jpg)

Available using the built-in auto-updater or manually at 
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-9228.dmg

Best regards and happy holidays,
Martin
