### ISSUE TITLE
Autocomplete giving incorrect results

### ISSUE THREAD

**Issue by gdoe** [jakob/Postico#731]
## What did you do?

I typed the name of my schema, then ".", and was given a list of options. Some of those options were historical typos, not actual columns in the table. 

## What did you expect to happen?

- The list of options should only include valid columns or options

## What actually happened?

- Some of those options were historical typos, not actual columns in the table.  When I ran the query, I get the message that "schema.my_column" isn't in the table, which was puzzling until I figured out what happened.

## What software versions are you using?

Postico version:  
Version 2.0beta (7213)

macOS version:  
10.15.6 (19G2021)

PostgreSQL version:  
PostgreSQL 12.4 (Ubuntu 12.4-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit

**Comment by jakob** [comment]
Postico doesn't automatically refresh the autocomplete information. But you can always press Cmd-R to invalidate all cached data, then the autocomplete data should be refetched automatically next time.

**Comment by gdoe** [comment]
Great, I will try that, thanks Jakob.
