### ISSUE TITLE
Postico 2 (7256): Connect via SSH tunnel fails with invalid argument

### ISSUE THREAD

**Issue by johanneswuerbach** [jakob/Postico#734]
On Build 7256 establishing a connection via an SSH tunnel fails with "invalid argument". Downgrading to Build 7234 resolves the issue.

MacOS version 10.15.7

**Comment by jakob** [comment]
Are you sure that this is caused by Build 7256 vs 7234?

It sounds like the file descriptor leak (see issue #725), which is a known issue that we haven't fixed yet. The workaround right now is to quit and restart Postico when the issue occurs.

**Comment by johanneswuerbach** [comment]
Ah, I downgraded and it worked, but didn't try to upgrade again.

**Comment by johanneswuerbach** [comment]
Upgraded and works again, so this is a duplicate. Sorry :-(

**Comment by jakob** [comment]
Don't worry, I'm glad you reported it anyway. I much prefer duplicate issues to not knowing about an issue.
