### ISSUE TITLE
iCloud storage of queries?

### ISSUE THREAD

**Issue by wellsoliver** [jakob/Postico#736]
Is it possible to add storing queries in iCloud for moving between computers?

**Comment by jakob** [comment]
Yes, that's possible.

I assume you are using Postico 2 and already have a library (configuration directory) in iCloud. Any queries you create in the sidebar with the "+" button are created inside the library folder and synced via iCloud.

If you add files from Finder with drag and drop, by default Postico just opens the file in place and creates a reference to the file in the sidebar. That reference is not synced over iCloud, it's just on one machine.

If you hold down the option (alt) key when dropping the file, Postico creates a copy which will be synced. For example, in this screenshot, the first file is inside the library folder and is synced, and the second one is just a reference and is not synced. You can see it is a reference by the little arrow symbol.

<img width="934" alt="Bildschirmfoto 2020-11-02 um 21 25 26" src="https://user-images.githubusercontent.com/198305/97915936-950b4680-1d52-11eb-87c0-5db56bc7a4be.png">

For the sake of anybody else who stumbles across this issue, here are step-by-step instructions how to sync your servers and queries with iCloud:

On the first computer:

1) Make sure you have a recent build of Postico 2 (from https://eggerapps.at/postico2/)
2) Go to Preferences -> Library
3) Click the "Create New Library" button
4) Choose the "Encrypted with Master Password" option to securely sync credentials
5) Select a location in iCloud Drive
6) Now close preferences, and create a server in your new library. You can also just drag a server from your local library to your newly created library

On the second computer:

1) Open Postico 2
2) Go to Preferences -> Library
3) Click the "Add existing Library" button
4) Select the library folder in iCloud Drive that you created on the other computer
5) The server you created on the other computer should show up!

Any query files you create on either computer should be synced automatically to the other computer. If Postico doesn't refresh automatically, you can always try pressing Cmd-R to force a reload.

Does that answer your question?

**Comment by wellsoliver** [comment]
Beaut! Thank you!
