### ISSUE TITLE
Struggling with ye olde spinning beach ball of death

### ISSUE THREAD

**Issue by wellsoliver** [jakob/Postico#738]
This isn't a bug report b/c I know how "this isn't working" can drive an engineer nuts, but I'm wondering if there's something I can do to better diagnose this to report it: I'm having a lot of spinning beach ball states in the last two versions of Postico 2.

It's almost always after I execute a query, and after it is fully loaded in the results pane (and the result counts don't seem to matter: hangs after 1 row, hangs after 1000 rows). It can spin/hang for about 15 seconds, which can be an eternity. I'm not sure what it's doing: there are not further UI elements to adjust or render.

It's an iCloud library, MacOS Catalina 10.15.7.

What can I do to better troubleshoot why this might happen? I know I'm providing no helpful details here :)

**Comment by jakob** [comment]
Thanks for reporting this! Every bug report is useful, even when we can't reproduce it (yet).

Is there a reason why you closed the issue?

Anyway, unless you disabled the "Report Crashes" preference, Postico 2 should automatically send an anonymous stack trace when it hangs for more than a few seconds. If you tell us at what date & time the hang occurred (in GMT) then I can look up if I find the stack trace, which should give us an indicator of where it's hanging.

Even better would be a sample generated with Activity Monitor (as described [here](https://eggerapps.at/postico/docs/v1.5.14/reporting-bugs.html)):

> When Postico hangs...
> A hang is when the app stops responding. Sometimes the beachball cursor appears after a few seconds, but not for all types of hangs. When reporting a hang, please send a process sample of Postico.
> To create a process sample, open Activity Monitor, select Postico, click the info button in the toolbar, then click "Sample". After a few seconds a sample will appear. Save it, then email it to us. Make sure to sample Postico while it is actually hanging.

A sample created with Activity Monitor contains multiple stack traces and gives us an even better indication of what's going on (ie. is it actually doing something that we need to optimize or is it stuck waiting for something).

**Comment by wellsoliver** [comment]
Did not mean to close! I will definitely return to this issue with some times and details should it continue, thanks for the help.

**Comment by wellsoliver** [comment]
What's the best way to send a sample dump to you?

**Comment by jakob** [comment]
email to postico@eggerapps.at

**Comment by jakob** [comment]
I think we've fixed this bug in the mean time. If I recall correctly it was caused by the query history feature.
