### ISSUE TITLE
Testers wanted for Big Sur and Apple Silicon Compatibility

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#740]
Postico 1.5.14 mostly works on Big Sur, but there are a lot of graphical glitches due to the new interface design of macOS 11. We've been working on getting Postico ready for the new OS since June, but since the beta versions have been a bit of a moving target, we unfortunately haven't managed to be ready on release day.

Anyway, Postico 1.5.15 is almost ready. Postico 1.5.15 fixes most graphical issues, adds support for Apple Silicon, and it contains a workaround for an unresolved TLS certificate bug in macOS 11 (see issue #728 for details).

You can download Postico 1.5.15 release candidate here:
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-7378.zip

If everything goes well, we're planning on releasing Postico 1.5.15 on Monday, Nov 16, 2020. If you've already updated to Big Sur, please let us know if Build 7378 works for you!

**Comment by gavacho** [comment]
I'm on big sur and am able to connect and query using this build

**Comment by rurza** [comment]
Thanks :) Any chance for un updated icon?:)

**Comment by jakob** [comment]
@rurza Postico 2 will get an updated icon, Postico 1.x will keep the old icon.

**Comment by rurza** [comment]
When we can expect it? Will it be a paid upgrade? What's new? :)

**Comment by jakob** [comment]
@rurza We announced Postico 2 almost a year ago here on Github: #689

We're still working on it, and it's going to be a paid upgrade. The major new features are described at https://eggerapps.at/postico2/

**Comment by rurza** [comment]
Thanks for the reply :) Do you have any upgrade plan for people that just bought the app? :D

**Comment by jakob** [comment]
@rurza We haven't made a final decision on pricing or upgrade policy yet. But for now your license will unlock Postico 2 Preview.

Postico 1.5.15 was released earlier today. Thanks to everyone who provided feedback!
