### ISSUE TITLE
Table names needlessly abbreviated in sidebar

### ISSUE THREAD

**Issue by i-tu** [jakob/Postico#745]
### What did you expect to happen?
 I expected to see full-width table names in my spacious sidebar.

### What actually happened?
Table names did not fill the space, but got abbreviated to 16 character-length with an ellipsis at the end.

<img width="285" alt="Screenshot 2020-11-24 at 9 17 24" src="https://user-images.githubusercontent.com/2201932/100060896-e8465580-2e35-11eb-9fbc-3da368a49810.png">

### What software versions are you using?

Postico version:  Version 2.0beta (7442)
macOS version:  10.15.6 (19G2021)
PostgreSQL version:  PostgreSQL 12.4 on x86_64-apple-darwin16.7.0

**Comment by tkrajacic** [comment]
This seems to be a very common bug in Bug Sur that appears in many applications. Even in Apple's own (e.g. Xcode)

**Comment by jakob** [comment]
I'm not sure exactly what causes the issue, but it seems to be fixed in build 7453:
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-7453.dmg

(That build isn't yet merged into master, so the auto-update funtion won't install it yet)

**Comment by tkrajacic** [comment]
My uneducated guess is that minuscule layout changes in Big Sur (possibly just if the app is built under Big Sur) make the columns, as set up in Storyboard or xib, not touch the right edge of the scrollview, and so they don't attach. If you make the window smaller until the last column touches the right edge, and then scale it up again, the last column will stick to the right properly.

**Comment by KurtPattyn** [comment]
I filed a similar issue via the inline feedback. I am not running Big Sur and still having this problem

**Comment by tkrajacic** [comment]
The show and hide sidebars buttons in the menu bar of the server overview are also not working for me under 10.15. They are permanently enabled (so both sidebars are shown) and can't be disabled. I tried this because it turns out on 10.15, even the server names are all abbreviated despite more than enough space.

**Comment by jakob** [comment]
@tkrajacic There are no sidebars anymore in the server overview, which is why the sidebar buttons are disabled.

**Comment by i-tu** [comment]
I downloaded the new build and the bug is gone on my machine. Thank you for the fix @jakob ! I will close the issue.

Also taking this chance to offer you some praise: It is always a real pleasure to use Postico. So many useful and delightful features! You have really hit it out of the park, and I would gladly pay the cost of my license many times over. Kudos!
