### ISSUE TITLE
Import CSV with exponents

### ISSUE THREAD

**Issue by jeremycochoy** [jakob/Postico#746]
Postico allow export of CSV with exponents for small decimal values (ex: -3.73434e-15) but do not allow to read them when importing. Not very funny (:

![image](https://user-images.githubusercontent.com/4193259/100383703-91e83b00-301e-11eb-9773-d52b2d1f9c43.png)

**Comment by jakob** [comment]
Thanks for reporting this. We should really fix this.

**Comment by jakob** [comment]
We've fixed the bug! Postico now accepts floats with exponential notation. The bug fix will be released in Postico 1.5.17.

You can download a pre-release build here: https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-7513.zip

If you are already using the Postico 2.0 beta, you can just use the "Check for Update" function to install the latest build.

There are some special values that we still don't support (inf, nan). They are on our to do list. But at least the more common case should work now!

Thanks again for reporting the issue!
