### ISSUE TITLE
Postico crashes when using autocomplete while writing inner join

### ISSUE THREAD

**Issue by Samsinite** [jakob/Postico#748]
## What did you do?
Started typing a query, got to the `INNER JOIN table_name ON table_name.field_`, it is trying to autocomplete (the dropdown shows the field name(s) available) and the application becomes unresponsive. Ex:
```
SELECT * FROM table_name
  INNER JOIN related_table_name ON related_table_name.related_    <- autocomplete dropdown shows up here and app becomes unresponsive
```

## What did you expect to happen?
I expected to be able to write my query.

## What actually happened?
The app becomes unresponsive

## What software versions are you using?

Postico version:  
`Version 1.5.16 (7440)`

macOS version:  
`Big Sur 11.0.1`

PostgreSQL version:  
`PostgreSQL 10.11 on x86_64-apple-darwin14.5.0, compiled by Apple LLVM version 7.0.0 (clang-700.1.76), 64-bit`

**Comment by Samsinite** [comment]
Is there a way to revert to a previous version or disable autocomplete? With this bug, it pretty much makes using Postico unusable and I love this software :(.

**Comment by jakob** [comment]
Hi @Samsinite! Thanks for reporting this bug.

If I understand correctly, Postico is hanging (and maybe showing the beachball cursor), but it keeps running. Does it eventually become responsive again, or do you have to force quit it?

Is there any chance you could send us a sample of Postico (as described [here](https://eggerapps.at/postico/docs/v1.5.16/reporting-bugs.html)):

> To create a process sample, open Activity Monitor, select Postico, click the info button in the toolbar, then click "Sample". After a few seconds a sample will appear. Save it, then email it to us. Make sure to sample Postico while it is actually hanging.

**Comment by Samsinite** [comment]
Hi @jakob, sorry for the delayed response, I didn't look at my notifications I had to force quit, but let me download the latest version, enable autocomplete, and see if it is still an issue. If so, I'll send over the requested data.

**Comment by Samsinite** [comment]
@jakob this issue appears to have been fixed in the latest version, cheers!
