### ISSUE TITLE
Special Invisible Unicode characters should be highlighted (or replaced)

### ISSUE THREAD

**Issue by cansik** [jakob/Postico#75]
I have a problem when I try to use the SQL Query Textbox to create my database Schema. If I copy my SQL form the PyCharm IDE, there are some signs copied which should not be there. If I run the query, this is the output:

```SQL
ERROR:  syntax error at or near " CREATE"
LINE 2:  CREATE VIEW "query_view" AS  SELECT prov.name AS provenance...
        ^
Query failed
PostgreSQL said: syntax error at or near "‚Ä®CREATE"
```

Maybe it's a failure of the copy function of PyCharm, but would be great If Postico would "clean" the inserted text.

Here the query:

```SQL
-- Query View
 CREATE VIEW "query_view" AS  SELECT prov.name AS provenance,     pgt.name AS property_group_type,     pg.fc_id,     pg.time_start,     pg.nar,  ....
```

**Comment by jakob** [comment]
Might be non-breaking spaces or similar. If you email me the query, I can investigate: jakob@eggerapps.at

**Comment by jakob** [comment]
It looks like the query contains the unicode `LINE SEPARATOR` character, which PostgreSQL does not understand.

Since problems with odd unicode characters appear to be common (another example is issue #25), I'll investigate ways to detect and highlight or remove these types of characters in Postico.

**Comment by jakob** [comment]
Postico 1.0.1 now automatically converts LINE SEPARATOR to LINEFEED, which should fix this issue. More info: https://eggerapps.at/postico/changelist.html

**Comment by gajus** [comment]
@jakob I ran into a similar issue when copy-ing text from CLI that contains colour characters. It put me really off-track:

<img width="770" alt="screen shot 2017-04-14 at 12 41 32" src="https://cloud.githubusercontent.com/assets/973543/25042404/b5fb5dc8-210f-11e7-8055-51c74c7b19ca.png">
