### ISSUE TITLE
better tab naming

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#752]
The current naming scheme for tabs is `<connection_name> – <database_name> – <table_name>`.

If I have 4 or more tabs open, only `<connection_name> – <database_name>` is visible, which is not very helpful.

Reversing the naming scheme `<table_name > – <database_name> – <connection_name>` would produce more useful tab names.

**Comment by qgenda-timcoker** [comment]
This is the way mine works.  Looks like this issue should be closed.

**Comment by qwesda** [comment]
jepp, can be closed
