### ISSUE TITLE
Favorite Export: "Include Query History" Doesn't Work As Intended

### ISSUE THREAD

**Issue by amiantos** [jakob/Postico#764]
## What did you do?

- I got a new MacBook, so I exported all my favorites from Postico with the "Include Query History" box checked. When imported into Postico on my new Mac, the query history was not included.

## What did you expect to happen?

- I expected to see that my query history was imported along with my favorites.

## What actually happened?

- Query history did not appear.

## What software versions are you using?

Postico version:  
1.5.17

macOS version:  
11.3.1

PostgreSQL version:  
PostgreSQL 12.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9), 64-bit

**Comment by martinjankoehler** [comment]
Hello @amiantos,
I could not reproduce this issue (exporting from and importing into) 1.5.17,
and the query history is included after the import.

Did you use version 1.5.17 on both sides?

**Comment by amiantos** [comment]
I just reproduced this on 1.5.17. I right clicked and picked "Export All Favorites". Used these settings:

![image](https://user-images.githubusercontent.com/1126616/120841162-0517c000-c520-11eb-9b51-1077234d17b9.png)

Then I drug one of the favorites from the folder created back into Postico to create a new favorite, connected to it, and there's no query history. I get the same result regardless of whether I do "export all" or just a single favorite.

**Comment by amiantos** [comment]
Just to make sure, by "Include Query History" I assume the feature means that all my custom SQL queries I've written into the "SQL Query" panel are persisted. Maybe I'm misinterpreting the feature.

**Comment by jakob** [comment]
@amiantos oh, it looks like this is a misunderstanding. "Query History" refers to the queries shown when you click the history/clock icon in the SQL Query editor. These are the queries that the checkbox saves:

<img width="895" alt="Bildschirmfoto 2021-06-07 um 11 50 00" src="https://user-images.githubusercontent.com/198305/120996321-81abd800-c786-11eb-85e0-639a7745eb6c.png">

There's not actually a way to include the contents of the query editor when exporting favorites in Postico 1.x. Thinking about it now this is something that's obviously missing.

We've completely rewritten that part of the UI in the upcoming Postico 2, and the new version does export queries, but the exported files are unfortunately not backwards compatible with Postico 1.x. I think there are also still some bugs in the export code in Postico 2 Preview.

**Comment by amiantos** [comment]
Awesome. Luckily this isn't a big problem for me, I was just transferring to a new computer while the old one still worked so I was able to grab my query history manually. Still glad to hear that the feature will come in the future though!
