### ISSUE TITLE
SSH key path not working across multiple sync'd installs

### ISSUE THREAD

**Issue by ffxsam** [jakob/Postico#770]
You can use this template for reporting bugs.
Feel free to remove parts that are not relevant, or just write something free-form if you prefer.

## What did you do?

I have Postico 2 installed on my Mac mini and on my MacBook Pro, and sync is enabled on both (via Dropbox). Things mostly seem to sync without issues.

## What did you expect to happen?

I'd expect the server settings to sync properly.

## What actually happened?

Even though the SSH path is the same on both Macs (`/Users/samh/.ssh/EC2-RC2.pem`), I get this error when I move to my other Mac:

<img width="398" alt="image" src="https://user-images.githubusercontent.com/12532733/120829811-71e08980-c523-11eb-83c3-8df02f48744c.png">

## What software versions are you using?

Postico version:  Version 2.0beta (8194)
(select "About Postico" from the Postico menu)

macOS version:  11.4
(selecting "About this Mac" from the Apple menu)

PostgreSQL version:  10.14
(execute the command "SELECT VERSION();" to find out)

**Comment by ehamberg** [comment]
Related to https://github.com/jakob/Postico/issues/717.

[This comment](https://github.com/jakob/Postico/issues/717#issuecomment-658671850) explains that _just syncing the path doesn't work since Postico is sandboxed_.

**Comment by ffxsam** [comment]
@ehamberg Thank you! I apparently chose the wrong setting and did not pick the master password protection. It seems to work fine now, and prompts me for a password to unlock access to the private key.
