### ISSUE TITLE
money column sorted incorrectly with negative values

### ISSUE THREAD

**Issue by RyanDurk** [jakob/Postico#771]
The GUI sorts [non-negative] money values numerically with the fix for #768 (thanks!). However, the GUI now sorts negative values as if larger than non-negative ones.

## What did you do?
Run a query--

SELECT vals, vals::money money
FROM generate_series(-5, 5) as t1(vals)
ORDER BY 2

## What did you expect to happen?

Clicking the money header should sort negative values numerically.

## What actually happened?

Negative values are sorted as if larger than the positive ones, and secondly according to their absolute value (see the query results in GUI).

## What software versions are you using?

Postico version:  
 1.5.18

macOS version:  
11.2.3

PostgreSQL version:  
13.2

**Comment by martinjankoehler** [comment]
Hello @RyanDurk,

thanks for reporting this issue
(_Money column sorted incorrectly with negative values_)

We've fixed this in Postico 1.5.19 [(download)](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-1.5.19.zip) and the latest Postico 2.0 beta.

Closing this one now, please feel free to re-open or open a new one should any issues occur.

Best regards,
Martin
