### ISSUE TITLE
Code formatting fails if Perl executable outside sandbox

### ISSUE THREAD

**Issue by lsundman** [jakob/Postico#775]
Hi!

Code formatting in Postico 2 fails on my system. Pressing <kbd>⌃</kbd>+<kbd>F</kbd> just gives me a beep and the following in Console.app (`74892` is Postico):

	Sandbox: env(74892) deny(1) process-exec* /opt/homebrew/Cellar/perl/5.34.0/bin/perl

It seems like the issue is that I have Perl from Homebrew prioritized in my PATH for both my shell and GUI apps.

Using `launchctl procinfo` I get the following environment for Postico 2:

```
application.at.eggerapps.Postico.6987052.6987153 = {
<snip>
	inherited environment = {
		PATH => /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
	}

	default environment = {
		PATH => /usr/bin:/bin:/usr/sbin:/sbin
	}

	environment = {
	<snip>
		PATH => /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
        <snip>
	}
```

I added a custom PATH spec. in Info.plist, putting `/usr/bin` first, and this made code formatting work again for me, but I'd rather not do this for every update. 🙂

Thanks a lot for the awesome Postgres client, other than this small hiccup version 2 has been great!

## What software versions are you using?

Postico version:  2.0beta (8375)
macOS version:  11.4
PostgreSQL version:  11.12

**Comment by martinjankoehler** [comment]
@lsundman Thanks for reporting this Perl PATH issue.

We have fixed this with Postico 2 build 8384, available either with the built-in updater 
or manually at https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8384.dmg

Please let us know if this also fixes the issue on your side.

Best regards,
Martin

**Comment by lsundman** [comment]
Great! Yes, build 8384 fixes my problem, SQL formatting now works as it should. Thanks for the help! 🎉
