### ISSUE TITLE
SSH Host Key check fails

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#78]
There is a bug in Postico 0.26 that can cause the SSH host key check to fail for users on OS X 10.11 (El Capitan). If you are affected, you'll see an error message like the following:

    Failed to connect to the SSH server because the key in the known_hosts file doesn't match.

The new version of SSH on OS X 10.11 supports elliptic curve cryptography, but libssh2 (which Postico uses) does not. So when your `~/.ssh/known_hosts` contains an elliptic curve host key, Postico tries to match it against an RSA host key, which fails.

I'm working on a fix, but in the mean time, you can use this work around:

1. Delete the elliptic curve host key from `known_hosts`
2. Connect to the problematic SSH server using the following command:
`ssh -o HostKeyAlgorithms=ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ssh-rsa,ssh-dss ssh.example.com`
3. When prompted, check the host key and confirm to add it to your known_hosts file

Once an RSA host key is in your known_hosts file, everything should work as expected.

**Comment by jakob** [comment]
This will be fixed in version 0.27.
Prerelease build: https://eggerapps-downloads.s3.amazonaws.com/postico-2015-09-30.zip

**Comment by stefanwiesendanger** [comment]
I can confirm the prerelease build has fixed this issue for me, thanks!

**Comment by fermion** [comment]
Thanks @jakob!

**Comment by patatjenl** [comment]
Fixed in the prerelease build, indeed. Thanks!

**Comment by jakob** [comment]
I've just released 0.27.
Download & changelist: https://eggerapps.at/postico/changelist.html

**Comment by doanerock** [comment]
@jakob just wanted to send you a thank you for fixing this bug.

**Comment by hraban** [comment]
In case someone is looking for a way to delete that key from known_hosts:

    $ ssh-keygen -R <hostname>
