### ISSUE TITLE
Postico 2: Double-clicking cell in results grid no longer highlights value for copy

### ISSUE THREAD

**Issue by wellsoliver** [jakob/Postico#781]
Postico 2.0, 8573, seems like this happened in the last release or something but double clicking on a column in the results grid no longer highlights that cell's value for copy, it doesn't seem to do anything. Only way to copy a cell is right-clicking and Copy Cell, which feels a little more cumbersome to me.

Not sure if it's an intentional change, thought it worth mentioning.

**Comment by martinjankoehler** [comment]
@wellsoliver Thanks for reporting this regression.

Preview build 8589 contains a fix and is available here:
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8589.dmg

Please let us know if this fixes the problem also on your side.

Best regards,
Martin

**Comment by wellsoliver** [comment]
Perfect, thank you. Out of curiosity, how long before those builds make their way the auto update pipeline?

**Comment by martinjankoehler** [comment]
Should be in the auto-updater this week.

**Comment by martinjankoehler** [comment]
The double-click regression fix is now available via the built-in auto updater or as a manual download at
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8602.dmg

Best regards,
Martin
