### ISSUE TITLE
Postico 2: Query fetching column information is invalid

### ISSUE THREAD

**Issue by phildum** [jakob/Postico#782]
## What did you do?

Viewed the content of a view directly from the sidebar

## What did you expect to happen?

A table of data appears

## What actually happened?
```
Query failed
PostgreSQL said: each UNION query must have the same number of columns
```

When looking at detail, it can be seen that the number of columns in the below query are not equal..
```
---------------------------------------------------------------------------------
-- Fetch Column Information -----------------------------------------------------
---------------------------------------------------------------------------------
SELECT 
	attnum,
	attname,
	atttypid,
	attnotnull,
	format_type(atttypid,atttypmod),
	pg_get_expr(adbin, attrelid, true) AS adsrc,
	col_description(attrelid, attnum),
	NULL as typcategory,
	true as has_column_privilege,
	'' as attgenerated,
	'' as attidentity,
	NULL  AS sequence_options

FROM pg_attribute
LEFT JOIN pg_type ON atttypid=pg_type.oid
LEFT JOIN pg_attrdef ON adrelid=attrelid AND adnum=attnum
WHERE attrelid = 'view_name'::regclass
  AND NOT attisdropped
UNION SELECT col_num, col_name, NULL, NULL, col_type, NULL, NULL, NULL, NULL
FROM pg_get_late_binding_view_cols() cols(view_schema name, view_name name, col_name name, col_type varchar, col_num int)
```

## What software versions are you using?

Postico version:  
2, build 8614

macOS version:  
11.5.2

PostgreSQL version:  
Redshift 1.0.29551

**Comment by jakob** [comment]
It looks like we broke Redshift support when we added support for generated columns. We'll fix this as soon as possible.

In the mean time, you can use [Build 8549](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8549.dmg)

(If you open Postico 2 directly from the disk image, auto update is disabled)

**Comment by martinjankoehler** [comment]
@phildum Thanks for reporting this Redshift regression.

We've been working on a fix, it's available via the built-in auto updater or manually at https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8619.dmg

Please let us know if the issue is also fixed on your side.

Best regards,
Martin

**Comment by phildum** [comment]
Thank you, confirmed fixed in 8619
