### ISSUE TITLE
Can't query data after renaming table with primary key type UUID, but works fine in PGAdmin

### ISSUE THREAD

**Issue by joegrenan** [jakob/Postico#784]
## What did you do?

- I renamed a table that has a column with a type of UUID.

## What did you expect to happen?

- I expected Postico to be able to show the data for that table.

## What actually happened?

- Postico displays error: `operator does not exist: uuid = boolean`

```
PG_DIAG_SEVERITY: ERROR
PG_DIAG_SQLSTATE: 42883
PG_DIAG_MESSAGE_PRIMARY: operator does not exist: uuid = boolean
PG_DIAG_MESSAGE_HINT: No operator matches the given name and argument types. You might need to add explicit type casts.
PG_DIAG_STATEMENT_POSITION: 113
PG_DIAG_SOURCE_FILE: parse_oper.c
PG_DIAG_SOURCE_LINE: 722
PG_DIAG_SOURCE_FUNCTION: op_error

SELECT "id", "word", "phoneme", "is_visible", "is_english", "is_suffix" FROM "public"."cmu_words"  WHERE (("id" = false OR "word" = false OR "phoneme" = false OR "is_visible" = false OR "is_english" = false OR "is_suffix" = false)) AND ("word" ILIKE 'hater%') ORDER BY "ctid" ASC  LIMIT 1000
```

## What software versions are you using?

Postico version:  1.5.19
(select "About Postico" from the Postico menu)

macOS version:  11.4
(selecting "About this Mac" from the Apple menu)

PostgreSQL version:  12.8
(execute the command "SELECT VERSION();" to find out)

**Comment by joegrenan** [comment]
Column definition is such: `id uuid NOT NULL DEFAULT uuid_generate_v4(),`

**Comment by jakob** [comment]
@joegrenan It sounds like a filter is active, but it for some reason the filter seems to think the column is a BOOLEAN. Maybe there was a problem restoring a previous filter. I'm not sure how this would happen.

Could you try clearing the filter, and pressing Cmd-R to refresh?

**Comment by joegrenan** [comment]
@jakob oh, that worked perfectly!
