### ISSUE TITLE
Request: Option to combine Queries, Tables & Functions into one tab bar

### ISSUE THREAD

**Issue by nicoburns** [jakob/Postico#785]
## Background

- I have a database with a relatively large number of tables (just over 150, grouped by schema)
- I also have quite a few saved queries (>30, and growing slowly)

## Problem

Navigating through all the tables and queries is quite difficult unless the relevant pane is maximised (I ideally want the Table panel at full height when browsing tables, and the queries panel at full height when browsing queries). This can be achieved at the moment by dragging the panel height, but it is a bit of a pain.

## Proposal

That there is a preference toggle to combine the left sidebar panes into one set of tabs that are always full-height so that switching between full height versions of the panes.

**Comment by martinjankoehler** [comment]
Hello @nicoburns

we've implemented this feature (customizable sidebar tab layout) in Postico 2,
now available via the built-in updater or manually at https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-9378.dmg

Just drag-and-drop the tabs to change the layout and/or use the context menu.

Best regards,
Martin
