### ISSUE TITLE
comments are not saved when adding columns

### ISSUE THREAD

**Issue by zhengyue** [jakob/Postico#79]
In version 0.26, if I add columns to an existing table, the comment of newly added columns are not saved.

**Comment by jakob** [comment]
Good catch! I forgot that in the code that generates the ALTER TABLE query.

Anyway, this will be fixed in version 0.27.
Prerelease build: https://eggerapps-downloads.s3.amazonaws.com/postico-2015-09-30.zip

**Comment by jakob** [comment]
0.27 is now released
https://eggerapps.at/postico/changelist.html
