### ISSUE TITLE
Postico 2 favorites/server import lacks clarity

### ISSUE THREAD

**Issue by thousandsofthem** [jakob/Postico#795]
## What did you do?
* created export of favorites ("export all servers...")
* tried to import them into another computer's copy of Postico 2 ("import servers...")

## What did you expect to happen?

- I expected to see my  fav connections visible 

## What actually happened?

- all i got is empty nested folder "Local Library"

## What software versions are you using?

Postico version:  Postico 2.0 beta 8975 on both machines

macOS version:  
from: 10.14.5
to: 12.0

## Sidenote

Import process is not clear: what exactly should be selected? how would i know?

**Comment by martinjankoehler** [comment]
Hello @thousandsofthem,

thanks for reporting this issue.

Did you get this error?
![Bildschirmfoto 2021-11-15 um 16 32 11](https://user-images.githubusercontent.com/29398377/141809055-c8b09ab1-9062-48cd-b53a-c8937be51363.jpg)

**Comment by thousandsofthem** [comment]
Thanks for the reply!
The issue was on "multi-select all the server directories you want to import". I did try parent folder and the nested folder, didn't expect the need of multi-select at all. Some clear instructions much needed. Thanks again!

**Comment by martinjankoehler** [comment]
> The issue was on "multi-select all the server directories you want to import". I did try parent folder and the nested folder, didn't expect the need of multi-select at all. Some clear instructions much needed. Thanks again!

And thanks again for the feedback!
I'm sure other users will have the same experience, so this UI needs more clarity.

**Comment by martinjankoehler** [comment]
@thousandsofthem we've been working on this issue,
and hava a preview build available for testing: 
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8997.dmg

Please let us know if that improves your user experience or where we still could do better.

Best regards,
Martin

**Comment by thousandsofthem** [comment]
Looks good for me! IMO good enough for everyone. It'll be much harder to make UX better from there - as example, creating separate export format, as in "single file export (renamed .zip)"

**Comment by martinjankoehler** [comment]
This is now improved in the latest Postico 2 version,
available using the built-in updater or manually at https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-9013.dmg

Best regards,
Martin
