### ISSUE TITLE
Feature request: Join Setapp

### ISSUE THREAD

**Issue by harismh** [jakob/Postico#796]
I use both Postico 1.5 and Table Plus, the latter coming a Mac subscription service/market called [Setapp](https://setapp.com). It would be awesome to get Postico 2 into Setapp as I feel it's more featured-paired with Table Plus, and Postico's autocomplete is frankly way better IMO.

Info for joining Setapp: https://setapp.com/developers

**Comment by jakob** [comment]
I really doubt that Setapp pays enough to make it worth the effort.
