### ISSUE TITLE
Visual Bug in preferences (screenshot included)

### ISSUE THREAD

**Issue by reczy** [jakob/Postico#799]
![CleanShot 2021-12-16 at 22 05 36@2x](https://user-images.githubusercontent.com/1100860/146487326-bc9e2ae0-fe92-420b-a559-ab55a31d416e.png)

## What software versions are you using?

Postico version:  
Version 2.0beta (9204)

macOS version:  
12.1 21C52

PostgreSQL version:  
PostgreSQL 14.1 on aarch64-apple-darwin20.6.0, compiled by Apple clang version 12.0.5 (clang-1205.0.22.9), 64-bit (using postgres.app)

**Comment by reczy** [comment]
Also - Thank you for your work on both Postico and Postgres.app. 2 great products!

**Comment by martinjankoehler** [comment]
@reczy Thanks for reporting this layout issue.

The bug is now fixed in the latest build,
available via the built-in autoupdater or manually at
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-9209.dmg

Best regards,
Martin
