### ISSUE TITLE
Make "SQL Query" sidebar option not affected by filtering

### ISSUE THREAD

**Issue by louim** [jakob/Postico#80]
Hello!

It would be really nice if the "SQL QUERY" sidebar option didn't get filtered and was always present, even when the filtering is on. It's a little weird to have to clear search to get access to it again. (Yeah I know there is a keyboard shortcut, but I keep forgetting it :wink: )

![capture d ecran 2015-09-28 a 18 09 46](https://cloud.githubusercontent.com/assets/923718/10150336/f0af0e5c-660c-11e5-8b59-271741642834.png)

**Comment by jakob** [comment]
Hi, thanks for the suggestion. I've just tried implementing this suggestion, and in practice I find it confusing. I'd prefer to leave it like this for the time being.

The bigger issue is that the query doesn't really fit well into that sidebar. I've been thinking about alternatives, but I'm not yet sure where the best place to put it is.

But here's something that may help: Right-click on the toolbar, and select "Customize". Then you can drag a button labelled "SQL Terminal" (should be labelled "SQL Query") to the toolbar. That button won't be affected by filtering, and it will always be there to switch to the SQL Query view.

**Comment by louim** [comment]
@jakob Thank you very much! Have you though about putting the SQL terminal button there by default? It seems like it's the only button that is not present by default.

Anyway, that solved the problem for me, what I really wanted was a permanent SQL terminal button, I'll leave you to close the issue if you want to. :+1:

**Comment by jakob** [comment]
There are other buttons that aren't there by default: "cancel query" and "new window".

I wanted to keep Postico as lean as possible, but since the customisable toolbar is absolutely not discoverable, I might have to reconsider.
