### ISSUE TITLE
Request: Middle click left nav to open new tab?

### ISSUE THREAD

**Issue by cokert** [jakob/Postico#800]
Is there any chance we can get the option to open left nav items in a new tab when clicking with the mouse wheel?  I didn't see this mentioned anywhere in open or closed issues.  This flow is deeply ingrained in me from using it in web browsers for 20 years and I keep trying to do it in postico, but it does nothing.

Speaking of tabs, when you hold down cmd and right click a table, you get the option to open the table in a new window.  It would be nice if there were the equivalent for tabs (when working without a mouse with a click wheel) -- maybe when holding option?

I'm on Postico 1.5.20.

**Comment by cokert** [comment]
I just realized I never replied to this.  This is awesome, thanks for the addition/response.  Would be nice to have on 2.0 as well, but I mostly use 1 right now.

**Comment by martinjankoehler** [comment]
Hey @cokert 

this feature (middle click to open tab) is now included in the latest Postico 2 update available via the built-in updater or manually at https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-9378.dmg

This feature will also be included in the next Postico 1.5 update.

Best regards,
Martin

**Comment by cokert** [comment]
👍  This is awesome, thanks!
