### ISSUE TITLE
Double quotes don't work as intended

### ISSUE THREAD

**Issue by 1st** [jakob/Postico#801]
## What did you do?

- Opened SQL Query tab
- Entered there a query where string value is placed in the double quotes

## What did you expect to happen?

String literals needs o work with single and double quotes

```
# It works with single quotes
SELECT * FROM pg_class WHERE relname='some_name' LIMIT 100;

# But it doesn't when double quotes used
SELECT * FROM pg_class WHERE relname="some_name" LIMIT 100;
```

## What actually happened?

Error in parsing statement appear:

```
ERROR:  column "some_name" does not exist
LINE 1: SELECT * FROM pg_class WHERE relname="some_name" LIMIT 1...
                                             ^
```

## What software versions are you using?

Postico version:  
1.5.20

macOS version:  
12.1

PostgreSQL version:  
13.4

**Comment by ehamberg** [comment]
In [Postgres] SQL queries, strings are always in single quotes [1]:

> A string constant in SQL is an arbitrary sequence of characters bounded by single quotes (')

Double quotes are used for quoted identifiers [2]:

> There is a second kind of identifier: the delimited identifier or quoted identifier. It is formed by enclosing an arbitrary sequence of characters in double-quotes (").

This can be used to e.g. refer to a column named "select" (which, if not quoted, would be interpreted as a keyword).

[1] https://www.postgresql.org/docs/14/sql-syntax-lexical.html#SQL-SYNTAX-CONSTANTS
[2] https://www.postgresql.org/docs/14/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
