### ISSUE TITLE
Crash when opening a new tab from new table screen

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#803]
Postico hangs and is then killed if you open a new tab from the new table screen

- open postico
- from the context menu select `new > table`
- hit `cmd + t`

## What software versions are you using?

Postico version:  
Version 2.0beta (9259)

macOS version:  
12.1 (21C52)

PostgreSQL version:  
PostgreSQL 12.9 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit

**Comment by martinjankoehler** [comment]
Hey @qwesda,
we've had experienced some downtime with our crash report receiver.

It this issue reproducable?
In case yes, could you please repeat the crash?

Is there something special about your environment?
Also, please let us know which option you've configured as an new-tab-strategy:
![Bildschirmfoto 2022-01-27 um 15 50 06](https://user-images.githubusercontent.com/29398377/151382640-4b63dadb-7810-4316-8e6a-e15171916f1c.jpg)

Best regards,
Martin

**Comment by qwesda** [comment]
hi,

the crash is reproducible on my system.  The selected `new tabs opens with`-option is `same view` – I guess that is also where the trouble comes from, since the new tab can't show the not-yet-existent new table. The same thing happens if I select `same view` for the `new windows ...` option.

As far as I know there is nothing to special about my env ...

**Comment by martinjankoehler** [comment]
@qwesda Hi, 

strange, I can't reproduce it here (also with this setting).

In order for us to see the stacktrace,
Could you please help us out by trying the following steps:
1. update to latest version
2. in Postico Preferences: check "Report crashes"
3. trigger the crash

**Comment by jakob** [comment]
I was able to reproduce it on my machine. I think it only happens when you create a new table in the temp schema. I was able to reproduce it like this:

1) Connect to server
2) Create a temp table, save and reload (so that the temp schema shows up)
3) Right click on the temp schema, select "new table"
4) Then press cmd-T to create a new tab
5) Postico crashes

I filed the crash reports under bug_id 89

I discovered a separate bug when testing this which I'm going to record in a separate issue (the UI doesn't update correctly after saving the first temp table).

**Comment by jakob** [comment]
Update: I was wrong about the temp schema. The bug happens also for other schemas, just not for the public schema.

**Comment by qwesda** [comment]
curious, it doesn't happen with the public schema if the `always expand public schema` is checked – otherwise it crashes just like with all other schemas ...

**Comment by martinjankoehler** [comment]
@qwesda we've been working on this issue (Crash when opening new tab from new table/function screen),
a preview build is available at: https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-9289.dmg
Please let us know if this resolved the issue also on your side.

Best regards,
Martin

**Comment by qwesda** [comment]
it seems to be fixed, thanks

**Comment by martinjankoehler** [comment]
We've fixed this issue (Crash when opening new tab from new table/function screen).
The latest Postico 2 build is available using the built-in updater or manually at
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-9295.dmg
