### ISSUE TITLE
Autocomplete stopped working for `pg_temp` schema

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#804]
The autocomplete stopped working for table names in the `pg_temp` schema alias – completion does still work for the actual schema name, i.e. `pg_temp_1`, etc.

```
CREATE TEMP TABLE a AS SELECT * FROM generate_series(1, 1);

SELECT * FROM pg_temp.
```

Typing the `.` does not open the autocomplete menu and hitting `esc` shows `no completions` ...

## What software versions are you using?

Postico version:
Version 2.0beta (9259)

macOS version:
12.1 (21C52)

PostgreSQL version:
PostgreSQL 12.9 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit

**Comment by qwesda** [comment]
that build fixes it, thanks!

**Comment by martinjankoehler** [comment]
@qwesda this fix (autocomplete for pg_temp alias)
is now available via the built-in updater or manually at
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-9287.dmg
