### ISSUE TITLE
Saving first temp table leads to broken UI state

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#805]
## What did you do?

- In the sidebar, click the + and select "New Table"
- Check the "temporary" checkbox
- Press Cmd-S to save

## What did you expect to happen?

- I expect Postico to create a temp table and I expect the UI to update accordingly

## What actually happened?

- Postico creates the temp table, but the UI stays the same, it looks as if nothing happened. No error message is displayed. Trying to save a second time leads to an error. You can press "discard changes" to discard the changes, but when closing the window Postico asks whether to save changes again.

## What software versions are you using?

Postico version:  Version 2.0beta (9288)

macOS version:  12.2 Monterey

PostgreSQL version:  PostgreSQL 12.5

**Comment by martinjankoehler** [comment]
We've fixed this issue in the latest build available via the built-in updater.
