### ISSUE TITLE
crashing when refresh materialized views

### ISSUE THREAD

**Issue by rfbrown** [jakob/Postico#809]
## What did you do?

- I right clicked on a materialized view and selected `Refresh Materialized View`.

## What did you expect to happen?

- I expected the materialized view to refresh without issue.

## What actually happened?

- The app crashed. ~~Upon reopening, I note that the materialized view did not refresh. Retrying doesn't resolve the issue.~~ Behavior appears to be consistent across all materialized views. _Update: the materialized view **is refreshed** upon reopening the app._ 

## What software versions are you using?

Postico version:  2.0beta (9346)
macOS version: 10.14.6
PostgreSQL version: 14.1 (Ubuntu 14.1-2.pgdg20.04+1)

**Comment by jakob** [comment]
Thanks for reporting this issue. It looks like we broke the error checking code.

Build 9381 fixes this bug!
