### ISSUE TITLE
Closing Postico and re-opening doesn't reconnect properly, but re-opens window

### ISSUE THREAD

**Issue by STRML** [jakob/Postico#81]
Looks like a new feature in 0.25+ - I see Postico is trying to re-open windows. But if the password is saved or any other modal popup shows up (such as an insecure connection warning), the reconnection fails, no matter how many times you dismiss the modal or enter your password.

The only way to get it working again is to close the window outright, go back to the Postico main window and re-open the connection via favorites.

**Comment by jakob** [comment]
I've already fixed this issue. I'm just wrapping up some final changes before I can release version 0.27 with this fix. In the mean time, you can download the latest pre-release here:
https://eggerapps-downloads.s3.amazonaws.com/postico-2015-09-30.zip

Anyway, thanks for taking the time to report this issue!

**Comment by STRML** [comment]
<3. Thanks!

**Comment by jakob** [comment]
I just released 0.27
https://eggerapps.at/postico/changelist.html
