### ISSUE TITLE
When changing database tables and functions is no updated (introduced in 9378)

### ISSUE THREAD

**Issue by 0x434d53** [jakob/Postico#810]
## What did you do?

- I connected to a server with several databases
- I switch from database A to another database B

## What did you expect to happen?

- Tables and Functions are shown for database B

## What actually happened?

- Tables and Functions are still shown for database A.

## What software versions are you using?

Postico version:  
9378 - Issue was introduced with this version

macOS version:  
12.2.1 (21D62)

**Comment by jakob** [comment]
Thanks for reporting this. Looks like the bug is in 9376 as well, it was probably a regression related to the configurable sidebar.

**Comment by jakob** [comment]
Build 9380 should fix the issue!

**Comment by 0x434d53** [comment]
Cool thanks :)
