### ISSUE TITLE
[NFR] Specify application_name for the connection

### ISSUE THREAD

**Issue by ovr** [jakob/Postico#818]
## What did you expect to happen?

```sql
SET application_name = 'Postico / version...';
```

## What actually happened?

It's not supported

## What software versions are you using?

Postico version:  1.5.20

macOS version:  12.4

PostgreSQL version:  14.1

**Comment by jakob** [comment]
Postico does set the application_name parameter, as you can confirm by executing this command:

```sql
SHOW application_name;
```

Postico does not set the parameter if the PostgreSQL version does not support it (very old PostgreSQL versions). For PostgreSQL 14, it will set the application name.
