### ISSUE TITLE
Add an option to reset indexes when truncate a table

### ISSUE THREAD

**Issue by joseluisq** [jakob/Postico#823]
You can use this template for reporting bugs.
Feel free to remove parts that are not relevant, or just write something free-form if you prefer.

## What did you do?

- When I right click over my `table1`
- Then click on `truncate...`

## What did you expect to happen?

- I expected to see on the small window and after the `truncate...` menu item is clicked, a check box with the option to `Restart Indextity` or `Reset Indexes` which belongs to `TRUNCATE TABLE table1 RESTART IDENTITY;`

## What actually happened?

- ~The app crashed / got stuck / didn't show something ...~

## What software versions are you using?

Postico version:  
Version 1.5.21 (9417)

macOS version:  
Macos 12.4

PostgreSQL version:  
14.3

**Comment by jakob** [comment]
What do you expect `Reset Indexes` to do?

I checked the [documentation of the TRUNCATE command](https://www.postgresql.org/docs/15/sql-truncate.html) but I found no mention of a RESET INDEXES command.

**Comment by joseluisq** [comment]
Forget what I said. Postico already has the `RESTART IDENTITY` checkbox. I simply did see it :)
