### ISSUE TITLE
Postico 2 - using Navigate > Go to Queries opens query editor for different server

### ISSUE THREAD

**Issue by kendlete33** [jakob/Postico#825]
## What did you do?

- Connected to a server in Servers view
- Pressed Navigate > Go to Queries

## What did you expect to happen?

- I expected to see the query editor for the currently selected server connection

## What actually happened?

- Query editor opened but for a different server entirely. I had the password for this other server saved so postico was able to connect in the background.
- Clicking 'SQL Query' in sidebar works as expected.

## What software versions are you using?

Postico version:  Version 2.0beta (9423)

macOS version:  12.5.1

PostgreSQL version:  PostgreSQL 14.4 on x86_64-pc-linux-gnu, compiled by Debian clang version 12.0.1, 64-bit

**Comment by jakob** [comment]
Thank you for reporting this issue!

The problem was that each window/tab remembers the last used query file, but the "Go to Queries" command did not check if it belongs to the same database.

I've fixed the problem, an update should be available soon!
