### ISSUE TITLE
Paid features do not appear after purchasing the license.

### ISSUE THREAD

**Issue by PetersonFonseca** [jakob/Postico#826]
You can use this template to report bugs.
Feel free to remove parts that aren't relevant or just write something freeform if you prefer.

## What did you do?

I bought a license to be able to search for files but it is still disabled.

## What did you expect to happen?

I would like to be able to search for data in the table

## What really happened?

It remains the same as the free version. I downloaded the latest version and still the new features do not appear.

## What software versions are you using?

Postico version:
1.5.21

macOS version:
macOs Monterey 12.5.1

PostgreSQL Version:
The problem is in the software itself.

**Comment by jakob** [comment]
Thank you for buying Postico!

Postico 1.5 requires a license file for activation. Did you download and double-click the license file?

Did Postico show an confirmation message or an error message?
