### ISSUE TITLE
Monthly subscription option

### ISSUE THREAD

**Issue by hosembafer** [jakob/Postico#828]
Hello and thank you for this great tool!
It would be great to have a subscription option for Postico. I'm using Postico time by time when working on small projects using Postgres, but not that much to purchase the license, it would be great to have a monthly subscription option.

Personally, if the subscription option were available, I would have already spent some money on it for sure.
I'm not sure if it's possible to do with the current license code system, but I think I'm not the only one who would like to spend less but get the software for short time.

Have you done some research on this, could it be financially beneficial for you?

**Comment by hosembafer** [comment]
By the way, users will try and may love the paid features and that could be the trigger for purchasing the full license :)

**Comment by hampelm** [comment]
I would also be happy to do a subscription in order to ensure there is a steady stream of revenue to support building Postico into the future

**Comment by qwesda** [comment]
@hampelm same here. I would pitch in 10EUR per month and I wouldn't want any rewards or premium features ...

**Comment by jakob** [comment]
Thank you for offering your support!

However, I really don't see a need to offer subscriptions.

There are enough new users coming to PostgreSQL every year. Postico earns very consistent revenue from new license sales, and it's enough to support my family. I have no plans to abandon Postico.

I'm also trying to spend more time with my family, which is one of the reasons why progress on new things is slow, and it's also the reason why I work on Postico on my own again. Previously I had an office and 1-2 employees, but surprisingly having employees did not reduce my workload, and the speed in development didn't increase as much as I expected. One day I'll read "The Mythical Man-Month" and maybe understand why. I've also discovered that I'm just not very good at leading a team, so I prefer to work on Postico alone.

If you want to help Postico, please keep sending feedback. Even if I don't respond to everything, I do read every email and every comment on every issue, and it's tremendously helpful to learn how people are using Postico, and what kind of problems you are running into.

@qwesda I won't take money from you, if anything I should be paying you for all the good suggestions you have made over the years :)
