### ISSUE TITLE
How to view types?

### ISSUE THREAD

**Issue by predrag-codetribe** [jakob/Postico#830]
Hello, 👋 

## What did you do?

I created a type:
```sql
CREATE TYPE public.buy_flow_status AS ENUM (
    'pending',
    'rejected',
    'accepted',
);
```

## What did you expect to happen?

- I expected to see that `buy_flow_status` type somewhere in the Postico App (to be able to delete it)

## What actually happened?

- But I do not see it. So I am not able to delete it.
Instead I have to open a different tool(PgAdmin4), and delete the type there. Or write the Query manually in Postico.
As you can see in pgAdmin, I can find the type:

![Screenshot 2023-02-06 at 10 13 59](https://user-images.githubusercontent.com/115091796/216933707-b906c8bd-b0fc-4fc5-a2b0-ca63cb34b149.png)

## What software versions are you using?

Postico version:  
 version 2.0beta (9560)

macOS version:  
13.1 (22C65)

PostgreSQL version:  
PostgreSQL 14.4 on aarch64-apple-darwin20.6.0, compiled by Apple clang version 12.0.5 (clang-1205.0.22.9), 64-bit

... I must say that I do not know postgress that well, and that probably the type is buried somewhere, but I wasn't able to find it.

**Comment by jakob** [comment]
Postico doesn't have a good way to view types / enums.

You can look at the pg_enum table in pg_catalog, but it's probably not the polished interface you were hoping for.
