### ISSUE TITLE
Bug: Hidden columns are copied together with visible columns

### ISSUE THREAD

**Issue by ADTC** [jakob/Postico#831]
## What did you do?

- I hid some columns using "Hide Column" option.
- I selected some rows.
- I copied the rows using "Copy Rows" and pasted in another application.

## What did you expect to happen?

- I expected to paste data from only the visible columns.

## What actually happened?

- It pasted data from all the columns including hidden columns.

## What software versions are you using?

Postico version:  Version 2.0 RC 6 (9481)
macOS version:  13.1 (22C65)
PostgreSQL version:  PostgreSQL 12.11 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-12), 64-bit

Issue first reported in #242.

**Comment by jakob** [comment]
Thanks for reporting this issue. I've fixed it in build 9579.
