### ISSUE TITLE
Postico v1. After reconnection all tabs are closed

### ISSUE THREAD

**Issue by 1st** [jakob/Postico#832]
Postico v1. After reconnection all tabs are closed. I would like to preserve all.my tabs after reconnection to the DB I used.

I use multiple TBs and for each connection I would like to keep their own list of tabs and with their inputs (custom SQL that I entered in the each tab).

Can I expect for this improvement? Thx

**Comment by jakob** [comment]
This is just how standard window tabs on macOS work (see eg. Safari, Finder, etc).

When you quit Postico instead of closing a window, it will restore state with all your tabs (unless you selected "Close Windows when quitting apps" in System seettings)

**Comment by 1st** [comment]
А hi @jakob 

I tried right now and it doesn't restore the tabs.

How to reproduce:
- open Postico v1
- connect to the local host connection that I've in favorites
- open any table
- press cams+T to open another tab. Select another table
- then close the window by pressing a red dot 🔴 
- now you again see the home screen of Postico
- again press Connect button for the same connection
- you see a new window without tabs restored from the last session

**Comment by jakob** [comment]
Yes, that is the expected bahavior. It's just how AppKit (the UI framework on macOS) works.

Restoration of tabs only works when you quit an app:

- Make sure "Close Windows when quitting apps" is not active in System Settings
- Quit the app by pressing Cmd-Q
- Reopen the app
- Windows with tabs should be reopened now

I'm aware that many apps, even Apple apps like Xcode, have a custom implementation of tabs and behave differently. But Postico does not, it uses the standard macOS tabs that were introduced in macOS 10.12.

This is a behaviour I do not intend to change for either Postico 1 or Postico 2.

**Comment by 1st** [comment]
> Yes, that is the expected bahavior. It's just how AppKit (the UI framework on macOS) works.
> 
> 
> 
> Restoration of tabs only works when you quit an app:
> 
> 
> 
> - Make sure "Close Windows when quitting apps" is not active in System Settings
> 
> - Quit the app by pressing Cmd-Q
> 
> - Reopen the app
> 
> - Windows with tabs should be reopened now
> 
> 
> 
> I'm aware that many apps, even Apple apps like Xcode, have a custom implementation of tabs and behave differently. But Postico does not, it uses the standard macOS tabs that were introduced in macOS 10.12.
> 
> 
> 
> This is a behaviour I do not intend to change for either Postico 1 or Postico 2.

Now I see the reason. Didn't know about this trick. I use VACode and when reopen it restores its tabs, like many other apps. And it is so natural to me, that I found that only Postico doesn't follow that rule. But seems that only Postico sticks to the rule of native tabs against other apps.

Thank you. If you will consider overriding the default setting via the menu of the app - will be beneficial and more intuitive for users.
