### ISSUE TITLE
Feature request - byte fields display as hex

### ISSUE THREAD

**Issue by 0x366** [jakob/Postico#839]
Currently the bytes fields aren't displayed and are shown as "BINARY (32 bytes)" instead.

Would be great to have an option in settings to display binary fields as hex: "0xabcde..789."

And when you copy this field it's also copied as hex string.

**Comment by jakob** [comment]
I've started working on this, and the latest dev build supports displaying bytea columns as hex.

You can download the dev build here: https://releases.eggerapps.at/postico2/changelog?update_channel=1

See issue #128 for more details!
