### ISSUE TITLE
problem with certain column names

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#84]
if you create the following table
```
CREATE TABLE "test" (
    "﻿account_name" text
);
```

and then try to view it in postico, you get the following error message" `Could not load table rows. The server said: column "account_name" does not exist`.

On the command line everything works fine.

**Comment by qwesda** [comment]
Correction: it was an invisible character `\ufeff`.
This issue can be closed, but maybe the query editor should highlight characters like these.

**Comment by jakob** [comment]
That's a byte order mark. Where was that? In the column name?

PostgreSQL doesn't really understand any of the special unicode characters amd treats them all like normal word characters; this leads to problems with Cocoa, which has all kinds of special handling for these characters.

I'd like to improve this, so it'd be nice if I could reproduce this issue, if only to add to my collection of edge cases for testing.

Thanks for taking so much time to report issues!

**Comment by qwesda** [comment]
Thanks for fixing the issues! I only report them so that I'll have a good postgres client to work with!

It was a `U+FEFF ZERO WIDTH NO-BREAK SPACE` everybody's favourite invisible character. I got it from a tab separated file I was trying to import into postgres. The error was on my part not catching it, while I was transforming the header line into a create table statement, since *sublime text* also doesn't highlight these characters.

BBEDIT at least makes them look like a normal space (wich is better), but ideally the syntax highlighter should make these give them a coloured background and the width of a normal space.

I think you can't just remove things like these since they might be valid in an insert statement.

**Comment by jakob** [comment]
Byte order marks aka "ZERO WIDTH NO-BREAK SPACE" are now stripped when pasting text into the query view. If people really want to use that character in an insert statement, they'll have to use escape sequences.
