### ISSUE TITLE
Foreign Key — Referenced Table

### ISSUE THREAD

**Issue by NAlexandrov** [jakob/Postico#85]
Hello. In last update, referenced table list in Foreign Key menu not sorted:

![Referenced Table list](https://habrastorage.org/files/df8/019/32e/df801932e7ad4932b0dceb93f3a53e40.png)

**Comment by jakob** [comment]
Fixed in the latest prerelease:
https://eggerapps-downloads.s3.amazonaws.com/postico-1235.zip

**Comment by NAlexandrov** [comment]
Thank you

**Comment by jakob** [comment]
Fixed in version 1.0
https://eggerapps.at/postico/changelist.html
