### ISSUE TITLE
New favorites clobber existing saved password

### ISSUE THREAD

**Issue by tschaub** [jakob/Postico#855]
## What did you do?

- I created a new favorite with a new nickname and a new password
- I chose to save the password for the new favorite in Keychain
- I successfully connected using the new favorite
- Later, I tried to use an old favorite

## What did you expect to happen?

- I expected to be able to connect using the old favorite

## What actually happened?

- I got prompted to enter the password for the old favorite
- After entering this, I was able to connect using the old favorite
- Later, I tried to use the new favorite and found that it didn't work

## What software versions are you using?

Postico version:  
1.5.22

macOS version:  
13.3.1 (a)

PostgreSQL version:  
various

## Background

I regularly use [`cloud-sql-proxy`](https://github.com/GoogleCloudPlatform/cloud-sql-proxy) to connect to Postgres CloudSQL instances.  I generally use the same port with `cloud-sql-proxy`.  Often, I work with instances that share database names with other instances.  I would like to be able to save credentials using Postico favorites.

It looks like Postico (1.5) uses `postgres://<host>:<port> (<db>)` as the name for keychain items.  So if I create a new favorite that shares the port and db name with an existing favorite, I guess my password for the old favorite gets overwritten.

Would it be possible to include a favorite id or something else in the Keychain item name to uniquely distinguish saved passwords for Postico favorites?

I am a very satisfied paying customer and will happily upgrade to Postico 2 if this feature already exists there.  I checked the [changelog](https://releases.eggerapps.at/postico2/changelog) but didn't see anything that looked like this, so I thought I would ask.

**Comment by jakob** [comment]
Yes, this problem was fixed in Postico 2.

Unfortunately there is no easy way to fix this in Postico 1.5, otherwise I would have fixed it for the old version as well. I don't want this to be the reason people upgrade to Postico 2. But changing how passwords are saved in Postico 1.5 would risk causing a lot of issues for people.

**Comment by tschaub** [comment]
Thanks for clarifying, @jakob
