### ISSUE TITLE
Format large numbers in the UI

### ISSUE THREAD

**Issue by ehamberg** [jakob/Postico#858]
It would be great if the number of rows in a result was formatted according to locale, so that e.g. “23720” would be formatted as e.g. “23,720” or “23 720” depending on the system's region settings.

Not super important, but would be great for avoiding mini heart-attacks when misreading a number early in the morning. 😇

![CleanShot 2023-10-19 at 10 34 21@2x](https://github.com/jakob/Postico/assets/16063/380726f8-dac5-47cb-9c4e-a712d0405185)

## What software versions are you using?

Postico version:  Version 2.1 dev (9658)

**Comment by qwesda** [comment]
oh yes please!

<img width="161" alt="image" src="https://github.com/jakob/Postico/assets/384993/c3dc1902-4f3f-4996-be19-0407129fb819">

**Comment by qwesda** [comment]
just noticed, thank you!

<img width="148" alt="image" src="https://github.com/jakob/Postico/assets/384993/85bad53b-d941-4914-830e-7ae8ea284558">

**Comment by jakob** [comment]
Oh yes, I forgot to post a comment here :)

I added the number formatting in Build 9674
