### ISSUE TITLE
Support Microsoft Entra ID authentication (formerly Azure AD)

### ISSUE THREAD

**Issue by Bouke** [jakob/Postico#860]
In our company we'd like to authenticate all users through Entra ID/Azure AD. Currently this requires manual steps to authenticate, like grabbing a token through the cli. It would be great if Postico would support this natively.

See also: https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-configure-sign-in-azure-ad-authentication

**Comment by jakob** [comment]
I've just added a new feature to Postico to help with this use case: A pre-connect shell script.

Can you download the latest development build from https://releases.eggerapps.at/postico2/changelog?update_channel=1 and see if you can figure it out? It should be pretty straightforward, but I want to know if the feature is understandable and if the docs are adequate.

**Comment by jakob** [comment]
I've tested connecting to Azure PostgreSQL (flexible server) with Entra ID and it was pretty straightforward to set up.

I've added docs specifically for Entra ID here: https://eggerapps.at/postico2/documentation/connection-preconnect-script.html#azure

@Bouke could you confirm that this works?

**Comment by Bouke** [comment]
@jakob sorry for not getting back to you on this sooner. This works great, thank you.
