### ISSUE TITLE
support `NULLS NOT DISTINCT` option for unique indices

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#868]
PG 15 added the `UNIQUE [ NULLS [NOT] DISTINCT ]` option. I'm pretty happy about this and use it frequently, but it would be even better if this was supported in the UI.

**Comment by jakob** [comment]
I added support for NULLS NOT DISTINCT in Build 9675

**Comment by qwesda** [comment]
thank you very much! seems to work as far as I can tell.

**Comment by qwesda** [comment]
my colleague just spotted a typo here ...

<img width="224" alt="image" src="https://github.com/jakob/Postico/assets/384993/75123284-b1e1-4141-8eb1-69cc18043e24">

**Comment by jakob** [comment]
Thank you! Typo will be fixed in the next build!
