### ISSUE TITLE
Support CoPilot or GPT interaction

### ISSUE THREAD

**Issue by yepher** [jakob/Postico#871]
This is a feature request.

I love CoPilot and GPT to help with various development tasks. It would be great if Postico could support CoPilot to help generate SQL commands and understand a given database schema.

The way I see it working is a text entry box in a side panel where user can enter their "prompt". Postico should transparently include the currently open table schema (or content of SQL query if open) as part of the prompt to help GPT answer the question. (Very similar to how VS Code CoPilot chat works.

Here is a screenshot from VS Code to demonstrate what that looks like in case you do not use it yourself:
![copilot_chat](https://github.com/jakob/Postico/assets/1359331/fc5f01b9-53cf-42bb-8832-fc77e6546b29)

In my mind, it would be something like this:

![copilot](https://github.com/jakob/Postico/assets/1359331/76ee2d4a-385c-4a7f-9198-0113f340b13d)

**Comment by bran0h** [comment]
Hey @jakob , asking one year later, can we add this feature now? 👀

**Comment by jakob** [comment]
My opinion on LLMs has changed a bit, I actually do find them surprisingly useful.

It's still not something that I want to add to Postico right now. I'll leave it to others to figure out how to best integrate AI into a database client.

**Comment by DeoLeung** [comment]
maybe starts from sql completion hint :)

**Comment by philfreo** [comment]
I feel like this is the main thing missing from postico. Simple v1 is just: a button that's a prompt input so you can type your question, and the database schema/ ddl is passed along with it to an LLM along with your system prompt, and it spits the SQL result into the editor for a human to review and edit or run. Settings panel would specify OpenAI key and optional API endpoint. 

If you want to go even simpler:
Having a one click way to get the entire database schema/ddl copied as plaintext so it can be pasted into ChatGPT would also help vs requiring usage of pgdump.
