### ISSUE TITLE
Login to database without password

### ISSUE THREAD

**Issue by schovi** [jakob/Postico#88]
I am trying to access database without any password (via ssh connection) and Postico still prompt me to enter one. Is there any special what i have to do?
Postico version 0.28

**Comment by jakob** [comment]
Probably the server requested a password. Make sure that pg_hba.conf is set up correctly -- when connecting via ssh, you're connecting via tcp, not via unix domain sockets.

Also, check the server log to see why it requests a password.

**Comment by jakob** [comment]
Did you find a way to fix the problem?

**Comment by schovi** [comment]
Hi,

my solution was simply to set password on database :) But good to know for
future.
Thanks and can't wait for new features in Postico

**Comment by jakob** [comment]
OK, glad you found a way to fix your issue. Finding the correct incantations to use in pg_hba files is often challenging...

**Comment by djbp** [comment]
I have solved this problem by changing the `md5` requirement in the pg_hba.conf file to `trust`:
```
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
```
As this is a local development server, this should not matter - however I'd not recommend such a change for a production environment.
