### ISSUE TITLE
Bug: database, role and user search_path is not respected

### ISSUE THREAD

**Issue by yinzara** [jakob/Postico#888]
## What did you do?

- Open a Postico 2 window to any database, assume it's called "my_database"
- `CREATE TABLE my_table (id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY);`
- `SELECT * FROM my_table;` <- no results returned as expected
- `ALTER SCHEMA "public" RENAME TO "my_schema";` <- rename the public schema to a better name
- `ALTER DATABASE "my_database" SET search_path = "my_schema";` <- change the search path of the database to the better name
- `SELECT * FROM my_table;` 
```shell
ERROR:  relation "my_table" does not exist
LINE 1: select * from my_table;
```
- `ALTER USER CURRENT_USER SET search_path = "my_schema";` <- change the search path of the current user, still no change
- `SELECT * FROM my_table;` 
```shell
ERROR:  relation "my_table" does not exist
LINE 1: select * from my_table;
```
- `ALTER ROLE CURRENT_ROLE SET search_path = "my_schema";` <- change the search path for the current role, still no change
- `SELECT * FROM my_table;` 
```shell
ERROR:  relation "my_table" does not exist
LINE 1: select * from my_table;
```
## What did you expect to happen?

- All 3 select statements should have resulted in no results returned, not an error
- If I execute the exact same commands using the `psql` client everything works as expected

## What actually happened?

```shell
ERROR:  relation "my_table" does not exist
LINE 1: select * from my_table;
```

- Additionally, when I look at the Postico list of tables, instead of showing all the tables of "my_schema" as the root, like it normally does for the "public" schema, it instead shows it under the "my_schema" folder. Not THAT big a deal, but technically wrong.

## What software versions are you using?

Postico version:  2.1.2 (9703)

macOS version:  15.0.1 (24A348)

PostgreSQL version:  PostgreSQL 14.13 (Debian 14.13-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

**Comment by jakob** [comment]
It sounds like you are new to PostgreSQL! I have a few suggestions:

1. Renaming the public schema is not something that I recommend.  
The "public" schema has special meaning in PostgreSQL, a lot of tools and extensions assume that there is a public schema, and handle it specially, like Postico does in the sidebar. I would recommend to create an additional schema, and just leave the public schema empty.

2. `ALTER USER / DATABASE ... SET SEARCH_PATH = ....` only sets the default value  
These commands do not affect open connections. You need to disconnect and reconnect for the setting to take effect. If you want to change a configuration parameter for the current session, please use `SET SEARCH_PATH = ...`.

3. You can use the `SHOW` command to show current value of config parameters

4. `ALTER USER` and `ALTER ROLE` are equivalent.  
There is no difference between these commands. It's customary to use `USER` for a `ROLE` that can log in, but that's just a convention. These two commands do exactly the same thing.

**Comment by yinzara** [comment]
You are absolutely right :-) thank you!
