### ISSUE TITLE
Allow to connect using unix domain sockets

### ISSUE THREAD

**Issue by flowersinthesand** [jakob/Postico#89]
It seems that Postico 0.28 doesn't support Unix-domain socket yet.

> '/Users/donghwankim/path/to/postgresql' looks like a socket path. Postico can't connect to unix domain sockets. Leave the field blank to connect via TCP.

**Comment by jakob** [comment]
This is unfortunately not possible due to limitations in OS X. Postico is a sandboxed application, and sandboxed apps can't connect to unix domain sockets outside of their sandbox.

**Comment by flowersinthesand** [comment]
I'm sorry to hear that. Anyway, thanks for the great work.

**Comment by infowolfe** [comment]
Shouldn't postico be able to connect to unix domain sockets over ssh tunnel?

**Comment by chuttam** [comment]
Linking to a post with what worked for me and that could help others who land here. It's specific to Postico: https://changingrainbows.medium.com/forwarding-unix-sockets-via-ssh-to-tcp-connection-4eebf16c11b4
