### ISSUE TITLE
favourites window should have a "new window" button for "open" connections

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#9]
Sometimes I have the issue that I want to open a new window, I hit `cmd+N` only to find that the only option I have is "disconnect". Than I have to hunt through my open windows and find one that belongs to this favourite and hit the "new window button" there.

I also don't really see the point of the "disconnect" button – as long as a connection window is open I expect it to have a connection. Maybe having just two buttons "open" and "edit" regardless of wether a connection is already open, would be best.

**Comment by jakob** [comment]
I added a "new window" button in 0.25. I left the disconnect button because it may be useful (e.g. you want to close all connections quickly so a server can restart gracefully)

More info: https://eggerapps.at/postico/changelist.html
