### ISSUE TITLE
Needs support for relationships

### ISSUE THREAD

**Issue by tblanchard** [jakob/Postico#91]
The problem with all the database editors is they don't understand foreign keys - even when foreign key constraints are added to the table - and so navigating across records is still a pain.

Please add support for relationship navigation based on foreign key constraints or even rails style foreign key naming conventions.

**Comment by jakob** [comment]
Postico does understand foreign keys. You can click the table icon next
to foreign key values to select a new value from the related table, or
you can even jump directly to the foreign table. If you activate the
sidebar, you'll see related rows inline.

However, Postico doesn't do any heuristics to detect relations. You need
to actually set up foreign key constraints for Postico to understand the
relations (which you can do in the table structure editor)

The only thing that's missing is support for the reverse relationship
(it's not yet possible to show a list of all rows referencing a specific
id). This also means that many-to-many relations aren't supported yet.

**Comment by jakob** [comment]
I'm closing this issue for now. Feel free to reopen it if you have anything to add!
