### ISSUE TITLE
No support for PostGIS geometry columns

### ISSUE THREAD

**Issue by tblanchard** [jakob/Postico#92]
They look like gibberish.  I'll buy the first database management tool that understands GIS.  Until it does, I don't find it any better than navicat - which I already own.

**Comment by jakob** [comment]
Hey Todd,

you are right, Postico is practically unusable for PostGIS. I'm not a PostGIS user myself, so I have to completely rely on customer feedback for this.

I talked about this with another customer some time ago, and as far as I understand it would be best if Postico displayed geography and geometry columns in EWKT format.

I tried implementing this. Could you try if this build does what you expect?
https://eggerapps-downloads.s3.amazonaws.com/postico-2015-10-21.zip

Are there any other ideas that would help PostGIS users?

**Comment by smnorris** [comment]
I disagree that is is unusable for PostGIS, I don't generally need to see individual geometries to develop a query and can fire up some other tool to look at things on a map. What I want is a good view of what tables and columns are available & a good text editor interface with autocomplete. 

That said, displaying geom/geog columns as text is definitely a handy shortcut.

Regardless of how it is displayed there has to be some logic on how many records to pull into memory when executing a query or opening a table directly. Currently the app seems to try and load everything - I opened a fairly large table with a geom column but didn't bother wait to see if it would complete after 10s or so.

A sql client with a very simple map window would be extremely handy.

**Comment by jakob** [comment]
Thanks for your input Simon!

A map interface is probably beyond the scope of Postico for now, considering how complicated working with geographic data is.

Concerning the slow load time: Postico defaults to loading 1000 rows. This setting can be changed in the preferences. When executing SQL, there is no limit, you need to add limit/offset clauses manually.

**Comment by jakob** [comment]
Would custom filters for geometry columns be useful?

**Comment by smnorris** [comment]
Filters based on postgis functions? Presumably to do the comparison I'd have to paste some text defining a bounding box or a geometry. Might be useful but I can't think of any instances where I'd use it, most geometry comparisons are between geometries in different tables.

**Comment by jakob** [comment]
What about filters that don't involve another geometry? Maybe filtering based on geometry type would make sense? Eg. show all rows that contain a POINT? Or filter rows that have a specific SRID? Or filter geometries that have an area larger than some value?

Would sorting geometry columns by area/length/type make sense?

**Comment by smnorris** [comment]
Traditionally all rows in a given geometry column will have the same geometry type and SRID. But I'm sure there are cases out there where that would be useful.

Filtering and sorting based on area/length definitely makes sense.

**Comment by jakob** [comment]
Thanks for all your feedback. I'm closing this issue now since the original problem has been fixed. If you have any other suggestions, feel free to open a new issue!

**Comment by smnorris** [comment]
fyi, one way to visualize postgis geometries
https://github.com/NYCPlanning/postgis-preview
