### ISSUE TITLE
"copy name" context menu option for column headers (in the query results window)

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#97]
this is the same as issue #13, but it should also work in the query results view.

**Comment by jakob** [comment]
I also added this in the latest prerelease:
https://eggerapps-downloads.s3.amazonaws.com/postico-1228.zip

**Comment by qwesda** [comment]
works as expected, thanks!

**Comment by jakob** [comment]
Fixed in version 1.0
https://eggerapps.at/postico/changelist.html
