### ISSUE TITLE
Read-Only Mode

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#99]
Several customers have requested a READ-ONLY mode for Postico, to avoid potentially dangerous operations when connecting to production databases.

Probably this means disabling all editing features in the UI, but it would also require scanning queries executed in the SQL terminal.

I'm a bit scared of implementing something like this, since a bug in this functionality will lead to dangerous data loss, but I understand how this could be a very valuable feature.

Is this something that is interesting for more people? Any suggestions?

**Comment by motns** [comment]
+1 for the feature - I already use colour coding to highlight the production DB in red, but an additional safety net would be really nice.

I suppose a possible starting point could be to just disable editing/deleting in the table views; it's less risky and makes most browsing operations safer. Scanning queries could come later then, but like you say that sounds more risky.

Also, at least in JDBC there's an option to make the database connection read-only, so that write operations are blocked at that level. I don't know what driver you're using, but maybe a "brute force" approach of making the connection itself read-only, and then handling any "not allowed" errors coming would be an option.

Just my two cents worth... Thanks for a great product!

**Comment by wellsoliver** [comment]
I like it, I'd be totally fine if it just disabled the data editing functionality of the UI (clicking on cells, etc) and left the SQL up to the user. I mean, if you want read only and you write some UPDATE queries, I feel like it's your own problem.

**Comment by jakob** [comment]
@motns I don't use the JDBC driver, I use libpq. Libpq doesn't offer a read-only mode. I'll look at the JDBC driver and try to find out how they implement the read-only mode.

@wellsoliver I get where you are coming from, but it would be nice if the "Read-Only Mode" also protected you against accidentally executing the wrong query (eg. when you hit Cmd-Enter and your cursor was on the wrong line).

**Comment by qwesda** [comment]
I don't really understand the use case. Wouldn't it be better if you create a db-user that only has connect and read permissions and use this one for the postico connection?
Having the db enforce read-only-ness is much safer than reimplementing it in a layer above the db.

**Comment by YesThatAllen** [comment]
I agree with Quesda... if I want a read-only connection, I'll make a read-only user.

**Comment by jakob** [comment]
Thanks for your input. After considering the options, I agree that implementing a read-only-mode doesn't make a lot of sense. First of all, every action in Postico that modifies the database already requires confirmation anyway. Second of all, to protect against inadvertent changes, it's definitely better to use PostgreSQL's built-in access control features. Trying to prevent changes on the client side is bound to be buggy. It will be little used code, since it will only be invoked accidentally, further increasing the likelyhood of bugs.

The only case where this feature would make sense is if you are connecting to a hosted PostgreSQL database and don't have a way to create a read-only user. In that case I think the better way is to contact your hosting provider and request a read-only user, rather than trying to fix the problem on the client side.

Thanks again to everyone for their input; I'm closing this issue now.

**Comment by unikzforce** [comment]
you have added it on postico 2, now we have to pay extra to upgrade to postico 2, 
dirty trick

**Comment by jakob** [comment]
In case someone finds this old issue:

In Postico 2 we added support  startup queries, which you can use to set the transaction mode to READ ONLY: https://eggerapps.at/postico2/documentation/read-only-connections.html
